from app.blocks import Show
from app.conditions.compound import MultiBaseType, TierStyle
from app.conditions.standard import Rarity, BaseType
from app.categories import TIER, RARITY

tier_0 = [
    "Leather Belt",
    "Heavy Belt",
    "Ring",
    "Paua Amulet",
    "Elegant Round Shield",
]
double_corrupt = [
    "Scholar's Robe",
    "Majestic Plate",
    "Colosseum Plate",
    "Desert Brigandine",
    "Devout Chainmail",
    "Saint's Hauberk",
    "Simple Robe",
]
rules = [
    Show(
        [
            Rarity(RARITY.UNIQUE),
            MultiBaseType(tier_0),
            TierStyle(TIER.LEGENDARY),
        ],
    ),
    Show(
        [
            Rarity(RARITY.UNIQUE),
            MultiBaseType(double_corrupt),
            TierStyle(TIER.LEGENDARY),
        ],
    ),
    Show(
        [
            Rarity(RARITY.UNIQUE),
            BaseType("Imperial Staff"),
            TierStyle(TIER.RARE),
        ],
    ),
]

dust_uniques = [
    {"name": "Original Sin", "multiplier": "1128.89"},
    {"name": "Replica Cortex", "multiplier": "1064.09"},
    {"name": "Headhunter", "multiplier": "891.16"},
    {"name": "Mageblood", "multiplier": "891.16"},
    {"name": "Defiance of Destiny", "multiplier": "891.16"},
    {"name": "Reefbane", "multiplier": "851.24"},
    {"name": "Replica Shroud of the Lightless", "multiplier": "791.78"},
    {"name": "Stasis Prison", "multiplier": "791.78"},
    {"name": "The Squire", "multiplier": "768.72"},
    {"name": "Rakiata's Dance", "multiplier": "768.72"},
    {"name": "Angler's Plait", "multiplier": "734.29"},
    {"name": "Starforge", "multiplier": "703.49"},
    {"name": "Voidforge", "multiplier": "703.49"},
    {"name": "Replica Kongor's Undying Rage", "multiplier": "703.49"},
    {"name": "Echoforge", "multiplier": "703.49"},
    {"name": "Lioneye's Glare", "multiplier": "683"},
    {"name": "Divinarius", "multiplier": "683"},
    {"name": "Essentia Sanguis", "multiplier": "683"},
    {"name": "Kingmaker", "multiplier": "683"},
    {"name": "Soul Taker", "multiplier": "663.11"},
    {"name": "Voltaxic Rift", "multiplier": "643.79"},
    {"name": "Atziri's Disfavour", "multiplier": "643.79"},
    {"name": "Replica Duskdawn", "multiplier": "643.79"},
    {"name": "Bloodseeker", "multiplier": "606.84"},
    {"name": "The Saviour", "multiplier": "606.84"},
    {"name": "Replica Tukohama's Fortress", "multiplier": "589.16"},
    {"name": "Kalandra's Touch", "multiplier": "572"},
    {"name": "Bino's Kitchen Knife", "multiplier": "539.17"},
    {"name": "Marohi Erqi", "multiplier": "523.46"},
    {"name": "The Winds of Fate", "multiplier": "493.41"},
    {"name": "Hateforge", "multiplier": "389.5"},
    {"name": "Uul-Netol's Vow", "multiplier": "367.15"},
    {"name": "Soul Ascension", "multiplier": "317.64"},
    {"name": "Nimis", "multiplier": "317.64"},
    {"name": "Replica Headhunter", "multiplier": "316.7"},
    {"name": "The Tower of Ordeals", "multiplier": "282.22"},
    {"name": "Yoke of Suffering", "multiplier": "236.36"},
    {"name": "Replica Poorjoy's Asylum", "multiplier": "229.47"},
    {"name": "Manastorm", "multiplier": "210"},
    {"name": "Replica Bated Breath", "multiplier": "206"},
    {"name": "Stranglegasp", "multiplier": "203.28"},
    {"name": "Replica Farrul's Fur", "multiplier": "186.58"},
    {"name": "Kitava's Feast", "multiplier": "181.15"},
    {"name": "Replica Nebulis", "multiplier": "181.15"},
    {"name": "Malachai's Mark", "multiplier": "175.87"},
    {"name": "Replica Windripper", "multiplier": "170.75"},
    {"name": "Tidebreaker", "multiplier": "165.78"},
    {"name": "Replica Eternity Shroud", "multiplier": "165.78"},
    {"name": "Annihilation's Approach", "multiplier": "165.78"},
    {"name": "Eternal Damnation", "multiplier": "165.78"},
    {"name": "Duskdawn", "multiplier": "160.95"},
    {"name": "The Brine Crown", "multiplier": "156.26"},
    {"name": "Replica Atziri's Acuity", "multiplier": "156.26"},
    {"name": "Garukhan's Flight", "multiplier": "151.71"},
    {"name": "The Utmost", "multiplier": "151.26"},
    {"name": "Tukohama's Fortress", "multiplier": "147.29"},
    {"name": "Entropic Devastation", "multiplier": "134.79"},
    {"name": "Cloak of Tawm'r Isley", "multiplier": "127.05"},
    {"name": "Arakaali's Fang", "multiplier": "116.27"},
    {"name": "Martyr of Innocence", "multiplier": "112.89"},
    {"name": "Song of the Sirens", "multiplier": "111.95"},
    {"name": "Zerphi's Last Breath", "multiplier": "106.41"},
    {"name": "Replica Alberon's Warpath", "multiplier": "103.31"},
    {"name": "Replica Maloney's Mechanism", "multiplier": "91.79"},
    {"name": "Replica Trypanon", "multiplier": "79.18"},
    {"name": "Gruthkul's Pelt", "multiplier": "74.63"},
    {"name": "Dialla's Malefaction", "multiplier": "72.46"},
    {"name": "Ralakesh's Impatience", "multiplier": "70.35"},
    {"name": "Skyforth", "multiplier": "69.77"},
    {"name": "Infused Beachhead", "multiplier": "67.73"},
    {"name": "Wraithlord", "multiplier": "66.31"},
    {"name": "Eyes of the Greatwolf", "multiplier": "65.76"},
    {"name": "The Dark Seer", "multiplier": "62.5"},
    {"name": "Ryslatha's Coil", "multiplier": "62.5"},
    {"name": "The Vinktar Square", "multiplier": "61.99"},
    {"name": "Shade of Solaris", "multiplier": "58.91"},
    {"name": "Void Battery", "multiplier": "56.73"},
    {"name": "Rigwald's Quills", "multiplier": "56.73"},
    {"name": "The Brass Dome", "multiplier": "56.73"},
    {"name": "Light of Lunaris", "multiplier": "55.53"},
    {"name": "Sin's Rebirth", "multiplier": "53.91"},
    {"name": "Soul Ripper", "multiplier": "53.91"},
    {"name": "Seven-League Step", "multiplier": "53.47"},
    {"name": "Warrior's Legacy", "multiplier": "53.47"},
    {"name": "Astral Projector", "multiplier": "53.47"},
    {"name": "Replica Pillars of Arun", "multiplier": "51.91"},
    {"name": "Aegis Aurora", "multiplier": "50.4"},
    {"name": "The Tides of Time", "multiplier": "50.4"},
    {"name": "Atziri's Splendour", "multiplier": "48.93"},
    {"name": "Doryani's Machinarium", "multiplier": "48.93"},
    {"name": "Shroud of the Lightless", "multiplier": "47.51"},
    {"name": "Voll's Devotion", "multiplier": "46.12"},
    {"name": "Shavronne's Revelation", "multiplier": "46.12"},
    {"name": "Windripper", "multiplier": "46.12"},
    {"name": "Magna Eclipsis", "multiplier": "46.12"},
    {"name": "Doryani's Fist", "multiplier": "44.78"},
    {"name": "Indigon", "multiplier": "44.78"},
    {"name": "Farrul's Fur", "multiplier": "44.78"},
    {"name": "Farrul's Chase", "multiplier": "44.78"},
    {"name": "The Red Nightmare", "multiplier": "43.84"},
    {"name": "The Green Nightmare", "multiplier": "43.84"},
    {"name": "The Blue Nightmare", "multiplier": "43.84"},
    {"name": "Rational Doctrine", "multiplier": "43.84"},
    {"name": "Kaom's Heart", "multiplier": "43.48"},
    {"name": "Rathpith Globe", "multiplier": "43.48"},
    {"name": "Prism Guardian", "multiplier": "43.48"},
    {"name": "Broken Faith", "multiplier": "43.48"},
    {"name": "Cospri's Malice", "multiplier": "43.48"},
    {"name": "Inpulsa's Broken Heart", "multiplier": "43.48"},
    {"name": "Hand of Wisdom and Action", "multiplier": "43.48"},
    {"name": "The Red Trail", "multiplier": "43.48"},
    {"name": "Doryani's Delusion", "multiplier": "43.48"},
    {"name": "The Queen's Hunger", "multiplier": "43.48"},
    {"name": "Maloney's Mechanism", "multiplier": "43.48"},
    {"name": "Brutal Restraint", "multiplier": "43.48"},
    {"name": "Badge of the Brotherhood", "multiplier": "43.48"},
    {"name": "The Immortal Will", "multiplier": "43.48"},
    {"name": "Replica Kaom's Heart", "multiplier": "43.48"},
    {"name": "Replica Red Trail", "multiplier": "43.48"},
    {"name": "Viridi's Veil", "multiplier": "43.48"},
    {"name": "Doppelgänger Guise", "multiplier": "43.48"},
    {"name": "Grace of the Goddess", "multiplier": "43.48"},
    {"name": "Thunderfist", "multiplier": "42.21"},
    {"name": "Steppan Eard", "multiplier": "42.21"},
    {"name": "Heretic's Veil", "multiplier": "42.21"},
    {"name": "Machina Mitts", "multiplier": "42.21"},
    {"name": "Sporeguard", "multiplier": "42.21"},
    {"name": "Doryani's Prototype", "multiplier": "42.21"},
    {"name": "Progenesis", "multiplier": "41.32"},
    {"name": "Paradoxica", "multiplier": "40.98"},
    {"name": "The Yielding Mortality", "multiplier": "40.98"},
    {"name": "Replica Paradoxica", "multiplier": "40.98"},
    {"name": "Replica Allure", "multiplier": "40.98"},
    {"name": "Hyrri's Ire", "multiplier": "39.79"},
    {"name": "The Formless Inferno", "multiplier": "39.79"},
    {"name": "The Perfect Form", "multiplier": "39.79"},
    {"name": "Doedre's Skin", "multiplier": "39.79"},
    {"name": "The Eternity Shroud", "multiplier": "39.79"},
    {"name": "Replica Perfect Form", "multiplier": "39.79"},
    {"name": "Replica Hyrri's Ire", "multiplier": "39.79"},
    {"name": "Varunastra", "multiplier": "38.63"},
    {"name": "Uul-Netol's Embrace", "multiplier": "38.63"},
    {"name": "The Surrender", "multiplier": "38.63"},
    {"name": "Disintegrator", "multiplier": "38.63"},
    {"name": "Loreweave", "multiplier": "38.63"},
    {"name": "Replica Loreweave", "multiplier": "38.63"},
    {"name": "Yaomac's Accord", "multiplier": "38.63"},
    {"name": "Replica Stampede", "multiplier": "37.5"},
    {"name": "The Devourer of Minds", "multiplier": "37.5"},
    {"name": "Shavronne's Wrappings", "multiplier": "36.41"},
    {"name": "Darkscorn", "multiplier": "36.41"},
    {"name": "Kintsugi", "multiplier": "36.41"},
    {"name": "Tulfall", "multiplier": "36.41"},
    {"name": "Esh's Visage", "multiplier": "36.41"},
    {"name": "Arborix", "multiplier": "36.41"},
    {"name": "Apep's Supremacy", "multiplier": "36.41"},
    {"name": "The Surging Thoughts", "multiplier": "36.41"},
    {"name": "The Admiral", "multiplier": "36.41"},
    {"name": "Replica Cold Iron Point", "multiplier": "36.41"},
    {"name": "Replica Tulfall", "multiplier": "36.41"},
    {"name": "Abberath's Hooves", "multiplier": "34.61"},
    {"name": "Mjölner", "multiplier": "34.32"},
    {"name": "Replica Abyssus", "multiplier": "34.32"},
    {"name": "Replica Mistwall", "multiplier": "34.32"},
    {"name": "The Iron Fortress", "multiplier": "33.32"},
    {"name": "Farrul's Pounce", "multiplier": "33.32"},
    {"name": "Fleshcrafter", "multiplier": "33.32"},
    {"name": "Gravebind", "multiplier": "33.32"},
    {"name": "Xoph's Nurture", "multiplier": "32.35"},
    {"name": "Crown of the Tyrant", "multiplier": "32.35"},
    {"name": "Crest of Desire", "multiplier": "32.35"},
    {"name": "Farrul's Bite", "multiplier": "31.41"},
    {"name": "Offering to the Serpent", "multiplier": "31.41"},
    {"name": "Oriath's End", "multiplier": "30.75"},
    {"name": "Garb of the Ephemeral", "multiplier": "30.49"},
    {"name": "Maata's Teaching", "multiplier": "30.49"},
    {"name": "Corpsewalker", "multiplier": "29.6"},
    {"name": "The Fourth Vow", "multiplier": "29.6"},
    {"name": "The Devouring Diadem", "multiplier": "28.74"},
    {"name": "Qotra's Regulator", "multiplier": "28.74"},
    {"name": "Atziri's Reflection", "multiplier": "28.74"},
    {"name": "Sandstorm Visage", "multiplier": "28.74"},
    {"name": "The Tempest Rising", "multiplier": "28.74"},
    {"name": "Utula's Hunger", "multiplier": "27.91"},
    {"name": "The Celestial Brace", "multiplier": "27.91"},
    {"name": "Cloak of Defiance", "multiplier": "27.09"},
    {"name": "Skin of the Lords", "multiplier": "26.52"},
    {"name": "Zerphi's Heart", "multiplier": "26.52"},
    {"name": "Svalinn", "multiplier": "26.3"},
    {"name": "Taste of Hate", "multiplier": "25.54"},
    {"name": "Inspired Learning", "multiplier": "25.54"},
    {"name": "Replica Frostbreath", "multiplier": "25.54"},
    {"name": "The Covenant", "multiplier": "24.79"},
    {"name": "Anathema", "multiplier": "24.79"},
    {"name": "Replica Covenant", "multiplier": "24.79"},
    {"name": "Winds of Change", "multiplier": "23.37"},
    {"name": "Death Rush", "multiplier": "22.69"},
    {"name": "Emperor's Vigilance", "multiplier": "22.69"},
    {"name": "Mahuxotl's Machination", "multiplier": "22.69"},
    {"name": "The Pariah", "multiplier": "22.03"},
    {"name": "Abhorrent Interrogation", "multiplier": "22.03"},
    {"name": "The Tempest's Liberation", "multiplier": "22.03"},
    {"name": "Perfidy", "multiplier": "21.92"},
    {"name": "Ravenous Passion", "multiplier": "21.39"},
    {"name": "Altered Distant Memory", "multiplier": "21.28"},
    {"name": "Augmented Distant Memory", "multiplier": "21.28"},
    {"name": "Twisted Distant Memory", "multiplier": "21.28"},
    {"name": "Rewritten Distant Memory", "multiplier": "21.28"},
    {"name": "Cortex", "multiplier": "21.28"},
    {"name": "Hand of the Fervent", "multiplier": "20.76"},
    {"name": "Impresence", "multiplier": "20.66"},
    {"name": "Assailum", "multiplier": "20.66"},
    {"name": "Tecrod's Gaze", "multiplier": "20.66"},
    {"name": "Ulaman's Gaze", "multiplier": "20.66"},
    {"name": "Kurgal's Gaze", "multiplier": "20.66"},
    {"name": "Amanamu's Gaze", "multiplier": "20.66"},
    {"name": "Mark of the Elder", "multiplier": "19.48"},
    {"name": "Mark of the Shaper", "multiplier": "19.48"},
    {"name": "Polaric Devastation", "multiplier": "19.48"},
    {"name": "Replica Soul Strike", "multiplier": "19"},
    {"name": "Replica Midnight Bargain", "multiplier": "19"},
    {"name": "Brain Rattler", "multiplier": "18.91"},
    {"name": "Razor of the Seventh Sun", "multiplier": "18.91"},
    {"name": "Snakepit", "multiplier": "18.91"},
    {"name": "The Scourge", "multiplier": "18.91"},
    {"name": "Memory Vault", "multiplier": "18.91"},
    {"name": "Grelwood Shank", "multiplier": "18.91"},
    {"name": "Beltimber Blade", "multiplier": "18.91"},
    {"name": "Vulconus", "multiplier": "18.91"},
    {"name": "Augyre", "multiplier": "18.91"},
    {"name": "Gloomfang", "multiplier": "18.91"},
    {"name": "The Twilight Temple", "multiplier": "18.36"},
    {"name": "The Gull", "multiplier": "17.91"},
    {"name": "Severed in Sleep", "multiplier": "17.91"},
    {"name": "United in Dream", "multiplier": "17.91"},
    {"name": "Blackflame", "multiplier": "17.91"},
    {"name": "Maligaro's Virtuosity", "multiplier": "17.82"},
    {"name": "Asenath's Gentle Touch", "multiplier": "17.82"},
    {"name": "Perandus Signet", "multiplier": "17.82"},
    {"name": "Hidden Potential", "multiplier": "17.82"},
    {"name": "Nebuloch", "multiplier": "17.82"},
    {"name": "Hopeshredder", "multiplier": "17.82"},
    {"name": "Shimmeron", "multiplier": "17.82"},
    {"name": "Beacon of Madness", "multiplier": "17.82"},
    {"name": "Sunblast", "multiplier": "17.39"},
    {"name": "Doon Cuebiyari", "multiplier": "17.3"},
    {"name": "Death's Door", "multiplier": "17.3"},
    {"name": "Auxium", "multiplier": "16.8"},
    {"name": "Flamesight", "multiplier": "16.8"},
    {"name": "Galesight", "multiplier": "16.8"},
    {"name": "Thundersight", "multiplier": "16.8"},
    {"name": "The Ivory Tower", "multiplier": "16.8"},
    {"name": "Leash of Oblation", "multiplier": "16.8"},
    {"name": "Mistwall", "multiplier": "16.8"},
    {"name": "Maw of Mischief", "multiplier": "16.8"},
    {"name": "The Burden of Truth", "multiplier": "16.8"},
    {"name": "The Apostate", "multiplier": "16.39"},
    {"name": "Shadowstitch", "multiplier": "16.31"},
    {"name": "Hegemony's Era", "multiplier": "15.84"},
    {"name": "Replica Restless Ward", "multiplier": "15.84"},
    {"name": "Lioneye's Remorse", "multiplier": "15.37"},
    {"name": "Incandescent Heart", "multiplier": "15.37"},
    {"name": "Rumi's Concoction", "multiplier": "15.37"},
    {"name": "The Hungry Loop", "multiplier": "15.37"},
    {"name": "Chains of Command", "multiplier": "15.37"},
    {"name": "Black Zenith", "multiplier": "15.37"},
    {"name": "Crown of Eyes", "multiplier": "14.93"},
    {"name": "Ylfeban's Trickery", "multiplier": "14.93"},
    {"name": "Voidwalker", "multiplier": "14.93"},
    {"name": "Bubonic Trail", "multiplier": "14.93"},
    {"name": "Craiceann's Pincers", "multiplier": "14.93"},
    {"name": "Usurper's Penance", "multiplier": "14.93"},
    {"name": "Replica Voidwalker", "multiplier": "14.93"},
    {"name": "Vorana's March", "multiplier": "14.93"},
    {"name": "Kaom's Spirit", "multiplier": "14.93"},
    {"name": "The Shattered Divinity", "multiplier": "14.56"},
    {"name": "Mon'tregul's Grasp", "multiplier": "14.49"},
    {"name": "Pledge of Hands", "multiplier": "14.49"},
    {"name": "Kaom's Roots", "multiplier": "14.49"},
    {"name": "Voll's Vision", "multiplier": "14.49"},
    {"name": "Malachai's Vision", "multiplier": "14.49"},
    {"name": "Cospri's Will", "multiplier": "14.49"},
    {"name": "Tinkerskin", "multiplier": "14.49"},
    {"name": "Hand of Thought and Motion", "multiplier": "14.49"},
    {"name": "The Infinite Pursuit", "multiplier": "14.49"},
    {"name": "The Unshattered Will", "multiplier": "14.49"},
    {"name": "Invictus Solaris", "multiplier": "14.49"},
    {"name": "Cyclopean Coil", "multiplier": "14.49"},
    {"name": "Blasphemer's Grasp", "multiplier": "14.49"},
    {"name": "The Grey Spire", "multiplier": "14.49"},
    {"name": "Bitterbind Point", "multiplier": "14.49"},
    {"name": "Nebulis", "multiplier": "14.49"},
    {"name": "Glorious Vanity", "multiplier": "14.49"},
    {"name": "Lethal Pride", "multiplier": "14.49"},
    {"name": "Militant Faith", "multiplier": "14.49"},
    {"name": "Elegant Hubris", "multiplier": "14.49"},
    {"name": "Atziri's Rule", "multiplier": "14.49"},
    {"name": "Cadigan's Crown", "multiplier": "14.49"},
    {"name": "The Taming", "multiplier": "14.14"},
    {"name": "Circle of Ambition", "multiplier": "14.14"},
    {"name": "The Bringer of Rain", "multiplier": "14.07"},
    {"name": "Replica Oro's Sacrifice", "multiplier": "14.07"},
    {"name": "Dawnbreaker", "multiplier": "14.07"},
    {"name": "Dreamfeather", "multiplier": "13.66"},
    {"name": "Repentance", "multiplier": "13.66"},
    {"name": "Shaper's Touch", "multiplier": "13.66"},
    {"name": "The Enmity Divine", "multiplier": "13.66"},
    {"name": "Vix Lunaris", "multiplier": "13.66"},
    {"name": "Voidfletcher", "multiplier": "13.66"},
    {"name": "Hands of the High Templar", "multiplier": "13.66"},
    {"name": "Font of Thunder", "multiplier": "13.66"},
    {"name": "Replica Dreamfeather", "multiplier": "13.66"},
    {"name": "The Goddess Scorned", "multiplier": "13.33"},
    {"name": "Rime Gaze", "multiplier": "13.26"},
    {"name": "Infernal Mantle", "multiplier": "13.26"},
    {"name": "Ming's Heart", "multiplier": "13.26"},
    {"name": "Jack, the Axe", "multiplier": "13.26"},
    {"name": "Doomsower", "multiplier": "13.26"},
    {"name": "Scold's Bridle", "multiplier": "13.26"},
    {"name": "The Formless Flame", "multiplier": "13.26"},
    {"name": "The Snowblind Grace", "multiplier": "13.26"},
    {"name": "Saqawal's Nest", "multiplier": "13.26"},
    {"name": "Fenumus' Shroud", "multiplier": "13.26"},
    {"name": "Hale Negator", "multiplier": "13.26"},
    {"name": "Echoes of Creation", "multiplier": "13.26"},
    {"name": "Bottled Faith", "multiplier": "12.94"},
    {"name": "Replica Rumi's Concoction", "multiplier": "12.94"},
    {"name": "Olroth's Resolve", "multiplier": "12.94"},
    {"name": "Taryn's Shiver", "multiplier": "12.88"},
    {"name": "Alpha's Howl", "multiplier": "12.88"},
    {"name": "Rebuke of the Vaal", "multiplier": "12.88"},
    {"name": "Hezmana's Bloodlust", "multiplier": "12.88"},
    {"name": "Reach of the Council", "multiplier": "12.88"},
    {"name": "Uul-Netol's Kiss", "multiplier": "12.88"},
    {"name": "The Anticipation", "multiplier": "12.88"},
    {"name": "Replica Alpha's Howl", "multiplier": "12.88"},
    {"name": "Daresso's Defiance", "multiplier": "12.5"},
    {"name": "Atziri's Acuity", "multiplier": "12.5"},
    {"name": "Fenumus' Spinnerets", "multiplier": "12.5"},
    {"name": "Crown of the Inward Eye", "multiplier": "12.5"},
    {"name": "Astramentis", "multiplier": "12.2"},
    {"name": "Presence of Chayula", "multiplier": "12.2"},
    {"name": "Aul's Uprising", "multiplier": "12.2"},
    {"name": "Solstice Vigil", "multiplier": "12.2"},
    {"name": "Leadership's Price", "multiplier": "12.2"},
    {"name": "Crystallised Omniscience", "multiplier": "12.2"},
    {"name": "Ashes of the Stars", "multiplier": "12.2"},
    {"name": "Stormfire", "multiplier": "12.17"},
    {"name": "The Searing Touch", "multiplier": "12.14"},
    {"name": "Carcass Jack", "multiplier": "12.14"},
    {"name": "Death's Oath", "multiplier": "12.14"},
    {"name": "The Vertex", "multiplier": "12.14"},
    {"name": "Tulborn", "multiplier": "12.14"},
    {"name": "Esh's Mirror", "multiplier": "12.14"},
    {"name": "Yriel's Fostering", "multiplier": "12.14"},
    {"name": "The Rippling Thoughts", "multiplier": "12.14"},
    {"name": "Perepiteia", "multiplier": "12.14"},
    {"name": "Fractal Thoughts", "multiplier": "12.14"},
    {"name": "Cold Iron Point", "multiplier": "12.14"},
    {"name": "Law of the Wilds", "multiplier": "12.14"},
    {"name": "Blunderbore", "multiplier": "12.14"},
    {"name": "Replica Wings of Entropy", "multiplier": "12.14"},
    {"name": "Glimpse of Chaos", "multiplier": "12.14"},
    {"name": "Dawnstrider", "multiplier": "12.14"},
    {"name": "Rigwald's Savagery", "multiplier": "11.82"},
    {"name": "Rigwald's Command", "multiplier": "11.82"},
    {"name": "Slivertongue", "multiplier": "11.82"},
    {"name": "Obscurantis", "multiplier": "11.82"},
    {"name": "Inya's Epiphany", "multiplier": "11.78"},
    {"name": "Replica Inya's Epiphany", "multiplier": "11.78"},
    {"name": "The Living Blade", "multiplier": "11.78"},
    {"name": "Abyssus", "multiplier": "11.44"},
    {"name": "Lightning Coil", "multiplier": "11.44"},
    {"name": "Null's Inclination", "multiplier": "11.44"},
    {"name": "Dyadian Dawn", "multiplier": "11.44"},
    {"name": "Rigwald's Curse", "multiplier": "11.44"},
    {"name": "Grip of the Council", "multiplier": "11.44"},
    {"name": "Saqawal's Flock", "multiplier": "11.44"},
    {"name": "The Iron Mass", "multiplier": "11.44"},
    {"name": "The Hidden Blade", "multiplier": "11.44"},
    {"name": "The Fulcrum", "multiplier": "11.44"},
    {"name": "Replica Grip of the Council", "multiplier": "11.44"},
    {"name": "Cameria's Avarice", "multiplier": "11.44"},
    {"name": "The Battle Within", "multiplier": "11.44"},
    {"name": "Contract: The Twins", "multiplier": "11.29"},
    {"name": "The Second Sacrament", "multiplier": "11.29"},
    {"name": "The Original Scripture", "multiplier": "11.29"},
    {"name": "Algor Mortis", "multiplier": "11.14"},
    {"name": "Saffell's Frame", "multiplier": "11.11"},
    {"name": "Queen of the Forest", "multiplier": "11.11"},
    {"name": "Saqawal's Talons", "multiplier": "11.11"},
    {"name": "Breathstealer", "multiplier": "11.11"},
    {"name": "Expedition's End", "multiplier": "11.11"},
    {"name": "Wilma's Requital", "multiplier": "11.11"},
    {"name": "Gamblesprint", "multiplier": "11.11"},
    {"name": "First Piece of Focus", "multiplier": "10.96"},
    {"name": "Second Piece of Focus", "multiplier": "10.96"},
    {"name": "Third Piece of Focus", "multiplier": "10.96"},
    {"name": "Fourth Piece of Focus", "multiplier": "10.96"},
    {"name": "First Piece of Storms", "multiplier": "10.96"},
    {"name": "Second Piece of Storms", "multiplier": "10.96"},
    {"name": "Third Piece of Storms", "multiplier": "10.96"},
    {"name": "Contract: Death to Darnaw", "multiplier": "10.96"},
    {"name": "The First Crest", "multiplier": "10.96"},
    {"name": "Unyielding Flame", "multiplier": "10.82"},
    {"name": "Xoph's Inception", "multiplier": "10.78"},
    {"name": "Craiceann's Chitin", "multiplier": "10.78"},
    {"name": "Mask of the Stitched Demon", "multiplier": "10.78"},
    {"name": "Storm's Gift", "multiplier": "10.78"},
    {"name": "Mask of the Tribunal", "multiplier": "10.78"},
    {"name": "Contract: Jamanra's Rest", "multiplier": "10.64"},
    {"name": "Contract: Heart of Glory", "multiplier": "10.64"},
    {"name": "The Magnate", "multiplier": "10.52"},
    {"name": "Lioneye's Fall", "multiplier": "10.52"},
    {"name": "Intuitive Leap", "multiplier": "10.52"},
    {"name": "Dead Reckoning", "multiplier": "10.52"},
    {"name": "Emperor's Cunning", "multiplier": "10.52"},
    {"name": "Emperor's Wit", "multiplier": "10.52"},
    {"name": "Emperor's Might", "multiplier": "10.52"},
    {"name": "Grand Spectrum", "multiplier": "10.52"},
    {"name": "Unending Hunger", "multiplier": "10.52"},
    {"name": "The Red Dream", "multiplier": "10.52"},
    {"name": "The Green Dream", "multiplier": "10.52"},
    {"name": "The Blue Dream", "multiplier": "10.52"},
    {"name": "Pure Talent", "multiplier": "10.52"},
    {"name": "Might of the Meek", "multiplier": "10.52"},
    {"name": "Transcendent Flesh", "multiplier": "10.52"},
    {"name": "Transcendent Spirit", "multiplier": "10.52"},
    {"name": "Transcendent Mind", "multiplier": "10.52"},
    {"name": "Unnatural Instinct", "multiplier": "10.52"},
    {"name": "The Torrent's Reclamation", "multiplier": "10.52"},
    {"name": "Replica Soul Tether", "multiplier": "10.52"},
    {"name": "Replica Ungil's Gauche", "multiplier": "10.52"},
    {"name": "Replica Primordial Might", "multiplier": "10.52"},
    {"name": "Melding of the Flesh", "multiplier": "10.52"},
    {"name": "Dissolution of the Flesh", "multiplier": "10.52"},
    {"name": "Immutable Force", "multiplier": "10.52"},
    {"name": "Stormshroud", "multiplier": "10.52"},
    {"name": "Firesong", "multiplier": "10.52"},
    {"name": "Witchbane", "multiplier": "10.52"},
    {"name": "The Balance of Terror", "multiplier": "10.52"},
    {"name": "Ancestral Vision", "multiplier": "10.52"},
    {"name": "Bloodnotch", "multiplier": "10.52"},
    {"name": "Warrior's Tale", "multiplier": "10.52"},
    {"name": "The Adorned", "multiplier": "10.52"},
    {"name": "Replica Badge of the Brotherhood", "multiplier": "10.52"},
    {"name": "Perseverance", "multiplier": "10.5"},
    {"name": "The Black Cane", "multiplier": "10.5"},
    {"name": "Willowgift", "multiplier": "10.5"},
    {"name": "Eye of Malice", "multiplier": "10.5"},
    {"name": "Ancient Skull", "multiplier": "10.5"},
    {"name": "Mind of the Council", "multiplier": "10.47"},
    {"name": "The Crimson Storm", "multiplier": "10.47"},
    {"name": "Kaom's Binding", "multiplier": "10.47"},
    {"name": "Contract: Breaking the Unbreakable", "multiplier": "10.33"},
    {"name": "Contract: The Slaver King", "multiplier": "10.33"},
    {"name": "The Angel of Vengeance", "multiplier": "10.33"},
    {"name": "The Narcissist", "multiplier": "10.33"},
    {"name": "The Epiphany", "multiplier": "10.33"},
    {"name": "The Depraved", "multiplier": "10.33"},
    {"name": "The Twisted Trinity", "multiplier": "10.33"},
    {"name": "The Raging Inferno", "multiplier": "10.33"},
    {"name": "The Unbridled Tempest", "multiplier": "10.33"},
    {"name": "Insomnia", "multiplier": "10.33"},
    {"name": "The Chains of Castigation", "multiplier": "10.33"},
    {"name": "The Power and the Promise", "multiplier": "10.33"},
    {"name": "The Rat Cage", "multiplier": "10.16"},
    {"name": "Craiceann's Carapace", "multiplier": "10.16"},
    {"name": "Fate of the Vaal", "multiplier": "10.16"},
    {"name": "Replica Dragonfang's Flight", "multiplier": "10.16"},
    {"name": "Vessel of Vinktar", "multiplier": "9.92"},
    {"name": "Dying Sun", "multiplier": "9.92"},
    {"name": "Lioneye's Vision", "multiplier": "9.9"},
    {"name": "Brinerot Mark", "multiplier": "9.87"},
    {"name": "Redblade Band", "multiplier": "9.87"},
    {"name": "Mutewind Seal", "multiplier": "9.87"},
    {"name": "Ngamahu's Flame", "multiplier": "9.87"},
    {"name": "Omeyocan", "multiplier": "9.87"},
    {"name": "Tavukai", "multiplier": "9.87"},
    {"name": "Replica Three-step Assault", "multiplier": "9.87"},
    {"name": "Temptation Step", "multiplier": "9.87"},
    {"name": "Great Old One's Tentacles", "multiplier": "9.61"},
    {"name": "Ceaseless Feast", "multiplier": "9.61"},
    {"name": "Inextricable Fate", "multiplier": "9.61"},
    {"name": "Chitus' Apex", "multiplier": "9.58"},
    {"name": "Daresso's Courage", "multiplier": "9.58"},
    {"name": "Craiceann's Tracks", "multiplier": "9.58"},
    {"name": "Fenumus' Toxins", "multiplier": "9.58"},
    {"name": "Wraeclast Pantheon", "multiplier": "9.45"},
    {"name": "The Perandus Manor", "multiplier": "9.45"},
    {"name": "Eye of Innocence", "multiplier": "9.45"},
    {"name": "First Piece of Brutality", "multiplier": "9.45"},
    {"name": "Second Piece of Brutality", "multiplier": "9.45"},
    {"name": "Third Piece of Brutality", "multiplier": "9.45"},
    {"name": "First Piece of Directions", "multiplier": "9.45"},
    {"name": "Second Piece of Directions", "multiplier": "9.45"},
    {"name": "Third Piece of Directions", "multiplier": "9.45"},
    {"name": "Leper's Alms", "multiplier": "9.45"},
    {"name": "Atziri's Foible", "multiplier": "9.35"},
    {"name": "Ahkeli's Meadow", "multiplier": "9.35"},
    {"name": "Replica Emberwake", "multiplier": "9.35"},
    {"name": "Dyadus", "multiplier": "9.33"},
    {"name": "Atziri's Step", "multiplier": "9.33"},
    {"name": "Cherrubim's Maleficence", "multiplier": "9.33"},
    {"name": "Eber's Unification", "multiplier": "9.33"},
    {"name": "Medved's Challenge", "multiplier": "9.33"},
    {"name": "Rainbowstride", "multiplier": "9.3"},
    {"name": "Apep's Rage", "multiplier": "9.3"},
    {"name": "Lightpoacher", "multiplier": "9.3"},
    {"name": "Forbidden Shako", "multiplier": "9.3"},
    {"name": "Replica Infractem", "multiplier": "9.3"},
    {"name": "The Putrid Cloister", "multiplier": "9.18"},
    {"name": "The Beast Fur Shawl", "multiplier": "9.06"},
    {"name": "Touch of Anguish", "multiplier": "9.06"},
    {"name": "Ahn's Contempt", "multiplier": "9.06"},
    {"name": "Ahn's Might", "multiplier": "9.06"},
    {"name": "Gorgon's Gaze", "multiplier": "9.03"},
    {"name": "Profane Proxy", "multiplier": "9.03"},
    {"name": "Witchhunter's Judgment", "multiplier": "9.03"},
    {"name": "Akoya's Gaze", "multiplier": "9.03"},
    {"name": "Ynda's Stand", "multiplier": "9.03"},
    {"name": "Grasping Nightshade", "multiplier": "9.03"},
    {"name": "Death and Taxes", "multiplier": "8.91"},
    {"name": "The Ephemeral Bond", "multiplier": "8.91"},
    {"name": "The Gilded Chalice", "multiplier": "8.91"},
    {"name": "The Broken Censer", "multiplier": "8.91"},
    {"name": "Kongor's Undying Rage", "multiplier": "8.79"},
    {"name": "Ahn's Heritage", "multiplier": "8.79"},
    {"name": "Saqawal's Winds", "multiplier": "8.77"},
    {"name": "Legacy of Fury", "multiplier": "8.77"},
    {"name": "Devoto's Devotion", "multiplier": "8.65"},
    {"name": "Olmec's Sanctum", "multiplier": "8.65"},
    {"name": "Bloodgrip", "multiplier": "8.65"},
    {"name": "Pillars of Arun", "multiplier": "8.65"},
    {"name": "Agnerod East", "multiplier": "8.54"},
    {"name": "Agnerod North", "multiplier": "8.54"},
    {"name": "Agnerod South", "multiplier": "8.54"},
    {"name": "Agnerod West", "multiplier": "8.54"},
    {"name": "Breath of the Council", "multiplier": "8.54"},
    {"name": "The Poised Prism", "multiplier": "8.54"},
    {"name": "Andvarius", "multiplier": "8.51"},
    {"name": "Rain of Splinters", "multiplier": "8.51"},
    {"name": "Star of Wraeclast", "multiplier": "8.51"},
    {"name": "Fenumus' Weave", "multiplier": "8.51"},
    {"name": "Replica Victario's Charity", "multiplier": "8.51"},
    {"name": "Replica Heartbreaker", "multiplier": "8.51"},
    {"name": "Replica Lavianga's Spirit", "multiplier": "8.51"},
    {"name": "Worldcarver", "multiplier": "8.4"},
    {"name": "Painseeker", "multiplier": "8.4"},
    {"name": "The Poet's Pen", "multiplier": "8.31"},
    {"name": "Putembo's Mountain", "multiplier": "8.31"},
    {"name": "Rise of the Phoenix", "multiplier": "8.29"},
    {"name": "Darkray Vectors", "multiplier": "8.29"},
    {"name": "Vis Mortis", "multiplier": "8.29"},
    {"name": "Ventor's Gamble", "multiplier": "8.29"},
    {"name": "Malachai's Loop", "multiplier": "8.29"},
    {"name": "Cane of Kulemak", "multiplier": "8.26"},
    {"name": "The Scales of Justice", "multiplier": "8.26"},
    {"name": "Bound Fate", "multiplier": "8.26"},
    {"name": "Oba's Cursed Trove", "multiplier": "8.16"},
    {"name": "Death's Hand", "multiplier": "8.16"},
    {"name": "Caer Blaidd, Wolfpack's Den", "multiplier": "8.16"},
    {"name": "The Beachhead", "multiplier": "8.16"},
    {"name": "Doryani's Catalyst", "multiplier": "8.05"},
    {"name": "Soul Strike", "multiplier": "8.05"},
    {"name": "Geofri's Sanctuary", "multiplier": "8.05"},
    {"name": "Hyrri's Truth", "multiplier": "8.05"},
    {"name": "Rashkaldor's Patience", "multiplier": "8.02"},
    {"name": "Witchfire Brew", "multiplier": "8.02"},
    {"name": "Soul Tether", "multiplier": "8.02"},
    {"name": "Maw of Conquest", "multiplier": "8.02"},
    {"name": "The Jinxed Juju", "multiplier": "8.02"},
    {"name": "Kaom's Command", "multiplier": "8.02"},
    {"name": "Poorjoy's Asylum", "multiplier": "7.92"},
    {"name": "BlackGuardz", "multiplier": "7.92"},
    {"name": "Cagan's Map", "multiplier": "7.92"},
    {"name": "Whakawairua Tuahu", "multiplier": "7.92"},
    {"name": "The Restless Ward", "multiplier": "7.92"},
    {"name": "Hallowed Ground", "multiplier": "7.92"},
    {"name": "Replica Siegebreaker", "multiplier": "7.83"},
    {"name": "Speaker's Wreath", "multiplier": "7.81"},
    {"name": "The Stampede", "multiplier": "7.81"},
    {"name": "Actum", "multiplier": "7.81"},
    {"name": "Cerberus Limb", "multiplier": "7.79"},
    {"name": "Replica Kalisa's Grace", "multiplier": "7.79"},
    {"name": "Replica Innsbury Edge", "multiplier": "7.79"},
    {"name": "Jaws of Agony", "multiplier": "7.69"},
    {"name": "Pitch Darkness", "multiplier": "7.69"},
    {"name": "Rive", "multiplier": "7.69"},
    {"name": "Mercenary's Lot", "multiplier": "7.69"},
    {"name": "The Oppressor", "multiplier": "7.69"},
    {"name": "Hyaon's Fury", "multiplier": "7.59"},
    {"name": "Singularity", "multiplier": "7.59"},
    {"name": "Apep's Slumber", "multiplier": "7.59"},
    {"name": "Belly of the Beast", "multiplier": "7.56"},
    {"name": "Redblade Tramplers", "multiplier": "7.56"},
    {"name": "Acton's Nightmare", "multiplier": "7.46"},
    {"name": "Convent of the Twins' Flame", "multiplier": "7.46"},
    {"name": "Hall of Grandmasters", "multiplier": "7.46"},
    {"name": "Veruso's Battering Rams", "multiplier": "7.46"},
    {"name": "Asenath's Mark", "multiplier": "7.38"},
    {"name": "Uzaza's Valley", "multiplier": "7.38"},
    {"name": "Scorpion's Call", "multiplier": "7.36"},
    {"name": "Tawhoa's Felling", "multiplier": "7.36"},
    {"name": "Soulthirst", "multiplier": "7.34"},
    {"name": "The Tempest's Binding", "multiplier": "7.34"},
    {"name": "Slavedriver's Hand", "multiplier": "7.34"},
    {"name": "Vivinsect", "multiplier": "7.34"},
    {"name": "Replica Malachai's Artifice", "multiplier": "7.34"},
    {"name": "Replica Voideye", "multiplier": "7.34"},
    {"name": "Rotblood Promise", "multiplier": "7.34"},
    {"name": "Triumvirate Authority", "multiplier": "7.34"},
    {"name": "Vaults of Atziri", "multiplier": "7.25"},
    {"name": "Mao Kun", "multiplier": "7.25"},
    {"name": "Izaro's Dilemma", "multiplier": "7.25"},
    {"name": "Nuro's Harp", "multiplier": "7.25"},
    {"name": "The Torturer", "multiplier": "7.25"},
    {"name": "The Hateful Accuser", "multiplier": "7.25"},
    {"name": "The Selfish Shepherd", "multiplier": "7.25"},
    {"name": "The Queller of Minds", "multiplier": "7.25"},
    {"name": "Xoph's Blood", "multiplier": "7.16"},
    {"name": "The Pandemonius", "multiplier": "7.16"},
    {"name": "Choir of the Storm", "multiplier": "7.16"},
    {"name": "Replica Hyrri's Truth", "multiplier": "7.16"},
    {"name": "Starkonja's Head", "multiplier": "7.15"},
    {"name": "Romira's Banquet", "multiplier": "7.15"},
    {"name": "The Writhing Jar", "multiplier": "7.15"},
    {"name": "Scaeva", "multiplier": "7.15"},
    {"name": "Cane of Unravelling", "multiplier": "7.15"},
    {"name": "Soulwrest", "multiplier": "7.15"},
    {"name": "Cowl of the Thermophile", "multiplier": "7.15"},
    {"name": "Cowl of the Cryophile", "multiplier": "7.15"},
    {"name": "The Blood Dance", "multiplier": "7.13"},
    {"name": "Hinekora's Sight", "multiplier": "7.13"},
    {"name": "Replica Hinekora's Sight", "multiplier": "7.13"},
    {"name": "Maelström of Chaos", "multiplier": "7.03"},
    {"name": "Robbie's Rotten Mace", "multiplier": "7.03"},
    {"name": "Carl's Crusher", "multiplier": "7.03"},
    {"name": "Oro's Sacrifice", "multiplier": "7.03"},
    {"name": "Surgebinders", "multiplier": "7.03"},
    {"name": "Spiritskin", "multiplier": "7.03"},
    {"name": "Waycarver", "multiplier": "7.03"},
    {"name": "The Infested", "multiplier": "7.03"},
    {"name": "Piscator's Vigil", "multiplier": "6.94"},
    {"name": "The Dancing Dervish", "multiplier": "6.94"},
    {"name": "Hiltless", "multiplier": "6.94"},
    {"name": "Dendrobate", "multiplier": "6.94"},
    {"name": "Cowl of the Ceraunophile", "multiplier": "6.94"},
    {"name": "Haemophilia", "multiplier": "6.92"},
    {"name": "Volkuur's Guidance", "multiplier": "6.92"},
    {"name": "Replica Volkuur's Guidance", "multiplier": "6.92"},
    {"name": "Callinellus Malleus", "multiplier": "6.83"},
    {"name": "The Goddess Unleashed", "multiplier": "6.83"},
    {"name": "Allure", "multiplier": "6.83"},
    {"name": "Debeon's Dirge", "multiplier": "6.83"},
    {"name": "White Wind", "multiplier": "6.83"},
    {"name": "Kaom's Primacy", "multiplier": "6.74"},
    {"name": "Snakebite", "multiplier": "6.74"},
    {"name": "Ichimonji", "multiplier": "6.74"},
    {"name": "Mask of the Spirit Drinker", "multiplier": "6.74"},
    {"name": "The Ghastly Theatre", "multiplier": "6.74"},
    {"name": "The Gluttonous Tide", "multiplier": "6.74"},
    {"name": "Mutewind Pennant", "multiplier": "6.72"},
    {"name": "Mutewind Whispersteps", "multiplier": "6.72"},
    {"name": "Tainted Pact", "multiplier": "6.72"},
    {"name": "Null and Void", "multiplier": "6.54"},
    {"name": "Kiloava's Bluster", "multiplier": "6.54"},
    {"name": "The Supreme Truth", "multiplier": "6.52"},
    {"name": "Nycta's Lantern", "multiplier": "6.52"},
    {"name": "Tremor Rod", "multiplier": "6.52"},
    {"name": "Brinerot Whalers", "multiplier": "6.52"},
    {"name": "Allelopathy", "multiplier": "6.52"},
    {"name": "Replica Allelopathy", "multiplier": "6.52"},
    {"name": "Mark of the Doubting Knight", "multiplier": "6.44"},
    {"name": "The Rack", "multiplier": "6.44"},
    {"name": "Skin of the Loyal", "multiplier": "6.37"},
    {"name": "Replica Atziri's Foible", "multiplier": "6.37"},
    {"name": "Greed's Embrace", "multiplier": "6.35"},
    {"name": "Story of the Vaal", "multiplier": "6.35"},
    {"name": "Storm Secret", "multiplier": "6.35"},
    {"name": "Ahuana's Bite", "multiplier": "6.35"},
    {"name": "Marylene's Fallacy", "multiplier": "6.33"},
    {"name": "Call of the Brotherhood", "multiplier": "6.33"},
    {"name": "Emberwake", "multiplier": "6.33"},
    {"name": "Trypanon", "multiplier": "6.33"},
    {"name": "Voice of the Storm", "multiplier": "6.33"},
    {"name": "Fury Valve", "multiplier": "6.33"},
    {"name": "Mother's Embrace", "multiplier": "6.33"},
    {"name": "Blood Price", "multiplier": "6.33"},
    {"name": "Thousand Teeth Temu", "multiplier": "6.25"},
    {"name": "The Broken Crown", "multiplier": "6.25"},
    {"name": "The Retch", "multiplier": "6.18"},
    {"name": "Voidbringer", "multiplier": "6.17"},
    {"name": "Dance of the Offered", "multiplier": "6.17"},
    {"name": "Admiral's Arrogance", "multiplier": "6.15"},
    {"name": "Sin Trek", "multiplier": "6.07"},
    {"name": "Chin Sol", "multiplier": "6.07"},
    {"name": "Wings of Entropy", "multiplier": "6.07"},
    {"name": "Santoni's Faith", "multiplier": "6.07"},
    {"name": "Fairgraves' Bearing", "multiplier": "6.07"},
    {"name": "Borrowed Power", "multiplier": "6.07"},
    {"name": "Bloodletter", "multiplier": "6.07"},
    {"name": "Rumblemarch", "multiplier": "6.07"},
    {"name": "Sinvicta's Mettle", "multiplier": "6.07"},
    {"name": "The Basilisk", "multiplier": "6.07"},
    {"name": "Emperor's Mastery", "multiplier": "6"},
    {"name": "The Anima Stone", "multiplier": "6"},
    {"name": "Voices", "multiplier": "6"},
    {"name": "Sublime Vision", "multiplier": "6"},
    {"name": "Voidhome", "multiplier": "5.99"},
    {"name": "Pyroshock Clasp", "multiplier": "5.99"},
    {"name": "Circle of Nostalgia", "multiplier": "5.97"},
    {"name": "Chernobog's Pillar", "multiplier": "5.89"},
    {"name": "Kingsguard", "multiplier": "5.89"},
    {"name": "Kondo's Pride", "multiplier": "5.89"},
    {"name": "Geofri's Crest", "multiplier": "5.81"},
    {"name": "Bronn's Lithe", "multiplier": "5.81"},
    {"name": "The Consuming Dark", "multiplier": "5.81"},
    {"name": "The Coming Calamity", "multiplier": "5.81"},
    {"name": "Serle's Masterwork", "multiplier": "5.81"},
    {"name": "Command of the Pit", "multiplier": "5.8"},
    {"name": "Replica Harvest", "multiplier": "5.8"},
    {"name": "The Coward's Trial", "multiplier": "5.72"},
    {"name": "Untainted Paradise", "multiplier": "5.72"},
    {"name": "Cameria's Maul", "multiplier": "5.72"},
    {"name": "Malicious Intent", "multiplier": "5.72"},
    {"name": "Balefire", "multiplier": "5.72"},
    {"name": "The Wasp Nest", "multiplier": "5.72"},
    {"name": "Taproot", "multiplier": "5.72"},
    {"name": "The Druggery", "multiplier": "5.72"},
    {"name": "Goblinedge", "multiplier": "5.72"},
    {"name": "The Benefactor", "multiplier": "5.72"},
    {"name": "The Redblade", "multiplier": "5.72"},
    {"name": "Victario's Influence", "multiplier": "5.64"},
    {"name": "Crown of the Pale King", "multiplier": "5.64"},
    {"name": "Oskarm", "multiplier": "5.64"},
    {"name": "Aurseize", "multiplier": "5.63"},
    {"name": "Tombfist", "multiplier": "5.63"},
    {"name": "Vixen's Entrapment", "multiplier": "5.63"},
    {"name": "Moonsorrow", "multiplier": "5.55"},
    {"name": "Obliteration", "multiplier": "5.55"},
    {"name": "Farsight", "multiplier": "5.55"},
    {"name": "Replica Soul Taker", "multiplier": "5.55"},
    {"name": "The Dancing Duo", "multiplier": "5.55"},
    {"name": "The Fledgling", "multiplier": "5.48"},
    {"name": "Voll's Protector", "multiplier": "5.46"},
    {"name": "Meginord's Vise", "multiplier": "5.46"},
    {"name": "Lion's Roar", "multiplier": "5.46"},
    {"name": "Redblade Banner", "multiplier": "5.46"},
    {"name": "Xoph's Heart", "multiplier": "5.46"},
    {"name": "The Halcyon", "multiplier": "5.46"},
    {"name": "Replica Earendel's Embrace", "multiplier": "5.46"},
    {"name": "Leviathan Ivory", "multiplier": "5.39"},
    {"name": "Rory's Revengance", "multiplier": "5.39"},
    {"name": "Mark2's Mastery", "multiplier": "5.39"},
    {"name": "Gang's Momentum", "multiplier": "5.39"},
    {"name": "Femurs of the Saints", "multiplier": "5.39"},
    {"name": "Lawbreaker", "multiplier": "5.39"},
    {"name": "March of the Legion", "multiplier": "5.39"},
    {"name": "Sign of the Sin Eater", "multiplier": "5.39"},
    {"name": "Rotting Legion", "multiplier": "5.39"},
    {"name": "The Hollow-Eyed Skull", "multiplier": "5.39"},
    {"name": "The Ancient Angler", "multiplier": "5.39"},
    {"name": "The Burden of Shadows", "multiplier": "5.39"},
    {"name": "Blood of the Karui", "multiplier": "5.32"},
    {"name": "Lavianga's Spirit", "multiplier": "5.32"},
    {"name": "Warped Timepiece", "multiplier": "5.32"},
    {"name": "Heartbound Loop", "multiplier": "5.32"},
    {"name": "Frostbreath", "multiplier": "5.32"},
    {"name": "Darkness Enthroned", "multiplier": "5.32"},
    {"name": "Perquil's Toe", "multiplier": "5.32"},
    {"name": "Nametaker", "multiplier": "5.32"},
    {"name": "Soul Mantle", "multiplier": "5.17"},
    {"name": "Alberon's Warpath", "multiplier": "5.17"},
    {"name": "Sire of Shards", "multiplier": "5.17"},
    {"name": "Wyrmsign", "multiplier": "5.17"},
    {"name": "Venopuncture", "multiplier": "5.17"},
    {"name": "Icefang Orbit", "multiplier": "5.17"},
    {"name": "Shattershard", "multiplier": "5.17"},
    {"name": "Steelworm", "multiplier": "5.17"},
    {"name": "Tanu Ahi", "multiplier": "5.17"},
    {"name": "Bloodsoaked Medallion", "multiplier": "5.17"},
    {"name": "Windscream", "multiplier": "5.15"},
    {"name": "Deidbell", "multiplier": "5.15"},
    {"name": "The Whispering Ice", "multiplier": "5.15"},
    {"name": "Prospero's Vault", "multiplier": "5.08"},
    {"name": "Gluttony", "multiplier": "5.01"},
    {"name": "Nightgrip", "multiplier": "5.01"},
    {"name": "Olroth's Charge", "multiplier": "5.01"},
    {"name": "Sudden Dawn", "multiplier": "5.01"},
    {"name": "Ephemeral Edge", "multiplier": "5"},
    {"name": "Death's Harp", "multiplier": "5"},
    {"name": "Bitterdream", "multiplier": "5"},
    {"name": "Replica Iron Commander", "multiplier": "5"},
    {"name": "The Hand of Phrecia", "multiplier": "5"},
    {"name": "Wildfire Phloem", "multiplier": "5"},
    {"name": "Hrimnor's Resolve", "multiplier": "4.93"},
    {"name": "Rat's Nest", "multiplier": "4.93"},
    {"name": "Maloney's Nightfall", "multiplier": "4.93"},
    {"name": "Three-step Assault", "multiplier": "4.93"},
    {"name": "The Ascetic", "multiplier": "4.93"},
    {"name": "The Highwayman", "multiplier": "4.93"},
    {"name": "Innsbury Edge", "multiplier": "4.87"},
    {"name": "The Fracturing Spinner", "multiplier": "4.85"},
    {"name": "Atziri's Mirror", "multiplier": "4.79"},
    {"name": "The Arbiter", "multiplier": "4.79"},
    {"name": "Great Old One's Ward", "multiplier": "4.73"},
    {"name": "Replica Advancing Fortress", "multiplier": "4.73"},
    {"name": "Kahuturoa's Certainty", "multiplier": "4.73"},
    {"name": "Divination Distillate", "multiplier": "4.71"},
    {"name": "Umbilicus Immortalis", "multiplier": "4.71"},
    {"name": "Xirgil's Crank", "multiplier": "4.71"},
    {"name": "Bisco's Collar", "multiplier": "4.71"},
    {"name": "Bisco's Leash", "multiplier": "4.71"},
    {"name": "Replica Lioneye's Paws", "multiplier": "4.71"},
    {"name": "Relic of the Pact", "multiplier": "4.71"},
    {"name": "Infractem", "multiplier": "4.65"},
    {"name": "Felltooth", "multiplier": "4.65"},
    {"name": "Prismatic Eclipse", "multiplier": "4.65"},
    {"name": "Empire's Grasp", "multiplier": "4.65"},
    {"name": "Disjunction", "multiplier": "4.65"},
    {"name": "Replica Forbidden Shako", "multiplier": "4.65"},
    {"name": "Geofri's Legacy", "multiplier": "4.65"},
    {"name": "Voideye", "multiplier": "4.59"},
    {"name": "Forbidden Taste", "multiplier": "4.59"},
    {"name": "Malachai's Artifice", "multiplier": "4.59"},
    {"name": "Kongming's Stratagem", "multiplier": "4.59"},
    {"name": "Essence Worm", "multiplier": "4.59"},
    {"name": "Architect's Hand", "multiplier": "4.59"},
    {"name": "The Annihilating Light", "multiplier": "4.59"},
    {"name": "Stormseeker", "multiplier": "4.59"},
    {"name": "The Geomantic Gyre", "multiplier": "4.52"},
    {"name": "Maligaro's Restraint", "multiplier": "4.46"},
    {"name": "Jorrhast's Blacksteel", "multiplier": "4.46"},
    {"name": "Natural Hierarchy", "multiplier": "4.46"},
    {"name": "Ascent From Flesh", "multiplier": "4.46"},
    {"name": "Kitava's Thirst", "multiplier": "4.46"},
    {"name": "Soulbound", "multiplier": "4.46"},
    {"name": "Doomfletch", "multiplier": "4.44"},
    {"name": "Brutus' Lead Sprinkler", "multiplier": "4.44"},
    {"name": "Terminus Est", "multiplier": "4.38"},
    {"name": "Black Sun Crest", "multiplier": "4.38"},
    {"name": "Southbound", "multiplier": "4.38"},
    {"name": "Ambu's Charge", "multiplier": "4.33"},
    {"name": "Replica Ambu's Charge", "multiplier": "4.33"},
    {"name": "Vaal Caress", "multiplier": "4.31"},
    {"name": "Cinderswallow Urn", "multiplier": "4.31"},
    {"name": "Replica Sorrow of the Divine", "multiplier": "4.31"},
    {"name": "Starlight Chalice", "multiplier": "4.31"},
    {"name": "Elixir of the Unbroken Circle", "multiplier": "4.31"},
    {"name": "Replica Witchfire Brew", "multiplier": "4.31"},
    {"name": "Heartbreaker", "multiplier": "4.26"},
    {"name": "Immortal Flesh", "multiplier": "4.26"},
    {"name": "Mantra of Flames", "multiplier": "4.26"},
    {"name": "Victario's Charity", "multiplier": "4.26"},
    {"name": "The Embalmer", "multiplier": "4.26"},
    {"name": "Zeel's Amplifier", "multiplier": "4.13"},
    {"name": "The Eternal Apple", "multiplier": "4.13"},
    {"name": "Pragmatism", "multiplier": "4.13"},
    {"name": "Demon Stitcher", "multiplier": "4.08"},
    {"name": "Eye of Chayula", "multiplier": "4.07"},
    {"name": "The Eternal Struggle", "multiplier": "4.07"},
    {"name": "Midnight Bargain", "multiplier": "3.96"},
    {"name": "Ceinture of Benevolence", "multiplier": "3.96"},
    {"name": "Dream Fragments", "multiplier": "3.95"},
    {"name": "Reverberation Rod", "multiplier": "3.95"},
    {"name": "Winterweave", "multiplier": "3.95"},
    {"name": "Doedre's Tongue", "multiplier": "3.95"},
    {"name": "Kalisa's Grace", "multiplier": "3.9"},
    {"name": "Arimagius' Honor", "multiplier": "3.9"},
    {"name": "Lightbane Raiment", "multiplier": "3.9"},
    {"name": "Doedre's Scorn", "multiplier": "3.84"},
    {"name": "Moonbender's Wing", "multiplier": "3.84"},
    {"name": "The Flawed Refuge", "multiplier": "3.84"},
    {"name": "Ungil's Harmony", "multiplier": "3.83"},
    {"name": "Brinerot Flag", "multiplier": "3.83"},
    {"name": "Ornament of the East", "multiplier": "3.78"},
    {"name": "Advancing Fortress", "multiplier": "3.78"},
    {"name": "Valako's Sign", "multiplier": "3.73"},
    {"name": "Replica Bones of Ullr", "multiplier": "3.72"},
    {"name": "The Blood Reaper", "multiplier": "3.67"},
    {"name": "Deadman's Hand", "multiplier": "3.67"},
    {"name": "Sibyl's Lament", "multiplier": "3.67"},
    {"name": "The Anvil", "multiplier": "3.67"},
    {"name": "Maligaro's Lens", "multiplier": "3.67"},
    {"name": "Mark of Submission", "multiplier": "3.67"},
    {"name": "The Signal Fire", "multiplier": "3.67"},
    {"name": "Corona Solaris", "multiplier": "3.67"},
    {"name": "The Harvest", "multiplier": "3.62"},
    {"name": "Rigwald's Charge", "multiplier": "3.56"},
    {"name": "Widowmaker", "multiplier": "3.56"},
    {"name": "Siegebreaker", "multiplier": "3.56"},
    {"name": "Tawhanuku's Timing", "multiplier": "3.56"},
    {"name": "Heatshiver", "multiplier": "3.51"},
    {"name": "Berek's Respite", "multiplier": "3.51"},
    {"name": "To Dust", "multiplier": "3.51"},
    {"name": "Fertile Mind", "multiplier": "3.51"},
    {"name": "Fluid Motion", "multiplier": "3.51"},
    {"name": "Fevered Mind", "multiplier": "3.51"},
    {"name": "Efficient Training", "multiplier": "3.51"},
    {"name": "Brute Force Solution", "multiplier": "3.51"},
    {"name": "Careful Planning", "multiplier": "3.51"},
    {"name": "Inertia", "multiplier": "3.51"},
    {"name": "Atziri's Reign", "multiplier": "3.51"},
    {"name": "Chill of Corruption", "multiplier": "3.51"},
    {"name": "Self-Flagellation", "multiplier": "3.51"},
    {"name": "Pacifism", "multiplier": "3.51"},
    {"name": "Fragility", "multiplier": "3.51"},
    {"name": "Powerlessness", "multiplier": "3.51"},
    {"name": "Energised Armour", "multiplier": "3.51"},
    {"name": "Energy From Within", "multiplier": "3.51"},
    {"name": "Healthy Mind", "multiplier": "3.51"},
    {"name": "Reckless Defence", "multiplier": "3.51"},
    {"name": "Rigwald's Crest", "multiplier": "3.51"},
    {"name": "Primordial Harmony", "multiplier": "3.51"},
    {"name": "Primordial Might", "multiplier": "3.51"},
    {"name": "Primordial Eminence", "multiplier": "3.51"},
    {"name": "The Flow Untethered", "multiplier": "3.51"},
    {"name": "The Golden Rule", "multiplier": "3.51"},
    {"name": "Soul's Wick", "multiplier": "3.51"},
    {"name": "Fortress Covenant", "multiplier": "3.51"},
    {"name": "Quickening Covenant", "multiplier": "3.51"},
    {"name": "Thread of Hope", "multiplier": "3.51"},
    {"name": "Split Personality", "multiplier": "3.51"},
    {"name": "Replica Tempestuous Steel", "multiplier": "3.51"},
    {"name": "Replica Reckless Defence", "multiplier": "3.51"},
    {"name": "Arn's Anguish", "multiplier": "3.51"},
    {"name": "Olesya's Delight", "multiplier": "3.51"},
    {"name": "Graven's Secret", "multiplier": "3.51"},
    {"name": "Forbidden Flame", "multiplier": "3.51"},
    {"name": "Forbidden Flesh", "multiplier": "3.51"},
    {"name": "Impossible Escape", "multiplier": "3.51"},
    {"name": "That Which Was Taken", "multiplier": "3.51"},
    {"name": "Ixchel's Temptation", "multiplier": "3.51"},
    {"name": "Replica Pacifism", "multiplier": "3.51"},
    {"name": "Replica Fragility", "multiplier": "3.51"},
    {"name": "Replica Powerlessness", "multiplier": "3.51"},
    {"name": "Replica Heatshiver", "multiplier": "3.51"},
    {"name": "Nevalius Inheritance", "multiplier": "3.51"},
    {"name": "Daresso's Passion", "multiplier": "3.46"},
    {"name": "El'Abin's Visage", "multiplier": "3.46"},
    {"name": "Bloodbond", "multiplier": "3.41"},
    {"name": "Wurm's Molt", "multiplier": "3.36"},
    {"name": "Winterheart", "multiplier": "3.36"},
    {"name": "Goldwyrm", "multiplier": "3.32"},
    {"name": "The Primordial Chain", "multiplier": "3.32"},
    {"name": "Plume of Pursuit", "multiplier": "3.32"},
    {"name": "Veruso's Ambition", "multiplier": "3.32"},
    {"name": "Cloak of Flame", "multiplier": "3.31"},
    {"name": "Coruscating Elixir", "multiplier": "3.31"},
    {"name": "Sap of the Seasons", "multiplier": "3.31"},
    {"name": "Mightblood Ire", "multiplier": "3.31"},
    {"name": "Clayshaper", "multiplier": "3.26"},
    {"name": "Sentari's Answer", "multiplier": "3.22"},
    {"name": "Chober Chaber", "multiplier": "3.17"},
    {"name": "Selfless Leadership", "multiplier": "3.17"},
    {"name": "Static Electricity", "multiplier": "3.17"},
    {"name": "Might in All Forms", "multiplier": "3.17"},
    {"name": "Rotgut", "multiplier": "3.17"},
    {"name": "Eclipse Solaris", "multiplier": "3.17"},
    {"name": "Chaber Cairn", "multiplier": "3.17"},
    {"name": "The Aylardex", "multiplier": "3.13"},
    {"name": "Iron Commander", "multiplier": "3.13"},
    {"name": "Replica Bitterdream", "multiplier": "3.13"},
    {"name": "Ahkeli's Valley", "multiplier": "3.12"},
    {"name": "Precursor's Emblem", "multiplier": "3.12"},
    {"name": "Circle of Anguish", "multiplier": "3.12"},
    {"name": "Icetomb", "multiplier": "3.07"},
    {"name": "Crystal Vault", "multiplier": "3.07"},
    {"name": "Orbala's Stand", "multiplier": "3.07"},
    {"name": "Rearguard", "multiplier": "3.03"},
    {"name": "Shadows and Dust", "multiplier": "3.03"},
    {"name": "Demigod's Beacon", "multiplier": "3.03"},
    {"name": "Aukuna's Will", "multiplier": "3.03"},
    {"name": "Replica Winterheart", "multiplier": "3.03"},
    {"name": "Valyrium", "multiplier": "2.99"},
    {"name": "Escalation", "multiplier": "2.99"},
    {"name": "Lioneye's Paws", "multiplier": "2.95"},
    {"name": "Thief's Torment", "multiplier": "2.95"},
    {"name": "Lori's Lantern", "multiplier": "2.95"},
    {"name": "Replica Twyzel", "multiplier": "2.95"},
    {"name": "Zahndethus' Cassock", "multiplier": "2.9"},
    {"name": "Mindspiral", "multiplier": "2.9"},
    {"name": "Cybil's Paw", "multiplier": "2.9"},
    {"name": "Torchoak Step", "multiplier": "2.9"},
    {"name": "Chalice of Horrors", "multiplier": "2.86"},
    {"name": "Ngamahu's Sign", "multiplier": "2.86"},
    {"name": "Skullhead", "multiplier": "2.81"},
    {"name": "Skirmish", "multiplier": "2.81"},
    {"name": "Gifts from Above", "multiplier": "2.78"},
    {"name": "Blightwell", "multiplier": "2.78"},
    {"name": "Replica Leer Cast", "multiplier": "2.78"},
    {"name": "Putembo's Meadow", "multiplier": "2.77"},
    {"name": "Circle of Regret", "multiplier": "2.77"},
    {"name": "The Three Dragons", "multiplier": "2.73"},
    {"name": "Earendel's Embrace", "multiplier": "2.73"},
    {"name": "Willclash", "multiplier": "2.73"},
    {"name": "Meginord's Vigour", "multiplier": "2.73"},
    {"name": "The Sorrow of the Divine", "multiplier": "2.7"},
    {"name": "The Overflowing Chalice", "multiplier": "2.7"},
    {"name": "Coralito's Signature", "multiplier": "2.7"},
    {"name": "Soul Catcher", "multiplier": "2.7"},
    {"name": "Vorana's Preparation", "multiplier": "2.7"},
    {"name": "Lycosidae", "multiplier": "2.69"},
    {"name": "Mortem Morsu", "multiplier": "2.65"},
    {"name": "Ylfe Ban", "multiplier": "2.65"},
    {"name": "Al Dhih", "multiplier": "2.62"},
    {"name": "The Baron", "multiplier": "2.62"},
    {"name": "Fairgraves' Tricorne", "multiplier": "2.61"},
    {"name": "Hyperboreus", "multiplier": "2.61"},
    {"name": "Survivor's Guilt", "multiplier": "2.61"},
    {"name": "Reaper's Pursuit", "multiplier": "2.58"},
    {"name": "Deidbellow", "multiplier": "2.58"},
    {"name": "Windshriek", "multiplier": "2.58"},
    {"name": "Drillneck", "multiplier": "2.54"},
    {"name": "Timeclasp", "multiplier": "2.54"},
    {"name": "Faithguard", "multiplier": "2.54"},
    {"name": "Grattus Signet", "multiplier": "2.54"},
    {"name": "Shavronne's Pace", "multiplier": "2.5"},
    {"name": "Stillwater", "multiplier": "2.5"},
    {"name": "Briskwrap", "multiplier": "2.5"},
    {"name": "Flesh-Eater", "multiplier": "2.5"},
    {"name": "Triad Grip", "multiplier": "2.5"},
    {"name": "Shavronne's Gambit", "multiplier": "2.5"},
    {"name": "Death's Opus", "multiplier": "2.5"},
    {"name": "Le Heup of All", "multiplier": "2.47"},
    {"name": "Pyre", "multiplier": "2.46"},
    {"name": "The Wise Oak", "multiplier": "2.46"},
    {"name": "Uzaza's Mountain", "multiplier": "2.46"},
    {"name": "Circle of Fear", "multiplier": "2.46"},
    {"name": "Replica Tasalio's Sign", "multiplier": "2.46"},
    {"name": "Call of the Void", "multiplier": "2.46"},
    {"name": "Ikiaho's Promise", "multiplier": "2.43"},
    {"name": "Matua Tupuna", "multiplier": "2.4"},
    {"name": "The Trickster's Smile", "multiplier": "2.4"},
    {"name": "Blood of Corruption", "multiplier": "2.39"},
    {"name": "Replica Karui Ward", "multiplier": "2.39"},
    {"name": "Mightflay", "multiplier": "2.36"},
    {"name": "Titucius' Span", "multiplier": "2.36"},
    {"name": "Twyzel", "multiplier": "2.36"},
    {"name": "Eldritch Knowledge", "multiplier": "2.36"},
    {"name": "Fortified Legion", "multiplier": "2.36"},
    {"name": "Chitus' Needle", "multiplier": "2.36"},
    {"name": "The Warden's Brand", "multiplier": "2.36"},
    {"name": "Retaliation Charm", "multiplier": "2.36"},
    {"name": "Elevore", "multiplier": "2.36"},
    {"name": "Veil of the Night", "multiplier": "2.33"},
    {"name": "Edge of Madness", "multiplier": "2.33"},
    {"name": "Replica Veil of the Night", "multiplier": "2.33"},
    {"name": "Relentless Fury", "multiplier": "2.29"},
    {"name": "Thirst for Horrors", "multiplier": "2.29"},
    {"name": "Fated End", "multiplier": "2.25"},
    {"name": "Replica Doedre's Damning", "multiplier": "2.25"},
    {"name": "Wake of Destruction", "multiplier": "2.22"},
    {"name": "Leer Cast", "multiplier": "2.22"},
    {"name": "Death Rattle", "multiplier": "2.22"},
    {"name": "Lakishu's Blade", "multiplier": "2.22"},
    {"name": "The Stormheart", "multiplier": "2.22"},
    {"name": "Viper's Scales", "multiplier": "2.22"},
    {"name": "Doomfletch's Prism", "multiplier": "2.22"},
    {"name": "The Stormwall", "multiplier": "2.22"},
    {"name": "Meginord's Girdle", "multiplier": "2.19"},
    {"name": "Berek's Pass", "multiplier": "2.19"},
    {"name": "Berek's Grip", "multiplier": "2.19"},
    {"name": "Kikazaru", "multiplier": "2.19"},
    {"name": "Belt of the Deceiver", "multiplier": "2.19"},
    {"name": "Tasalio's Sign", "multiplier": "2.19"},
    {"name": "Spirit Guards", "multiplier": "2.19"},
    {"name": "Maligaro's Cruelty", "multiplier": "2.19"},
    {"name": "Tempered Flesh", "multiplier": "2.19"},
    {"name": "Tempered Spirit", "multiplier": "2.19"},
    {"name": "Tempered Mind", "multiplier": "2.19"},
    {"name": "Combat Focus", "multiplier": "2.19"},
    {"name": "Curtain Call", "multiplier": "2.19"},
    {"name": "The Felbog Fang", "multiplier": "2.19"},
    {"name": "Endless Misery", "multiplier": "2.19"},
    {"name": "Apex Mode", "multiplier": "2.19"},
    {"name": "Nadir Mode", "multiplier": "2.19"},
    {"name": "Honoured Alliance", "multiplier": "2.19"},
    {"name": "Geofri's Baptism", "multiplier": "2.16"},
    {"name": "Sundance", "multiplier": "2.16"},
    {"name": "Slitherpinch", "multiplier": "2.16"},
    {"name": "Queen's Decree", "multiplier": "2.16"},
    {"name": "Alkem Eira", "multiplier": "2.16"},
    {"name": "Glitterdisc", "multiplier": "2.16"},
    {"name": "Kiara's Determination", "multiplier": "2.16"},
    {"name": "Sands of Shakari", "multiplier": "2.16"},
    {"name": "Queen's Escape", "multiplier": "2.16"},
    {"name": "Sunspite", "multiplier": "2.16"},
    {"name": "Geofri's Devotion", "multiplier": "2.16"},
    {"name": "Thousand Ribbons", "multiplier": "2.12"},
    {"name": "Tabula Rasa", "multiplier": "2.12"},
    {"name": "Vizaru's Folly", "multiplier": "2.09"},
    {"name": "Ewar's Mirage", "multiplier": "2.09"},
    {"name": "Mark of the Red Covenant", "multiplier": "2.09"},
    {"name": "Atziri's Promise", "multiplier": "2.07"},
    {"name": "Coward's Legacy", "multiplier": "2.06"},
    {"name": "Circle of Guilt", "multiplier": "2.06"},
    {"name": "Chains of Emancipation", "multiplier": "2.06"},
    {"name": "Carnage Heart", "multiplier": "2.03"},
    {"name": "Foxshade", "multiplier": "2.03"},
    {"name": "Mana Sponge", "multiplier": "2.03"},
    {"name": "Prismweave", "multiplier": "2.03"},
    {"name": "Duskwing", "multiplier": "2.03"},
    {"name": "The Learning Stone", "multiplier": "2.03"},
    {"name": "Timetwist", "multiplier": "2.03"},
    {"name": "Fox's Fortune", "multiplier": "2.03"},
    {"name": "Malachai's Simula", "multiplier": "2.01"},
    {"name": "Ashrend", "multiplier": "2.01"},
    {"name": "Solaris Lorica", "multiplier": "2.01"},
    {"name": "Trolltimber Spire", "multiplier": "2.01"},
    {"name": "Watcher's Eye", "multiplier": "2"},
    {"name": "Kitava's Teachings", "multiplier": "2"},
    {"name": "Calamitous Visions", "multiplier": "2"},
    {"name": "Natural Affinity", "multiplier": "2"},
    {"name": "The Interrogation", "multiplier": "2"},
    {"name": "The Siege", "multiplier": "2"},
    {"name": "The Front Line", "multiplier": "2"},
    {"name": "One With Nothing", "multiplier": "2"},
    {"name": "Megalomaniac", "multiplier": "2"},
    {"name": "Widowhail", "multiplier": "2"},
    {"name": "Pagan Geis", "multiplier": "1.97"},
    {"name": "Storm Prison", "multiplier": "1.97"},
    {"name": "Amplification Rod", "multiplier": "1.97"},
    {"name": "Facebreaker", "multiplier": "1.95"},
    {"name": "Mokou's Embrace", "multiplier": "1.95"},
    {"name": "Ahkeli's Mountain", "multiplier": "1.95"},
    {"name": "The Peregrine", "multiplier": "1.92"},
    {"name": "Stormcharger", "multiplier": "1.92"},
    {"name": "Giantsbane", "multiplier": "1.92"},
    {"name": "Whakatutuki o Matua", "multiplier": "1.92"},
    {"name": "Flesh and Spirit", "multiplier": "1.89"},
    {"name": "Replica Bloodplay", "multiplier": "1.89"},
    {"name": "Bones of Ullr", "multiplier": "1.86"},
    {"name": "Quecholli", "multiplier": "1.86"},
    {"name": "Mordhau", "multiplier": "1.86"},
    {"name": "Deerstalker", "multiplier": "1.86"},
    {"name": "Fidelitas' Spike", "multiplier": "1.86"},
    {"name": "Bated Breath", "multiplier": "1.86"},
    {"name": "Praxis", "multiplier": "1.86"},
    {"name": "Panquetzaliztli", "multiplier": "1.86"},
    {"name": "Boreal Shepherd", "multiplier": "1.81"},
    {"name": "Perandus Blazon", "multiplier": "1.75"},
    {"name": "Ungil's Gauche", "multiplier": "1.75"},
    {"name": "Brightbeak", "multiplier": "1.75"},
    {"name": "Daresso's Salute", "multiplier": "1.75"},
    {"name": "Victario's Acuity", "multiplier": "1.75"},
    {"name": "Asphyxia's Wrath", "multiplier": "1.75"},
    {"name": "Shaper's Seed", "multiplier": "1.75"},
    {"name": "Martial Artistry", "multiplier": "1.75"},
    {"name": "Survival Instincts", "multiplier": "1.75"},
    {"name": "Survival Skills", "multiplier": "1.75"},
    {"name": "Survival Secrets", "multiplier": "1.75"},
    {"name": "Cannibalistic Habits", "multiplier": "1.75"},
    {"name": "Spire of Stone", "multiplier": "1.75"},
    {"name": "Apparitions", "multiplier": "1.75"},
    {"name": "Vampire's Might", "multiplier": "1.75"},
    {"name": "Hotheaded", "multiplier": "1.75"},
    {"name": "Combustibles", "multiplier": "1.75"},
    {"name": "Weight of Sin", "multiplier": "1.75"},
    {"name": "The Naming Temporary", "multiplier": "1.75"},
    {"name": "Fragile Bloom", "multiplier": "1.75"},
    {"name": "Brawn", "multiplier": "1.75"},
    {"name": "Clear Mind", "multiplier": "1.75"},
    {"name": "Specialised", "multiplier": "1.75"},
    {"name": "Miser of Misery", "multiplier": "1.75"},
    {"name": "Sacrificial Harvest", "multiplier": "1.75"},
    {"name": "Vaal Sentencing", "multiplier": "1.75"},
    {"name": "Poacher's Aim", "multiplier": "1.75"},
    {"name": "Warlord's Reach", "multiplier": "1.75"},
    {"name": "Assassin's Haste", "multiplier": "1.75"},
    {"name": "Conqueror's Efficiency", "multiplier": "1.75"},
    {"name": "Conqueror's Potency", "multiplier": "1.75"},
    {"name": "Conqueror's Longevity", "multiplier": "1.75"},
    {"name": "Ancient Waystones", "multiplier": "1.75"},
    {"name": "Mutated Growth", "multiplier": "1.75"},
    {"name": "Hungry Abyss", "multiplier": "1.75"},
    {"name": "Zerphi's Youth", "multiplier": "1.75"},
    {"name": "Corrupted Energy", "multiplier": "1.75"},
    {"name": "Blood Sacrifice", "multiplier": "1.75"},
    {"name": "Brittle Barrier", "multiplier": "1.75"},
    {"name": "Pugilist", "multiplier": "1.75"},
    {"name": "Cold Steel", "multiplier": "1.75"},
    {"name": "Fireborn", "multiplier": "1.75"},
    {"name": "Anatomical Knowledge", "multiplier": "1.75"},
    {"name": "The Deep One's Hide", "multiplier": "1.75"},
    {"name": "Lavianga's Wisdom", "multiplier": "1.75"},
    {"name": "Shattered Chains", "multiplier": "1.75"},
    {"name": "Weight of the Empire", "multiplier": "1.75"},
    {"name": "Steel Spirit", "multiplier": "1.75"},
    {"name": "Growing Agony", "multiplier": "1.75"},
    {"name": "The Vigil", "multiplier": "1.75"},
    {"name": "Rolling Flames", "multiplier": "1.75"},
    {"name": "Winter's Bounty", "multiplier": "1.75"},
    {"name": "Spirited Response", "multiplier": "1.75"},
    {"name": "Spine of the First Claimant", "multiplier": "1.75"},
    {"name": "Izaro's Turmoil", "multiplier": "1.75"},
    {"name": "Extractor Mentis", "multiplier": "1.75"},
    {"name": "Rapid Expansion", "multiplier": "1.75"},
    {"name": "Volley Fire", "multiplier": "1.75"},
    {"name": "Demigod's Dominance", "multiplier": "1.75"},
    {"name": "The Tempestuous Steel", "multiplier": "1.75"},
    {"name": "Cheap Construction", "multiplier": "1.75"},
    {"name": "Hair Trigger", "multiplier": "1.75"},
    {"name": "Coated Shrapnel", "multiplier": "1.75"},
    {"name": "Unstable Payload", "multiplier": "1.75"},
    {"name": "Saemus' Gift", "multiplier": "1.75"},
    {"name": "Underdog's Fury", "multiplier": "1.75"},
    {"name": "Collateral Damage", "multiplier": "1.75"},
    {"name": "Sudden Ignition", "multiplier": "1.75"},
    {"name": "Overwhelming Odds", "multiplier": "1.75"},
    {"name": "First Snow", "multiplier": "1.75"},
    {"name": "Omen on the Winds", "multiplier": "1.75"},
    {"name": "Wildfire", "multiplier": "1.75"},
    {"name": "Fight for Survival", "multiplier": "1.75"},
    {"name": "Might and Influence", "multiplier": "1.75"},
    {"name": "Frozen Trail", "multiplier": "1.75"},
    {"name": "Ring of Blades", "multiplier": "1.75"},
    {"name": "Boundless Grasp", "multiplier": "1.75"},
    {"name": "Inevitability", "multiplier": "1.75"},
    {"name": "Winter Burial", "multiplier": "1.75"},
    {"name": "Spreading Rot", "multiplier": "1.75"},
    {"name": "Violent Dead", "multiplier": "1.75"},
    {"name": "Hazardous Research", "multiplier": "1.75"},
    {"name": "Choking Ash", "multiplier": "1.75"},
    {"name": "Straight and True", "multiplier": "1.75"},
    {"name": "From Dust", "multiplier": "1.75"},
    {"name": "The Long Winter", "multiplier": "1.75"},
    {"name": "Unearth Threshold", "multiplier": "1.75"},
    {"name": "Toxic Vapours", "multiplier": "1.75"},
    {"name": "Seething Fury", "multiplier": "1.75"},
    {"name": "Replica Conqueror's Efficiency", "multiplier": "1.75"},
    {"name": "Lord of Steel", "multiplier": "1.75"},
    {"name": "Replica Hotheaded", "multiplier": "1.75"},
    {"name": "Replica Pure Talent", "multiplier": "1.75"},
    {"name": "Replica Fragile Bloom", "multiplier": "1.75"},
    {"name": "Replica Unstable Payload", "multiplier": "1.75"},
    {"name": "Replica Blood Sacrifice", "multiplier": "1.75"},
    {"name": "Replica Cheap Construction", "multiplier": "1.75"},
    {"name": "Frostferno", "multiplier": "1.75"},
    {"name": "The Tactician", "multiplier": "1.75"},
    {"name": "The Nomad", "multiplier": "1.75"},
    {"name": "Divine Inferno", "multiplier": "1.75"},
    {"name": "Victario's Flight", "multiplier": "1.73"},
    {"name": "Ashcaller", "multiplier": "1.73"},
    {"name": "Putembo's Valley", "multiplier": "1.73"},
    {"name": "Ghostwrithe", "multiplier": "1.68"},
    {"name": "Dusktoe", "multiplier": "1.65"},
    {"name": "Wideswing", "multiplier": "1.65"},
    {"name": "Ghostmarch", "multiplier": "1.65"},
    {"name": "Faminebind", "multiplier": "1.65"},
    {"name": "Roth's Reach", "multiplier": "1.65"},
    {"name": "Duskblight", "multiplier": "1.65"},
    {"name": "Thrillsteel", "multiplier": "1.65"},
    {"name": "Doryani's Invitation", "multiplier": "1.63"},
    {"name": "Night's Hold", "multiplier": "1.63"},
    {"name": "String of Servitude", "multiplier": "1.63"},
    {"name": "Bear's Girdle", "multiplier": "1.63"},
    {"name": "Hrimnor's Hymn", "multiplier": "1.6"},
    {"name": "Aurumvorax", "multiplier": "1.6"},
    {"name": "Hrimnor's Dirge", "multiplier": "1.6"},
    {"name": "Malachai's Awakening", "multiplier": "1.6"},
    {"name": "Kaltenhalt", "multiplier": "1.56"},
    {"name": "Battlehaste", "multiplier": "1.56"},
    {"name": "Nomic's Storm", "multiplier": "1.56"},
    {"name": "Dreadarc", "multiplier": "1.56"},
    {"name": "Kaltensoul", "multiplier": "1.56"},
    {"name": "Dreadsurge", "multiplier": "1.56"},
    {"name": "Uzaza's Meadow", "multiplier": "1.54"},
    {"name": "Wreath of Phrecia", "multiplier": "1.54"},
    {"name": "Demigod's Presence", "multiplier": "1.51"},
    {"name": "The Ignomon", "multiplier": "1.51"},
    {"name": "Band of the Victor", "multiplier": "1.51"},
    {"name": "Bloodplay", "multiplier": "1.51"},
    {"name": "Frost Unbroken", "multiplier": "1.51"},
    {"name": "The Effigon", "multiplier": "1.51"},
    {"name": "The Untouched Soul", "multiplier": "1.51"},
    {"name": "The Goddess Bound", "multiplier": "1.49"},
    {"name": "Shackles of the Wretched", "multiplier": "1.49"},
    {"name": "Hyrri's Bite", "multiplier": "1.47"},
    {"name": "Hyrri's Demise", "multiplier": "1.47"},
    {"name": "Chain of Endurance", "multiplier": "1.47"},
    {"name": "Limbsplit", "multiplier": "1.43"},
    {"name": "Pillar of the Caged God", "multiplier": "1.43"},
    {"name": "Dying Breath", "multiplier": "1.43"},
    {"name": "Realmshaper", "multiplier": "1.43"},
    {"name": "The Cauteriser", "multiplier": "1.43"},
    {"name": "Realm Ender", "multiplier": "1.43"},
    {"name": "Doedre's Damning", "multiplier": "1.41"},
    {"name": "Quill Rain", "multiplier": "1.41"},
    {"name": "Replica Quill Rain", "multiplier": "1.41"},
    {"name": "Shiversting", "multiplier": "1.38"},
    {"name": "Honourhome", "multiplier": "1.38"},
    {"name": "Doedre's Tenure", "multiplier": "1.38"},
    {"name": "Demigod's Triumph", "multiplier": "1.38"},
    {"name": "Ungils's Coil", "multiplier": "1.38"},
    {"name": "Demigod's Stride", "multiplier": "1.38"},
    {"name": "Galla's Riposte", "multiplier": "1.38"},
    {"name": "Doedre's Elixir", "multiplier": "1.38"},
    {"name": "Demigod's Touch", "multiplier": "1.38"},
    {"name": "Stormblast", "multiplier": "1.38"},
    {"name": "Demigod's Bounty", "multiplier": "1.38"},
    {"name": "Demigod's Eye", "multiplier": "1.38"},
    {"name": "Wildslash", "multiplier": "1.38"},
    {"name": "Demigod's Immortality", "multiplier": "1.38"},
    {"name": "Doedre's Malevolence", "multiplier": "1.38"},
    {"name": "Honourhold", "multiplier": "1.38"},
    {"name": "Kaom's Sign", "multiplier": "1.37"},
    {"name": "Replica Blood Thorn", "multiplier": "1.37"},
    {"name": "Replica Fencoil", "multiplier": "1.37"},
    {"name": "Feastbind", "multiplier": "1.34"},
    {"name": "Sadima's Touch", "multiplier": "1.33"},
    {"name": "Goldrim", "multiplier": "1.33"},
    {"name": "Sacrificial Heart", "multiplier": "1.33"},
    {"name": "Replica Last Resort", "multiplier": "1.33"},
    {"name": "Maligaro's Etcher", "multiplier": "1.3"},
    {"name": "The Princess", "multiplier": "1.3"},
    {"name": "Gorebreaker", "multiplier": "1.3"},
    {"name": "Axiom Perpetuum", "multiplier": "1.3"},
    {"name": "Coward's Chains", "multiplier": "1.29"},
    {"name": "Replica Prismweave", "multiplier": "1.29"},
    {"name": "Wondertrap", "multiplier": "1.27"},
    {"name": "Hrimsorrow", "multiplier": "1.27"},
    {"name": "Storm Cloud", "multiplier": "1.27"},
    {"name": "Hrimburn", "multiplier": "1.27"},
    {"name": "The Tempest", "multiplier": "1.27"},
    {"name": "Greedtrap", "multiplier": "1.27"},
    {"name": "Wildwrap", "multiplier": "1.27"},
    {"name": "Bramblejack", "multiplier": "1.25"},
    {"name": "Crest of Perandus", "multiplier": "1.23"},
    {"name": "Asenath's Chant", "multiplier": "1.23"},
    {"name": "Stone of Lazhwar", "multiplier": "1.19"},
    {"name": "Broadstroke", "multiplier": "1.19"},
    {"name": "Karui Ward", "multiplier": "1.19"},
    {"name": "Springleaf", "multiplier": "1.19"},
    {"name": "The Rathorn", "multiplier": "1.19"},
    {"name": "Tear of Purity", "multiplier": "1.19"},
    {"name": "Karui Charge", "multiplier": "1.19"},
    {"name": "The Oak", "multiplier": "1.19"},
    {"name": "The Screaming Eagle", "multiplier": "1.16"},
    {"name": "Abberath's Horn", "multiplier": "1.16"},
    {"name": "The Gryphon", "multiplier": "1.16"},
    {"name": "Ondar's Clasp", "multiplier": "1.13"},
    {"name": "Wheel of the Stormsail", "multiplier": "1.13"},
    {"name": "Goredrill", "multiplier": "1.13"},
    {"name": "Sanguine Gambol", "multiplier": "1.13"},
    {"name": "The Megalomaniac", "multiplier": "1.13"},
    {"name": "Wurmfist", "multiplier": "1.09"},
    {"name": "Vestige of Divinity", "multiplier": "1.09"},
    {"name": "Fencoil", "multiplier": "1.09"},
    {"name": "Craghead", "multiplier": "1.09"},
    {"name": "The Blood Thorn", "multiplier": "1.09"},
    {"name": "Kaom's Way", "multiplier": "1.09"},
    {"name": "Cragfall", "multiplier": "1.09"},
    {"name": "Mirebough", "multiplier": "1.09"},
    {"name": "Sidhebreath", "multiplier": "1.06"},
    {"name": "Crown of Thorns", "multiplier": "1.06"},
    {"name": "Araku Tiki", "multiplier": "1.06"},
    {"name": "Wanderlust", "multiplier": "1.06"},
    {"name": "Last Resort", "multiplier": "1.06"},
    {"name": "DrTestapus' Charm", "multiplier": "1.06"},
    {"name": "Thunder of the Dawn", "multiplier": "1.06"},
    {"name": "Ironweld", "multiplier": "1.06"},
    {"name": "Scar of Fate", "multiplier": "1.06"},
    {"name": "Ngamahu Tiki", "multiplier": "1.06"},
    {"name": "Martyr's Crown", "multiplier": "1.06"},
    {"name": "Sidhebite", "multiplier": "1.06"},
    {"name": "Blackheart", "multiplier": "1.03"},
    {"name": "Blackgleam", "multiplier": "1.03"},
    {"name": "Dewath's Hide", "multiplier": "1.03"},
    {"name": "Remnant of Empires", "multiplier": "1.03"},
    {"name": "Rust of Winter", "multiplier": "1.03"},
    {"name": "Chains of Time", "multiplier": "1.03"},
    {"name": "Voidheart", "multiplier": "1.03"},
    {"name": "Oni-Goroshi", "multiplier": "1.03"},
    {"name": "Redbeak", "multiplier": "1"},
    {"name": "Silverbranch", "multiplier": "1"},
    {"name": "Ezomyte Peak", "multiplier": "1"},
    {"name": "Lochtonial Caress", "multiplier": "1"},
    {"name": "Fragment of Eternity", "multiplier": "1"},
    {"name": "Splinter of the Moon", "multiplier": "1"},
    {"name": "Ashes of the Sun", "multiplier": "1"},
    {"name": "Relic of the Cycle", "multiplier": "1"},
    {"name": "Tear of Entropy", "multiplier": "1"},
    {"name": "Lifesprig", "multiplier": "1"},
    {"name": "Celestial Fragment", "multiplier": "1"},
    {"name": "Bartek's Finger", "multiplier": "1"},
    {"name": "Blood of Summer", "multiplier": "1"},
    {"name": "Talisman of the Victor", "multiplier": "1"},
    {"name": "Slivers of Providence", "multiplier": "1"},
    {"name": "First Piece of the Arcane", "multiplier": "1"},
    {"name": "Second Piece of the Arcane", "multiplier": "1"},
    {"name": "Third Piece of the Arcane", "multiplier": "1"},
    {"name": "First Piece of Time", "multiplier": "1"},
    {"name": "Second Piece of Time", "multiplier": "1"},
    {"name": "Terror", "multiplier": "1"},
    {"name": "Stalwart Defenders", "multiplier": "1"},
    {"name": "Misinformation", "multiplier": "1"},
    {"name": "Irresistible Temptation", "multiplier": "1"},
    {"name": "Territories Unknown", "multiplier": "1"},
    {"name": "War Among the Stars", "multiplier": "1"},
    {"name": "Booming Populace", "multiplier": "1"},
    {"name": "The Warlord's Annex", "multiplier": "1"},
    {"name": "Demigod's Authority", "multiplier": "1"},
    {"name": "The Walls", "multiplier": "1"},
    {"name": "The Claim", "multiplier": "1"},
    {"name": "The Closest Peak", "multiplier": "1"},
    {"name": "Atop the Atlas", "multiplier": "1"},
    {"name": "The Vast Horizon", "multiplier": "1"},
    {"name": "The Builder", "multiplier": "1"},
    {"name": "Restless Cycles", "multiplier": "1"},
    {"name": "The False Hope", "multiplier": "1"},
    {"name": "Wall of Brambles", "multiplier": "1"},
    {"name": "Ezomyte Hold", "multiplier": "1"},
    {"name": "Silverbough", "multiplier": "1"},
    {"name": "Dreadbeak", "multiplier": "1"},
    {"name": "Beauty", "multiplier": "1"},
    {"name": "Curiosity", "multiplier": "1"},
    {"name": "Ambition", "multiplier": "1"},
    {"name": "Cooperation", "multiplier": "1"},
    {"name": "The Hour of Divinity", "multiplier": "1"},
    {"name": "The Night Lamp", "multiplier": "1"},
    {"name": "The Blood of Innocence", "multiplier": "1"},
    {"name": "The Perandus Pact", "multiplier": "1"},
    {"name": "Curio of Absorption", "multiplier": "1"},
    {"name": "Curio of Consumption", "multiplier": "1"},
    {"name": "Curio of Potential", "multiplier": "1"},
    {"name": "Curio of Decay", "multiplier": "1"},
    {"name": "The Light of Meaning", "multiplier": "1"},
]

with open("uniques.csv") as csv_file:
    text = csv_file.read()
    lines = text.split("\n")[1:-1]
    uniques = []
    for line in lines:
        parts = line.split(",")
        name = parts[0].strip('"')
        base_type = parts[6].strip('"')
        uniques.append(
            {
                "name": name,
                "base_type": base_type,
            }
        )

unique_base_types = list(set([unique["base_type"] for unique in uniques]))

dust_values_for_bases = []
for unique_base_type in unique_base_types:
    possible_uniques = [
        item["name"] for item in uniques if item["base_type"] == unique_base_type
    ]
    multipliers = [
        float(item["multiplier"])
        for item in dust_uniques
        if item["name"] in possible_uniques
    ]
    dust_values_for_bases.append(
        {
            "base_type": unique_base_type,
            "multipliers": multipliers or [0],
        }
    )

good_dust_uniques = [
    item["base_type"]
    for item in dust_values_for_bases
    if min(item["multipliers"]) >= 10
]

rules.append(
    Show(
        [
            Rarity(RARITY.UNIQUE),
            MultiBaseType(good_dust_uniques),
            TierStyle(TIER.RARE),
        ]
    )
)
