from app.common import (
    altered_bases,
    bases,
    card,
    currency,
    essence,
    gem,
    heist,
    leveling,
    map,
    miscellaneous,
    quest,
    unique,
    veiled,
    vendor,
)

rules = [
    *altered_bases.rules,
    *bases.rules,
    *card.rules,
    *currency.rules,
    *essence.rules,
    *gem.rules,
    *heist.rules,
    *leveling.rules,
    *map.rules,
    *miscellaneous.rules,
    *quest.rules,
    *unique.rules,
    *veiled.rules,
    *vendor.rules,
]
