from app.common import (
    altered_bases,
    bases,
    card,
    cluster,
    currency,
    essence,
    flasks,
    gem,
    heist,
    map,
    miscellaneous,
    quest,
    unique,
    veiled,
    vendor,
    hide,
)

rules = [
    *altered_bases.rules,
    *bases.rules,
    *card.rules,
    *cluster.rules,
    *currency.rules,
    *essence.rules,
    *flasks.rules,
    *gem.rules,
    *heist.rules,
    *map.rules,
    *miscellaneous.rules,
    *quest.rules,
    *unique.rules,
    *veiled.rules,
    *vendor.rules,
    # Very important that the hide rules go last
    *hide.rules,
]
