from app import categories, extensions
from app.rules import Rule

COMMON = "common"
RARE = "rare"
EPIC = "epic"
LEGENDARY = "legendary"
PLACEHOLDER = "placeholder"

cards = {
    "A Chilling Wind": COMMON,
    "A Dab of Ink": LEGENDARY,
    "A Dusty Memory": COMMON,
    "A Familiar Call": COMMON,
    "A Fate Worse Than Death": LEGENDARY,
    "A Modest Request": LEGENDARY,
    "A Mother's Parting Gift": COMMON,
    "A Note in the Wind": COMMON,
    "A Sea of Blue": RARE,
    "A Stone Perfected": LEGENDARY,
    "Abandoned Wealth": LEGENDARY,
    "Acclimatisation": RARE,
    "Akil's Prophecy": COMMON,
    "Alivia's Grace": COMMON,
    "Alluring Bounty": LEGENDARY,
    "Alone in the Darkness": COMMON,
    "Altered Perception": LEGENDARY,
    "Ambitious Obsession": LEGENDARY,
    "Anarchy's Price": COMMON,
    "Arrogance of the Vaal": LEGENDARY,
    "Assassin's Favour": COMMON,
    "Assassin's Gift": COMMON,
    "Astral Protection": COMMON,
    "Atziri's Arsenal": LEGENDARY,
    "Audacity": COMMON,
    "Auspicious Ambitions": LEGENDARY,
    "Azure Rage": RARE,
    "Azyran's Reward": LEGENDARY,
    "Baited Expectations": LEGENDARY,
    "Beauty Through Death": COMMON,
    "Bijoux": LEGENDARY,
    "Blind Venture": LEGENDARY,
    "Boon of Justice": RARE,
    "Boon of the First Ones": COMMON,
    "Boundless Realms": RARE,
    "Bowyer's Dream": LEGENDARY,
    "Broken Promises": LEGENDARY,
    "Broken Truce": COMMON,
    "Brother's Gift": LEGENDARY,
    "Brother's Stash": LEGENDARY,
    "Brotherhood in Exile": COMMON,
    "Brush, Paint and Palette": LEGENDARY,
    "Buried Treasure": RARE,
    "Burning Blood": COMMON,
    "Call to the First Ones": COMMON,
    "Cameria's Cut": RARE,
    "Cartographer's Delight": RARE,
    "Chaotic Disposition": EPIC,
    "Chasing Risk": LEGENDARY,
    "Checkmate": LEGENDARY,
    "Choking Guilt": COMMON,
    "Costly Curio": LEGENDARY,
    "Council of Cats": COMMON,
    "Coveted Possession": RARE,
    "Cursed Words": COMMON,
    "Dark Dreams": LEGENDARY,
    "Dark Temptation": RARE,
    "Darker Half": LEGENDARY,
    "Deadly Joy": COMMON,
    "Death": COMMON,
    "Deathly Designs": LEGENDARY,
    "Dementophobia": LEGENDARY,
    "Demigod's Wager": LEGENDARY,
    "Desecrated Virtue": LEGENDARY,
    "Desperate Crusade": LEGENDARY,
    "Destined to Crumble": RARE,
    "Dialla's Subjugation": RARE,
    "Disdain": EPIC,
    "Divine Beauty": LEGENDARY,
    "Doedre's Madness": COMMON,
    "Draped in Dreams": LEGENDARY,
    "Duality": COMMON,
    "Dying Light": COMMON,
    "Earth Drinker": COMMON,
    "Echoes of Love": COMMON,
    "Eldritch Perfection": LEGENDARY,
    "Emperor of Purity": LEGENDARY,
    "Emperor's Luck": RARE,
    "Endless Night": COMMON,
    "Etched in Blood": COMMON,
    "Eternal Bonds": LEGENDARY,
    "Ever-Changing": LEGENDARY,
    "Fateful Meeting": LEGENDARY,
    "Fire Of Unknown Origin": LEGENDARY,
    "Forbidden Power": COMMON,
    "From Bone to Ashes": COMMON,
    "Further Invention": LEGENDARY,
    "Gemcutter's Mercy": LEGENDARY,
    "Gemcutter's Promise": RARE,
    "Gift of Asenath": LEGENDARY,
    "Gift of the Gemling Queen": RARE,
    "Glimmer of Hope": RARE,
    "Grave Knowledge": LEGENDARY,
    "Guardian's Challenge": LEGENDARY,
    "Harmony of Souls": LEGENDARY,
    "Haunting Shadows": COMMON,
    "Her Mask": COMMON,
    "Heterochromia": RARE,
    "Home": LEGENDARY,
    "Hope": RARE,
    "House of Mirrors": LEGENDARY,
    "Hubris": RARE,
    "Humility": LEGENDARY,
    "Hunter's Resolve": COMMON,
    "Hunter's Reward": LEGENDARY,
    "I See Brothers": LEGENDARY,
    "Immortal Resolve": LEGENDARY,
    "Imperfect Memories": LEGENDARY,
    "Imperial Legacy": LEGENDARY,
    "Jack in the Box": RARE,
    "Judging Voices": LEGENDARY,
    "Justified Ambition": LEGENDARY,
    "Keeper's Corruption": LEGENDARY,
    "Lachrymal Necrosis": LEGENDARY,
    "Lantador's Lost Love": COMMON,
    "Last Hope": COMMON,
    "Left to Fate": RARE,
    "Lethean Temptation": COMMON,
    "Light and Truth": COMMON,
    "Lingering Remnants": LEGENDARY,
    "Lost Worlds": RARE,
    "Love Through Ice": LEGENDARY,
    "Loyalty": RARE,
    "Lucky Connections": RARE,
    "Lucky Deck": RARE,
    "Luminous Trove": LEGENDARY,
    "Lysah's Respite": COMMON,
    "Magnum Opus": LEGENDARY,
    "Man With Bear": RARE,
    "Matryoshka": RARE,
    "Mawr Blaidd": COMMON,
    "Merciless Armament": COMMON,
    "Might is Right": COMMON,
    "Misery in Darkness": LEGENDARY,
    "Mitts": RARE,
    "Monochrome": LEGENDARY,
    "More is Never Enough": LEGENDARY,
    "No Traces": LEGENDARY,
    "Nook's Crown": LEGENDARY,
    "Parasitic Passengers": RARE,
    "Peaceful Moments": LEGENDARY,
    "Perfection": RARE,
    "Poisoned Faith": LEGENDARY,
    "Prejudice": COMMON,
    "Pride Before the Fall": COMMON,
    "Pride of the First Ones": COMMON,
    "Prometheus' Armoury": RARE,
    "Prosperity": RARE,
    "Rain of Chaos": RARE,
    "Rain Tempter": RARE,
    "Rats": COMMON,
    "Rebirth": COMMON,
    "Rebirth and Renewal": LEGENDARY,
    "Reckless Ambition": COMMON,
    "Remembrance": RARE,
    "Sambodhi's Vow": COMMON,
    "Sambodhi's Wisdom": RARE,
    "Scholar of the Seas": LEGENDARY,
    "Seven Years Bad Luck": LEGENDARY,
    "Shard of Fate": RARE,
    "Silence and Frost": COMMON,
    "Society's Remorse": RARE,
    "Something Dark": LEGENDARY,
    "Soul Quenched": RARE,
    "Struck by Lightning": COMMON,
    "Succor of the Sinless": LEGENDARY,
    "The Academic": LEGENDARY,
    "The Admirer": COMMON,
    "The Adventuring Spirit": COMMON,
    "The Aesthete": COMMON,
    "The Apothecary": LEGENDARY,
    "The Archmage's Right Hand": COMMON,
    "The Arena Champion": RARE,
    "The Army of Blood": COMMON,
    "The Artist": LEGENDARY,
    "The Aspirant": RARE,
    "The Astromancer": LEGENDARY,
    "The Avenger": COMMON,
    "The Awakened": COMMON,
    "The Battle Born": COMMON,
    "The Bear Woman": COMMON,
    "The Beast": COMMON,
    "The Betrayal": COMMON,
    "The Bitter Blossom": LEGENDARY,
    "The Blazing Fire": COMMON,
    "The Body": RARE,
    "The Bones": COMMON,
    "The Brawny Battle Mage": COMMON,
    "The Breach": LEGENDARY,
    "The Brittle Emperor": COMMON,
    "The Cache": LEGENDARY,
    "The Cacophony": LEGENDARY,
    "The Calling": COMMON,
    "The Card Sharp": RARE,
    "The Carrion Crow": COMMON,
    "The Cartographer": RARE,
    "The Cataclysm": RARE,
    "The Catalyst": RARE,
    "The Catch": LEGENDARY,
    "The Celestial Justicar": LEGENDARY,
    "The Celestial Stone": COMMON,
    "The Chains that Bind": LEGENDARY,
    "The Cheater": LEGENDARY,
    "The Chosen": LEGENDARY,
    "The Coming Storm": LEGENDARY,
    "The Conduit": COMMON,
    "The Craving": LEGENDARY,
    "The Cursed King": COMMON,
    "The Damned": COMMON,
    "The Dapper Prodigy": LEGENDARY,
    "The Dark Mage": RARE,
    "The Darkest Dream": COMMON,
    "The Deal": RARE,
    "The Deceiver": COMMON,
    "The Deep Ones": COMMON,
    "The Demon": LEGENDARY,
    "The Demoness": COMMON,
    "The Destination": LEGENDARY,
    "The Doctor": LEGENDARY,
    "The Doppelganger": RARE,
    "The Dragon": COMMON,
    "The Dragon's Heart": LEGENDARY,
    "The Dreamer": LEGENDARY,
    "The Dreamland": LEGENDARY,
    "The Drunken Aristocrat": RARE,
    "The Dungeon Master": COMMON,
    "The Easy Stroll": RARE,
    "The Eldritch Decay": LEGENDARY,
    "The Emptiness": COMMON,
    "The Encroaching Darkness": LEGENDARY,
    "The Endless Darkness": COMMON,
    "The Endurance": RARE,
    "The Enforcer": COMMON,
    "The Enlightened": LEGENDARY,
    "The Enthusiasts": COMMON,
    "The Escape": LEGENDARY,
    "The Eternal War": LEGENDARY,
    "The Ethereal": LEGENDARY,
    "The Explorer": RARE,
    "The Eye of Terror": LEGENDARY,
    "The Eye of the Dragon": LEGENDARY,
    "The Fathomless Depths": COMMON,
    "The Feast": COMMON,
    "The Fiend": LEGENDARY,
    "The Finishing Touch": EPIC,
    "The Fishmonger": PLACEHOLDER,
    "The Fletcher": COMMON,
    "The Flora's Gift": COMMON,
    "The Fool": RARE,
    "The Forgotten Treasure": RARE,
    "The Formless Sea": COMMON,
    "The Forsaken": COMMON,
    "The Fortunate": LEGENDARY,
    "The Forward Gaze": RARE,
    "The Fox": RARE,
    "The Fox in the Brambles": COMMON,
    "The Gambler": RARE,
    "The Garish Power": LEGENDARY,
    "The Gemcutter": RARE,
    "The Gentleman": COMMON,
    "The Gladiator": COMMON,
    "The Golden Era": COMMON,
    "The Greatest Intentions": ChildProcessError,
    "The Gulf": LEGENDARY,
    "The Hale Heart": LEGENDARY,
    "The Harvester": COMMON,
    "The Hermit": COMMON,
    "The Heroic Shot": RARE,
    "The Hive of Knowledge": COMMON,
    "The Hoarder": LEGENDARY,
    "The Hunger": LEGENDARY,
    "The Immortal": LEGENDARY,
    "The Incantation": COMMON,
    "The Innocent": LEGENDARY,
    "The Inoculated": COMMON,
    "The Insane Cat": LEGENDARY,
    "The Insatiable": COMMON,
    "The Inventor": RARE,
    "The Jester": COMMON,
    "The Jeweller's Boon": COMMON,
    "The Journalist": RARE,
    "The Journey": EPIC,
    "The King's Blade": COMMON,
    "The King's Heart": COMMON,
    "The Landing": LEGENDARY,
    "The Last One Standing": COMMON,
    "The Last Supper": COMMON,
    "The Leviathan": LEGENDARY,
    "The Lich": COMMON,
    "The Life Thief": COMMON,
    "The Lion": COMMON,
    "The Long Con": LEGENDARY,
    "The Lord in Black": COMMON,
    "The Lord of Celebration": COMMON,
    "The Lover": COMMON,
    "The Lunaris Priestess": COMMON,
    "The Mad King": LEGENDARY,
    "The Magma Crab": RARE,
    "The Master": COMMON,
    "The Master Artisan": RARE,
    "The Mercenary": RARE,
    "The Messenger": COMMON,
    "The Metalsmith's Gift": COMMON,
    "The Mind's Eyes": COMMON,
    "The Mountain": COMMON,
    "The Nurse": LEGENDARY,
    "The Oath": COMMON,
    "The Obscured": LEGENDARY,
    "The Offering": COMMON,
    "The Offspring": COMMON,
    "The Old Man": LEGENDARY,
    "The One That Got Away": COMMON,
    "The One With All": RARE,
    "The Opulent": RARE,
    "The Pack Leader": COMMON,
    "The Pact": COMMON,
    "The Patient": LEGENDARY,
    "The Penitent": LEGENDARY,
    "The Poet": COMMON,
    "The Polymath": LEGENDARY,
    "The Porcupine": LEGENDARY,
    "The Price of Devotion": LEGENDARY,
    "The Price of Loyalty": LEGENDARY,
    "The Price of Prescience": LEGENDARY,
    "The Price of Protection": LEGENDARY,
    "The Primordial": LEGENDARY,
    "The Prince of Darkness": LEGENDARY,
    "The Professor": LEGENDARY,
    "The Progeny of Lunaris": COMMON,
    "The Puzzle": RARE,
    "The Queen": COMMON,
    "The Rabbit's Foot": LEGENDARY,
    "The Rabid Rhoa": COMMON,
    "The Realm": RARE,
    "The Return of the Rat": COMMON,
    "The Risk": RARE,
    "The Rite of Elements": COMMON,
    "The Road to Power": COMMON,
    "The Rusted Bard": LEGENDARY,
    "The Ruthless Ceinture": COMMON,
    "The Sacrifice": LEGENDARY,
    "The Saint's Treasure": LEGENDARY,
    "The Samurai's Eye": LEGENDARY,
    "The Scarred Meadow": COMMON,
    "The Scavenger": COMMON,
    "The Scholar": RARE,
    "The Scout": LEGENDARY,
    "The Seeker": LEGENDARY,
    "The Sephirot": LEGENDARY,
    "The Shepherd's Sandals": LEGENDARY,
    "The Shieldbearer": LEGENDARY,
    "The Shortcut": LEGENDARY,
    "The Side Quest": EPIC,
    "The Sigil": COMMON,
    "The Siren": COMMON,
    "The Skeleton": RARE,
    "The Soul": COMMON,
    "The Spark and the Flame": LEGENDARY,
    "The Spoiled Prince": COMMON,
    "The Standoff": COMMON,
    "The Stormcaller": COMMON,
    "The Strategist": LEGENDARY,
    "The Summoner": RARE,
    "The Sun": RARE,
    "The Surgeon": COMMON,
    "The Surveyor": RARE,
    "The Survivalist": RARE,
    "The Sword King's Salute": COMMON,
    "The Thaumaturgist": COMMON,
    "The Throne": LEGENDARY,
    "The Tinkerer's Table": EPIC,
    "The Tireless Extractor": EPIC,
    "The Tower": COMMON,
    "The Traitor": COMMON,
    "The Transformation": LEGENDARY,
    "The Trial": RARE,
    "The Tumbleweed": COMMON,
    "The Twilight Moon": LEGENDARY,
    "The Twins": COMMON,
    "The Tyrant": COMMON,
    "The Undaunted": COMMON,
    "The Undisputed": COMMON,
    "The Unexpected Prize": COMMON,
    "The Union": RARE,
    "The Valkyrie": COMMON,
    "The Vast": COMMON,
    "The Visionary": COMMON,
    "The Void": RARE,
    "The Warden": COMMON,
    "The Warlord": LEGENDARY,
    "The Watcher": COMMON,
    "The Web": COMMON,
    "The Wedding Gift": LEGENDARY,
    "The White Knight": LEGENDARY,
    "The Whiteout": COMMON,
    "The Wilted Rose": EPIC,
    "The Wind": COMMON,
    "The Witch": COMMON,
    "The Wolf": COMMON,
    "The Wolf's Legacy": LEGENDARY,
    "The Wolf's Shadow": COMMON,
    "The Wolven King's Bite": COMMON,
    "The Wolverine": COMMON,
    "The World Eater": COMMON,
    "The Wrath": EPIC,
    "The Wretched": RARE,
    "Thirst for Knowledge": COMMON,
    "Three Faces in the Dark": EPIC,
    "Three Voices": RARE,
    "Thunderous Skies": COMMON,
    "Time-Lost Relic": RARE,
    "Tranquillity": COMMON,
    "Treasure Hunter": LEGENDARY,
    "Triskaidekaphobia": RARE,
    "Turn the Other Cheek": COMMON,
    "Unchained": COMMON,
    "Underground Forest": EPIC,
    "Unrequited Love": LEGENDARY,
    "Vanity": LEGENDARY,
    "Vile Power": COMMON,
    "Vinia's Token": EPIC,
    "Void of the Elements": COMMON,
    "Volatile Power": RARE,
    "Wealth and Power": LEGENDARY,
    "Who Asked": RARE,
    "Winter's Embrace": LEGENDARY,
}

common_cards = [
    card_name for (card_name, card_tier) in cards.items() if card_tier == COMMON
]
rare_cards = [
    card_name for (card_name, card_tier) in cards.items() if card_tier == RARE
]
epic_cards = [
    card_name for (card_name, card_tier) in cards.items() if card_tier == EPIC
]
legendary_cards = [
    card_name for (card_name, card_tier) in cards.items() if card_tier == LEGENDARY
]


rules = [
    Rule(
        instruction=extensions.Show(),
        extensions=[
            extensions.BaseType(base_type="Stacked Deck"),
            extensions.TierStyle(tier=categories.TIER.RARE),
        ],
    ),
    Rule(
        instruction=extensions.Show(),
        extensions=[
            extensions.MultiBaseType(base_types=legendary_cards),
            extensions.TierStyle(tier=categories.TIER.LEGENDARY),
        ],
    ),
    Rule(
        instruction=extensions.Show(),
        extensions=[
            extensions.MultiBaseType(base_types=epic_cards),
            extensions.TierStyle(tier=categories.TIER.EPIC),
        ],
    ),
    Rule(
        instruction=extensions.Show(),
        extensions=[
            extensions.MultiBaseType(base_types=rare_cards),
            extensions.TierStyle(tier=categories.TIER.RARE),
        ],
    ),
    Rule(
        instruction=extensions.Show(),
        extensions=[
            extensions.MultiBaseType(base_types=common_cards),
            extensions.TierStyle(tier=categories.TIER.COMMON),
        ],
    ),
    Rule(
        instruction=extensions.Show(),
        extensions=[
            extensions.ClassName(class_name="Divination Cards"),
            extensions.TierStyle(tier=categories.TIER.LEGENDARY),
        ],
    ),
]
