ORB_OF_ALTERATION = "Orb of Alteration"
ORB_OF_FUSING = "Orb of Fusing"
ORB_OF_ALCHEMY = "Orb of Alchemy"
CHAOS_ORB = "Chaos Orb"
GEMCUTTERS_PRISM = "Gemcutter's Prism"
EXALTED_ORB = "Exalted Orb"
CHROMATIC_ORB = "Chromatic Orb"
JEWELLERS_ORB = "Jeweller's Orb"
ENGINEERS_ORB = "Engineer's Orb"
INFUSED_ENGINEERS_ORB = "Infused Engineer's Orb"
ORB_OF_CHANCE = "Orb of Chance"
QUANTITY_CHISEL = "Cartographer's Chisel"
RARITY_CHISEL = "Maven's Chisel of Procurement"
PACK_CHISEL = "Maven's Chisel of Proliferation"
SCARAB_CHISEL = "Maven's Chisel of Scarabs"
DIVINATION_CHISEL = "Maven's Chisel of Divination"
CURRENCY_CHISEL = "Maven's Chisel of Avarice"
ORB_OF_SCOURING = "Orb of Scouring"
BLESSED_ORB = "Blessed Orb"
ORB_OF_REGRET = "Orb of Regret"
REGAL_ORB = "Regal Orb"
DIVINE_ORB = "Divine Orb"
VAAL_ORB = "Vaal Orb"
ORB_OF_ANNULMENT = "Orb of Annulment"
ORB_OF_BINDING = "Orb of Binding"
ANCIENT_ORB = "Ancient Orb"
ORB_OF_HORIZONS = "Orb of Horizons"
HARBINGERS_ORB = "Harbinger's Orb"
FRACTURING_ORB = "Fracturing Orb"
SCROLL_OF_WISDOM = "Scroll of Wisdom"
PORTAL_SCROLL = "Portal Scroll"
ARMOURERS_SCRAP = "Armourer's Scrap"
BLACKSMITHS_WHETSTONE = "Blacksmith's Whetstone"
GLASSBLOWERS_BAUBLE = "Glassblower's Bauble"
ORB_OF_TRANSMUTATION = "Orb of Transmutation"
ORB_OF_AUGMENTATION = "Orb of Augmentation"
MIRROR_OF_KALANDRA = "Mirror of Kalandra"
ETERNAL_ORB = "Eternal Orb"
ROGUES_MARKER = "Rogue's Marker"
FACETORS_LENS = "Facetor's Lens"
TEMPERING_ORB = "Tempering Orb"
TAILORING_ORB = "Tailoring Orb"
AWAKENED_SEXTANT = "Awakened Sextant"
ELEVATED_SEXTANT = "Elevated Sextant"
SURVEYORS_COMPASS = "Surveyor's Compass"
ORB_OF_UNMAKING = "Orb of Unmaking"
BLESSING_OF_XOPH = "Blessing of Xoph"
BLESSING_OF_TUL = "Blessing of Tul"
BLESSING_OF_ESH = "Blessing of Esh"
BLESSING_OF_UUL_NETOL = "Blessing of Uul-Netol"
BLESSING_OF_CHAYULA = "Blessing of Chayula"
VEILED_EXALTED_ORB = "Veiled Exalted Orb"
VEILED_CHAOS_ORB = "Veiled Chaos Orb"
ENKINDLING_ORB = "Enkindling Orb"
INSTILLING_ORB = "Instilling Orb"
SACRED_ORB = "Sacred Orb"
STACKED_DECK = "Stacked Deck"
GOLD = "Gold"

CURRENCY = [
    ORB_OF_ALTERATION,
    ORB_OF_FUSING,
    ORB_OF_ALCHEMY,
    CHAOS_ORB,
    GEMCUTTERS_PRISM,
    EXALTED_ORB,
    CHROMATIC_ORB,
    JEWELLERS_ORB,
    ENGINEERS_ORB,
    INFUSED_ENGINEERS_ORB,
    ORB_OF_CHANCE,
    QUANTITY_CHISEL,
    ORB_OF_SCOURING,
    BLESSED_ORB,
    ORB_OF_REGRET,
    REGAL_ORB,
    DIVINE_ORB,
    VAAL_ORB,
    ORB_OF_ANNULMENT,
    ORB_OF_BINDING,
    ANCIENT_ORB,
    ORB_OF_HORIZONS,
    HARBINGERS_ORB,
    FRACTURING_ORB,
    SCROLL_OF_WISDOM,
    PORTAL_SCROLL,
    ARMOURERS_SCRAP,
    BLACKSMITHS_WHETSTONE,
    GLASSBLOWERS_BAUBLE,
    ORB_OF_TRANSMUTATION,
    ORB_OF_AUGMENTATION,
    MIRROR_OF_KALANDRA,
    ETERNAL_ORB,
    ROGUES_MARKER,
    FACETORS_LENS,
    TEMPERING_ORB,
    TAILORING_ORB,
    AWAKENED_SEXTANT,
    ELEVATED_SEXTANT,
    SURVEYORS_COMPASS,
    ORB_OF_UNMAKING,
    BLESSING_OF_XOPH,
    BLESSING_OF_TUL,
    BLESSING_OF_ESH,
    BLESSING_OF_UUL_NETOL,
    BLESSING_OF_CHAYULA,
    VEILED_EXALTED_ORB,
    VEILED_CHAOS_ORB,
    ENKINDLING_ORB,
    INSTILLING_ORB,
    SACRED_ORB,
    STACKED_DECK,
    GOLD,
]

ORB_OF_REMEMBRANCE = "Orb of Remembrance"
ORB_OF_UNRAVELLING = "Orb of Unravelling"
ORB_OF_INTENTION = "Orb of Intention"
SHAPERS_EXALTED_ORB = "Shaper's Exalted Orb"
ELDERS_EXALTED_ORB = "Elder's Exalted Orb"
CRUSADERS_EXALTED_ORB = "Crusader's Exalted Orb"
REDEEMERS_EXALTED_ORB = "Redeemer's Exalted Orb"
HUNTERS_EXALTED_ORB = "Hunter's Exalted Orb"
WARLORDS_EXALTED_ORB = "Warlord's Exalted Orb"
AWAKENERS_ORB = "Awakener's Orb"
ORB_OF_DOMINANCE = "Orb of Dominance"
ELDRITCH_CHAOS_ORB = "Eldritch Chaos Orb"
ELDRITCH_EXALTED_ORB = "Eldritch Exalted Orb"
ELDRITCH_ORB_OF_ANNULMENT = "Eldritch Orb of Annulment"
LESSER_ELDRITCH_EMBER = "Lesser Eldritch Ember"
GREATER_ELDRITCH_EMBER = "Greater Eldritch Ember"
GRAND_ELDRITCH_EMBER = "Grand Eldritch Ember"
EXCEPTIONAL_ELDRITCH_EMBER = "Exceptional Eldritch Ember"
LESSER_ELDRITCH_ICHOR = "Lesser Eldritch Ichor"
GREATER_ELDRITCH_ICHOR = "Greater Eldritch Ichor"
GRAND_ELDRITCH_ICHOR = "Grand Eldritch Ichor"
EXCEPTIONAL_ELDRITCH_ICHOR = "Exceptional Eldritch Ichor"
ORB_OF_CONFLICT = "Orb of Conflict"
TAINTED_CHROMATIC_ORB = "Tainted Chromatic Orb"
TAINTED_ORB_OF_FUSING = "Tainted Orb of Fusing"
TAINTED_JEWELLERS_ORB = "Tainted Jeweller's Orb"
TAINTED_CHAOS_ORB = "Tainted Chaos Orb"
TAINTED_EXALTED_ORB = "Tainted Exalted Orb"
TAINTED_MYTHIC_ORB = "Tainted Mythic Orb"
TAINTED_ARMOURERS_SCRAP = "Tainted Armourer's Scrap"
TAINTED_BLACKSMITHS_WHETSTONE = "Tainted Blacksmith's Whetstone"
TAINTED_DIVINE_TEARDROP = "Tainted Divine Teardrop"
WILD_CRYSTALLISED_LIFEFORCE = "Wild Crystallised Lifeforce"
VIVID_CRYSTALLISED_LIFEFORCE = "Vivid Crystallised Lifeforce"
PRIMAL_CRYSTALLISED_LIFEFORCE = "Primal Crystallised Lifeforce"
SACRED_CRYSTALLISED_LIFEFORCE = "Sacred Crystallised Lifeforce"
HINEKORAS_LOCK = "Hinekora's Lock"

EXOTIC_CURRENCY = [
    ORB_OF_REMEMBRANCE,
    ORB_OF_UNRAVELLING,
    ORB_OF_INTENTION,
    SHAPERS_EXALTED_ORB,
    ELDERS_EXALTED_ORB,
    CRUSADERS_EXALTED_ORB,
    REDEEMERS_EXALTED_ORB,
    HUNTERS_EXALTED_ORB,
    WARLORDS_EXALTED_ORB,
    AWAKENERS_ORB,
    ORB_OF_DOMINANCE,
    ELDRITCH_CHAOS_ORB,
    ELDRITCH_EXALTED_ORB,
    ELDRITCH_ORB_OF_ANNULMENT,
    LESSER_ELDRITCH_EMBER,
    GREATER_ELDRITCH_EMBER,
    GRAND_ELDRITCH_EMBER,
    EXCEPTIONAL_ELDRITCH_EMBER,
    LESSER_ELDRITCH_ICHOR,
    GREATER_ELDRITCH_ICHOR,
    GRAND_ELDRITCH_ICHOR,
    EXCEPTIONAL_ELDRITCH_ICHOR,
    ORB_OF_CONFLICT,
    TAINTED_CHROMATIC_ORB,
    TAINTED_ORB_OF_FUSING,
    TAINTED_JEWELLERS_ORB,
    TAINTED_CHAOS_ORB,
    TAINTED_EXALTED_ORB,
    TAINTED_MYTHIC_ORB,
    TAINTED_ARMOURERS_SCRAP,
    TAINTED_BLACKSMITHS_WHETSTONE,
    TAINTED_DIVINE_TEARDROP,
    WILD_CRYSTALLISED_LIFEFORCE,
    VIVID_CRYSTALLISED_LIFEFORCE,
    PRIMAL_CRYSTALLISED_LIFEFORCE,
    SACRED_CRYSTALLISED_LIFEFORCE,
    HINEKORAS_LOCK,
]

TRANSMUTATION_SHARD = "Transmutation Shard"
ALTERATION_SHARD = "Alteration Shard"
ALCHEMY_SHARD = "Alchemy Shard"
CHAOS_SHARD = "Chaos Shard"
EXALTED_SHARD = "Exalted Shard"
ENGINEERS_SHARD = "Engineer's Shard"
REGAL_SHARD = "Regal Shard"
ANNULMENT_SHARD = "Annulment Shard"
BINDING_SHARD = "Binding Shard"
ANCIENT_SHARD = "Ancient Shard"
HORIZON_SHARD = "Horizon Shard"
HARBINGERS_SHARD = "Harbinger's Shard"
FRACTURING_SHARD = "Fracturing Shard"
MIRROR_SHARD = "Mirror Shard"
SPLINTER_OF_XOPH = "Splinter of Xoph"
SPLINTER_OF_TUL = "Splinter of Tul"
SPLINTER_OF_ESH = "Splinter of Esh"
SPLINTER_OF_UUL_NETOL = "Splinter of Uul-Netol"
SPLINTER_OF_CHAYULA = "Splinter of Chayula"
TIMELESS_ETERNAL_EMPIRE_SPLINTER = "Timeless Eternal Empire Splinter"
TIMELESS_KARUI_SPLINTER = "Timeless Karui Splinter"
TIMELESS_VAAL_SPLINTER = "Timeless Vaal Splinter"
TIMELESS_TEMPLAR_SPLINTER = "Timeless Templar Splinter"
TIMELESS_MARAKETH_SPLINTER = "Timeless Maraketh Splinter"
SIMULACRUM_SPLINTER = "Simulacrum Splinter"
CRESCENT_SPLINTER = "Crescent Splinter"
RITUAL_SPLINTER = "Ritual Splinter"

SHARDS_SPLINTERS = [
    TRANSMUTATION_SHARD,
    ALTERATION_SHARD,
    ALCHEMY_SHARD,
    CHAOS_SHARD,
    EXALTED_SHARD,
    ENGINEERS_SHARD,
    REGAL_SHARD,
    ANNULMENT_SHARD,
    BINDING_SHARD,
    ANCIENT_SHARD,
    HORIZON_SHARD,
    HARBINGERS_SHARD,
    FRACTURING_SHARD,
    MIRROR_SHARD,
    SPLINTER_OF_XOPH,
    SPLINTER_OF_TUL,
    SPLINTER_OF_ESH,
    SPLINTER_OF_UUL_NETOL,
    SPLINTER_OF_CHAYULA,
    TIMELESS_ETERNAL_EMPIRE_SPLINTER,
    TIMELESS_KARUI_SPLINTER,
    TIMELESS_VAAL_SPLINTER,
    TIMELESS_TEMPLAR_SPLINTER,
    TIMELESS_MARAKETH_SPLINTER,
    SIMULACRUM_SPLINTER,
    CRESCENT_SPLINTER,
    RITUAL_SPLINTER,
]

SACRIFICE_AT_DUSK = "Sacrifice at Dusk"
SACRIFICE_AT_MIDNIGHT = "Sacrifice at Midnight"
SACRIFICE_AT_DAWN = "Sacrifice at Dawn"
SACRIFICE_AT_NOON = "Sacrifice at Noon"
MORTAL_GRIEF = "Mortal Grief"
MORTAL_RAGE = "Mortal Rage"
MORTAL_HOPE = "Mortal Hope"
MORTAL_IGNORANCE = "Mortal Ignorance"
FRAGMENT_OF_THE_HYDRA = "Fragment of the Hydra"
FRAGMENT_OF_THE_PHOENIX = "Fragment of the Phoenix"
FRAGMENT_OF_THE_MINOTAUR = "Fragment of the Minotaur"
FRAGMENT_OF_THE_CHIMERA = "Fragment of the Chimera"
FRAGMENT_OF_ENSLAVEMENT = "Fragment of Enslavement"
FRAGMENT_OF_ERADICATION = "Fragment of Eradication"
FRAGMENT_OF_CONSTRICTION = "Fragment of Constriction"
FRAGMENT_OF_PURIFICATION = "Fragment of Purification"
FRAGMENT_OF_TERROR = "Fragment of Terror"
FRAGMENT_OF_EMPTINESS = "Fragment of Emptiness"
FRAGMENT_OF_SHAPE = "Fragment of Shape"
FRAGMENT_OF_KNOWLEDGE = "Fragment of Knowledge"
AL_HEZMINS_CREST = "Al-Hezmin's Crest"
BARANS_CREST = "Baran's Crest"
DROXS_CREST = "Drox's Crest"
VERITANIAS_CREST = "Veritania's Crest"
BEAUTY = "Beauty"
CURIOSITY = "Curiosity"
AMBITION = "Ambition"
COOPERATION = "Cooperation"
OFFERING_TO_THE_GODDESS = "Offering to the Goddess"
TRIBUTE_TO_THE_GODDESS = "Tribute to the Goddess"
GIFT_TO_THE_GODDESS = "Gift to the Goddess"
DEDICATION_TO_THE_GODDESS = "Dedication to the Goddess"
SACRIFICE_SET = "Sacrifice Set"
MORTAL_SET = "Mortal Set"
KEY_TO_THE_CRUCIBLE = "Key to the Crucible"
KEY_TO_DECAY = "Key to Decay"
MADDENING_OBJECT = "Maddening Object"
CREST_OF_THE_ELDERSLAYERS = "Crest of the Elderslayers"
XOPHS_BREACHSTONE = "Xoph's Breachstone"
TULS_BREACHSTONE = "Tul's Breachstone"
ESHS_BREACHSTONE = "Esh's Breachstone"
UUL_NETOLS_BREACHSTONE = "Uul-Netol's Breachstone"
CHAYULAS_BREACHSTONE = "Chayula's Breachstone"
XOPHS_FLAWLESS_BREACHSTONE = "Xoph's Flawless Breachstone"
TULS_FLAWLESS_BREACHSTONE = "Tul's Flawless Breachstone"
ESHS_FLAWLESS_BREACHSTONE = "Esh's Flawless Breachstone"
UUL_NETOLS_FLAWLESS_BREACHSTONE = "Uul-Netol's Flawless Breachstone"
CHAYULAS_FLAWLESS_BREACHSTONE = "Chayula's Flawless Breachstone"
TIMELESS_ETERNAL_EMBLEM = "Timeless Eternal Emblem"
TIMELESS_KARUI_EMBLEM = "Timeless Karui Emblem"
TIMELESS_VAAL_EMBLEM = "Timeless Vaal Emblem"
TIMELESS_TEMPLAR_EMBLEM = "Timeless Templar Emblem"
TIMELESS_MARAKETH_EMBLEM = "Timeless Maraketh Emblem"
UNRELENTING_TIMELESS_ETERNAL_EMBLEM = "Unrelenting Timeless Eternal Emblem"
UNRELENTING_TIMELESS_KARUI_EMBLEM = "Unrelenting Timeless Karui Emblem"
UNRELENTING_TIMELESS_VAAL_EMBLEM = "Unrelenting Timeless Vaal Emblem"
UNRELENTING_TIMELESS_TEMPLAR_EMBLEM = "Unrelenting Timeless Templar Emblem"
UNRELENTING_TIMELESS_MARAKETH_EMBLEM = "Unrelenting Timeless Maraketh Emblem"
SIMULACRUM = "Simulacrum"
SACRED_BLOSSOM = "Sacred Blossom"
RITUAL_VESSEL = "Ritual Vessel"
MAVENS_INVITATION_THE_ATLAS = "Maven's Invitation: The Atlas"
MAVENS_INVITATION_THE_FORMED = "Maven's Invitation: The Formed"
MAVENS_INVITATION_THE_TWISTED = "Maven's Invitation: The Twisted"
MAVENS_INVITATION_THE_FORGOTTEN = "Maven's Invitation: The Forgotten"
MAVENS_INVITATION_THE_HIDDEN = "Maven's Invitation: The Hidden"
MAVENS_INVITATION_THE_FEARED = "Maven's Invitation: The Feared"
MAVENS_INVITATION_THE_ELDERSLAYERS = "Maven's Invitation: The Elderslayers"
ECHO_OF_TRAUMA = "Echo of Trauma"
ECHO_OF_REVERANCE = "Echo of Reverence"
ECHO_OF_LONELINESS = "Echo of Loneliness"
SYNDICATE_MEDALLION = "Syndicate Medallion"
THE_MAVENS_WRIT = "The Maven's Writ"
WRITHING_INVITATION = "Writhing Invitation"
SCREAMING_INVITATION = "Screaming Invitation"
POLARIC_INVITATION = "Polaric Invitation"
INCANDESCENT_INVITATION = "Incandescent Invitation"
ANCIENT_RELIQUARY_KEY = "Ancient Reliquary Key"
TIMEWORN_RELIQUARY_KEY = "Timeworn Reliquary Key"
VAAL_RELIQUARY_KEY = "Vaal Reliquary Key"
FORGOTTEN_RELIQUARY_KEY = "Forgotten Reliquary Key"
VISCERAL_RELIQUARY_KEY = "Visceral Reliquary Key"
SHINY_RELIQUARY_KEY = "Shiny Reliquary Key"
ARCHIVE_RELIQUARY_KEY = "Archive Reliquary Key"
OUBLIETTE_RELIQUARY_KEY = "Oubliette Reliquary Key"
COSMIC_RELIQUARY_KEY = "Cosmic Reliquary Key"
DECAYING_RELIQUARY_KEY = "Decaying Reliquary Key"
VOIDBORN_RELIQUARY_KEY = "Voidborn Reliquary Key"
VALDOS_PUZZLE_BOX = "Valdo's Puzzle Box"
DIVINE_VESSEL = "Divine Vessel"

FRAGMENTS_SETS = [
    SACRIFICE_AT_DUSK,
    SACRIFICE_AT_MIDNIGHT,
    SACRIFICE_AT_DAWN,
    SACRIFICE_AT_NOON,
    MORTAL_GRIEF,
    MORTAL_RAGE,
    MORTAL_HOPE,
    MORTAL_IGNORANCE,
    FRAGMENT_OF_THE_HYDRA,
    FRAGMENT_OF_THE_PHOENIX,
    FRAGMENT_OF_THE_MINOTAUR,
    FRAGMENT_OF_THE_CHIMERA,
    FRAGMENT_OF_ENSLAVEMENT,
    FRAGMENT_OF_ERADICATION,
    FRAGMENT_OF_CONSTRICTION,
    FRAGMENT_OF_PURIFICATION,
    FRAGMENT_OF_TERROR,
    FRAGMENT_OF_EMPTINESS,
    FRAGMENT_OF_SHAPE,
    FRAGMENT_OF_KNOWLEDGE,
    AL_HEZMINS_CREST,
    BARANS_CREST,
    DROXS_CREST,
    VERITANIAS_CREST,
    BEAUTY,
    CURIOSITY,
    AMBITION,
    COOPERATION,
    OFFERING_TO_THE_GODDESS,
    TRIBUTE_TO_THE_GODDESS,
    GIFT_TO_THE_GODDESS,
    DEDICATION_TO_THE_GODDESS,
    SACRIFICE_SET,
    MORTAL_SET,
    KEY_TO_THE_CRUCIBLE,
    KEY_TO_DECAY,
    MADDENING_OBJECT,
    CREST_OF_THE_ELDERSLAYERS,
    XOPHS_BREACHSTONE,
    TULS_BREACHSTONE,
    ESHS_BREACHSTONE,
    UUL_NETOLS_BREACHSTONE,
    CHAYULAS_BREACHSTONE,
    XOPHS_FLAWLESS_BREACHSTONE,
    TULS_FLAWLESS_BREACHSTONE,
    ESHS_FLAWLESS_BREACHSTONE,
    UUL_NETOLS_FLAWLESS_BREACHSTONE,
    CHAYULAS_FLAWLESS_BREACHSTONE,
    TIMELESS_ETERNAL_EMBLEM,
    TIMELESS_KARUI_EMBLEM,
    TIMELESS_VAAL_EMBLEM,
    TIMELESS_TEMPLAR_EMBLEM,
    TIMELESS_MARAKETH_EMBLEM,
    UNRELENTING_TIMELESS_ETERNAL_EMBLEM,
    UNRELENTING_TIMELESS_KARUI_EMBLEM,
    UNRELENTING_TIMELESS_VAAL_EMBLEM,
    UNRELENTING_TIMELESS_TEMPLAR_EMBLEM,
    UNRELENTING_TIMELESS_MARAKETH_EMBLEM,
    SIMULACRUM,
    SACRED_BLOSSOM,
    RITUAL_VESSEL,
    MAVENS_INVITATION_THE_ATLAS,
    MAVENS_INVITATION_THE_FORMED,
    MAVENS_INVITATION_THE_TWISTED,
    MAVENS_INVITATION_THE_FORGOTTEN,
    MAVENS_INVITATION_THE_HIDDEN,
    MAVENS_INVITATION_THE_FEARED,
    MAVENS_INVITATION_THE_ELDERSLAYERS,
    ECHO_OF_TRAUMA,
    ECHO_OF_REVERANCE,
    ECHO_OF_LONELINESS,
    SYNDICATE_MEDALLION,
    THE_MAVENS_WRIT,
    WRITHING_INVITATION,
    SCREAMING_INVITATION,
    POLARIC_INVITATION,
    INCANDESCENT_INVITATION,
    ANCIENT_RELIQUARY_KEY,
    TIMEWORN_RELIQUARY_KEY,
    VAAL_RELIQUARY_KEY,
    FORGOTTEN_RELIQUARY_KEY,
    VISCERAL_RELIQUARY_KEY,
    SHINY_RELIQUARY_KEY,
    ARCHIVE_RELIQUARY_KEY,
    OUBLIETTE_RELIQUARY_KEY,
    COSMIC_RELIQUARY_KEY,
    DECAYING_RELIQUARY_KEY,
    VOIDBORN_RELIQUARY_KEY,
    VALDOS_PUZZLE_BOX,
    DIVINE_VESSEL,
]

OMEN_OF_AMELIORATION = "Omen of Amelioration"
OMEN_OF_RETURN = "Omen of Return"
OMEN_OF_DEATH_DANCING = "Omen of Death-dancing"
OMEN_OF_REFRESHMENT = "Omen of Refreshment"
OMEN_OF_THE_SOUL_DEVOURER = "Omen of the Soul Devourer"
OMEN_OF_FORTUNE = "Omen of Fortune"
OMEN_OF_THE_JEWELLER = "Omen of the Jeweller"
OMEN_OF_CONNECTIONS = "Omen of Connections"
OMEN_OF_BLANCHING = "Omen of Blanching"
OMEN_OF_ADRENALINE = "Omen of Adrenaline"
OMEN_OF_DEATHS_DOOR = "Omen of Death's Door"
OMEN_OF_BRILLIANCE = "Omen of Brilliance"

OMENS = [
    OMEN_OF_AMELIORATION,
    OMEN_OF_RETURN,
    OMEN_OF_DEATH_DANCING,
    OMEN_OF_REFRESHMENT,
    OMEN_OF_THE_SOUL_DEVOURER,
    OMEN_OF_FORTUNE,
    OMEN_OF_THE_JEWELLER,
    OMEN_OF_CONNECTIONS,
    OMEN_OF_BLANCHING,
    OMEN_OF_ADRENALINE,
    OMEN_OF_DEATHS_DOOR,
    OMEN_OF_BRILLIANCE,
]

FORBIDDEN_TOME = "Forbidden Tome"
THE_HOUR_OF_DIVINITY = "The Hour of Divinity"
THE_GILDED_CHALICE = "The Gilded Chalice"
THE_SECOND_SACRAMENT = "The Second Sacrament"
THE_NIGHT_LAMP = "The Night Lamp"
THE_FIRST_CREST = "The First Crest"
THE_BROKEN_CENSER = "The Broken Censer"
THE_ORIGINAL_SCRIPTURE = "The Original Scripture"
THE_BLOOD_OF_INNOCENCE = "The Blood of Innocence"
THE_CHAINS_OF_CASTIGATION = "The Chains of Castigation"
THE_POWER_AND_THE_PROMISE = "The Power and the Promise"

SANCTUM_UNIQUE_RELICS = [
    FORBIDDEN_TOME,
    THE_HOUR_OF_DIVINITY,
    THE_GILDED_CHALICE,
    THE_SECOND_SACRAMENT,
    THE_NIGHT_LAMP,
    THE_FIRST_CREST,
    THE_BROKEN_CENSER,
    THE_ORIGINAL_SCRIPTURE,
    THE_BLOOD_OF_INNOCENCE,
    THE_CHAINS_OF_CASTIGATION,
    THE_POWER_AND_THE_PROMISE,
]

SINGULAR_SCOUTING_REPORT = "Singular Scouting Report"
OTHERWORLDLY_SCOUTING_REPORT = "Otherworldly Scouting Report"
COMPREHENSIVE_SCOUTING_REPORT = "Comprehensive Scouting Report"
VAAL_SCOUTING_REPORT = "Vaal Scouting Report"
DELIRIOUS_SCOUTING_REPORT = "Delirious Scouting Report"
OPERATIVES_SCOUTING_REPORT = "Operative's Scouting Report"
BLIGHTED_SCOUTING_REPORT = "Blighted Scouting Report"
INFLUENCED_SCOUTING_REPORT = "Influenced Scouting Report"
EXPLORERS_SCOUTING_REPORT = "Explorer's Scouting Report"

SCOUTING_REPORTS = [
    SINGULAR_SCOUTING_REPORT,
    OTHERWORLDLY_SCOUTING_REPORT,
    COMPREHENSIVE_SCOUTING_REPORT,
    VAAL_SCOUTING_REPORT,
    DELIRIOUS_SCOUTING_REPORT,
    OPERATIVES_SCOUTING_REPORT,
    BLIGHTED_SCOUTING_REPORT,
    INFLUENCED_SCOUTING_REPORT,
    EXPLORERS_SCOUTING_REPORT,
]

ASTRAGALI = "Astragali"
EXOTIC_COINAGE = "Exotic Coinage"
SCRAP_METAL = "Scrap Metal"
BURIAL_MEDALLION = "Burial Medallion"

EXPEDITION_CURRENCY = [
    ASTRAGALI,
    EXOTIC_COINAGE,
    SCRAP_METAL,
    BURIAL_MEDALLION,
]

FINE_DELIRIUM_ORB = "Fine Delirium Orb"
SINGULAR_DELIRIUM_ORB = "Singular Delirium Orb"
THAUMATURGES_DELIRIUM_ORB = "Thaumaturge's Delirium Orb"
BLACKSMITHS_DELIRIUM_ORB = "Blacksmith's Delirium Orb"
ARMOURSMITHS_DELIRIUM_ORB = "Armoursmith's Delirium Orb"
CARTOGRAPHERS_DELIRIUM_ORB = "Cartographer's Delirium Orb"
JEWELLERS_DELIRIUM_ORB = "Jeweller's Delirium Orb"
ABYSSAL_DELIRIUM_ORB = "Abyssal Delirium Orb"
KALGUURAN_DELIRIUM_ORB = "Kalguuran Delirium Orb"
FOREBODING_DELIRIUM_ORB = "Foreboding Delirium Orb"
OBSCURED_DELIRIUM_ORB = "Obscured Delirium Orb"
WHISPERING_DELIRIUM_ORB = "Whispering Delirium Orb"
FRAGMENTED_DELIRIUM_ORB = "Fragmented Delirium Orb"
SKITTERING_DELIRIUM_ORB = "Skittering Delirium Orb"
FOSSILISED_DELIRIUM_ORB = "Fossilised Delirium Orb"
DIVINERS_DELIRIUM_ORB = "Diviner's Delirium Orb"
DELIRIUM_ORB = "Delirium Orb"
PRIMAL_DELIRIUM_ORB = "Primal Delirium Orb"
TIMELESS_DELIRIUM_ORB = "Timeless Delirium Orb"
BLIGHTED_DELIRIUM_ORB = "Blighted Delirium Orb"
CHALLENGING_DELIRIUM_ORB = "Challenging Delirium Orb"

DELIRIUM_ORBS = [
    FINE_DELIRIUM_ORB,
    SINGULAR_DELIRIUM_ORB,
    THAUMATURGES_DELIRIUM_ORB,
    BLACKSMITHS_DELIRIUM_ORB,
    ARMOURSMITHS_DELIRIUM_ORB,
    CARTOGRAPHERS_DELIRIUM_ORB,
    JEWELLERS_DELIRIUM_ORB,
    ABYSSAL_DELIRIUM_ORB,
    KALGUURAN_DELIRIUM_ORB,
    FOREBODING_DELIRIUM_ORB,
    OBSCURED_DELIRIUM_ORB,
    WHISPERING_DELIRIUM_ORB,
    FRAGMENTED_DELIRIUM_ORB,
    SKITTERING_DELIRIUM_ORB,
    FOSSILISED_DELIRIUM_ORB,
    DIVINERS_DELIRIUM_ORB,
    DELIRIUM_ORB,
    PRIMAL_DELIRIUM_ORB,
    TIMELESS_DELIRIUM_ORB,
    BLIGHTED_DELIRIUM_ORB,
    CHALLENGING_DELIRIUM_ORB,
]

TURBULENT_CATALYST = "Turbulent Catalyst"
IMBUED_CATALYST = "Imbued Catalyst"
ABRASIVE_CATALYST = "Abrasive Catalyst"
TEMPERING_CATALYST = "Tempering Catalyst"
FERTILE_CATALYST = "Fertile Catalyst"
PRISMATIC_CATALYST = "Prismatic Catalyst"
INTRINSIC_CATALYST = "Intrinsic Catalyst"
NOXIOUS_CATALYST = "Noxious Catalyst"
ACCELERATING_CATALYST = "Accelerating Catalyst"
UNSTABLE_CATALYST = "Unstable Catalyst"
TAINTED_CATALYST = "Tainted Catalyst"

CATALYSTS = [
    TURBULENT_CATALYST,
    IMBUED_CATALYST,
    ABRASIVE_CATALYST,
    TEMPERING_CATALYST,
    FERTILE_CATALYST,
    PRISMATIC_CATALYST,
    INTRINSIC_CATALYST,
    NOXIOUS_CATALYST,
    ACCELERATING_CATALYST,
    UNSTABLE_CATALYST,
    TAINTED_CATALYST,
]

CLEAR_OIL = "Clear Oil"
SEPIA_OIL = "Sepia Oil"
AMBER_OIL = "Amber Oil"
VERDANT_OIL = "Verdant Oil"
TEAL_OIL = "Teal Oil"
AZURE_OIL = "Azure Oil"
INDIGO_OIL = "Indigo Oil"
VIOLET_OIL = "Violet Oil"
CRIMSON_OIL = "Crimson Oil"
BLACK_OIL = "Black Oil"
OPALESCENT_OIL = "Opalescent Oil"
SILVER_OIL = "Silver Oil"
GOLDEN_OIL = "Golden Oil"
TAINTED_OIL = "Tainted Oil"
REFLECTIVE_OIL = "Reflective Oil"
OIL_EXTRACTOR = "Oil Extractor"

OILS_EXTRACTOR = [
    CLEAR_OIL,
    SEPIA_OIL,
    AMBER_OIL,
    VERDANT_OIL,
    TEAL_OIL,
    AZURE_OIL,
    INDIGO_OIL,
    VIOLET_OIL,
    CRIMSON_OIL,
    BLACK_OIL,
    OPALESCENT_OIL,
    SILVER_OIL,
    GOLDEN_OIL,
    TAINTED_OIL,
    REFLECTIVE_OIL,
    OIL_EXTRACTOR,
]

WHISPERING_INCUBATOR = "Whispering Incubator"
FINE_INCUBATOR = "Fine Incubator"
SINGULAR_INCUBATOR = "Singular Incubator"
CARTOGRAPHERS_INCUBATOR = "Cartographer's Incubator"
OTHERWORLDLY_INCUBATOR = "Otherworldly Incubator"
ABYSSAL_INCUBATOR = "Abyssal Incubator"
FRAGMENTED_INCUBATOR = "Fragmented Incubator"
SKITTERING_INCUBATOR = "Skittering Incubator"
INFUSED_INCUBATOR = "Infused Incubator"
FOSSILISED_INCUBATOR = "Fossilised Incubator"
KALGUURAN_INCUBATOR = "Kalguuran Incubator"
DIVINERS_INCUBATOR = "Diviner's Incubator"
PRIMAL_INCUBATOR = "Primal Incubator"
ENCHANTED_INCUBATOR = "Enchanted Incubator"
GEOMANCERS_INCUBATOR = "Geomancer's Incubator"
ORNATE_INCUBATOR = "Ornate Incubator"
TIME_LOST_INCUBATOR = "Time-Lost Incubator"
CELESTIAL_ARMOURSMITHS_INCUBATOR = "Celestial Armoursmith's Incubator"
CELESTIAL_BLACKSMITHS_INCUBATOR = "Celestial Blacksmith's Incubator"
CELESTIAL_JEWELLERS_INCUBATOR = "Celestial Jeweller's Incubator"
ELDRITCH_INCUBATOR = "Eldritch Incubator"
OBSCURED_INCUBATOR = "Obscured Incubator"
FOREBODING_INCUBATOR = "Foreboding Incubator"
THAUMATURGES_INCUBATOR = "Thaumaturge's Incubator"
MYSTERIOUS_INCUBATOR = "Mysterious Incubator"
GEMCUTTERS_INCUBATOR = "Gemcutter's Incubator"
FERAL_INCUBATOR = "Feral Incubator"
BLIGHTED_INCUBATOR = "Blighted Incubator"
CHALLENGING_INCUBATOR = "Challenging Incubator"
MADDENING_INCUBATOR = "Maddening Incubator"

INCUBATORS = [
    WHISPERING_INCUBATOR,
    FINE_INCUBATOR,
    SINGULAR_INCUBATOR,
    CARTOGRAPHERS_INCUBATOR,
    OTHERWORLDLY_INCUBATOR,
    ABYSSAL_INCUBATOR,
    FRAGMENTED_INCUBATOR,
    SKITTERING_INCUBATOR,
    INFUSED_INCUBATOR,
    FOSSILISED_INCUBATOR,
    KALGUURAN_INCUBATOR,
    DIVINERS_INCUBATOR,
    PRIMAL_INCUBATOR,
    ENCHANTED_INCUBATOR,
    GEOMANCERS_INCUBATOR,
    ORNATE_INCUBATOR,
    TIME_LOST_INCUBATOR,
    CELESTIAL_ARMOURSMITHS_INCUBATOR,
    CELESTIAL_BLACKSMITHS_INCUBATOR,
    CELESTIAL_JEWELLERS_INCUBATOR,
    ELDRITCH_INCUBATOR,
    OBSCURED_INCUBATOR,
    FOREBODING_INCUBATOR,
    THAUMATURGES_INCUBATOR,
    MYSTERIOUS_INCUBATOR,
    GEMCUTTERS_INCUBATOR,
    FERAL_INCUBATOR,
    BLIGHTED_INCUBATOR,
    CHALLENGING_INCUBATOR,
    MADDENING_INCUBATOR,
]

PRIMITIVE_CHAOTIC_RESONATOR = "Primitive Chaotic Resonator"
POTENT_CHAOTIC_RESONATOR = "Potent Chaotic Resonator"
POWERFUL_CHAOTIC_RESONATOR = "Powerful Chaotic Resonator"
PRIME_CHAOTIC_RESONATOR = "Prime Chaotic Resonator"

DELVE_RESONATORS = [
    PRIMITIVE_CHAOTIC_RESONATOR,
    POTENT_CHAOTIC_RESONATOR,
    POWERFUL_CHAOTIC_RESONATOR,
    PRIME_CHAOTIC_RESONATOR,
]

SCORCHED_FOSSIL = "Scorched Fossil"
FRIGID_FOSSIL = "Frigid Fossil"
METALLIC_FOSSIL = "Metallic Fossil"
JAGGED_FOSSIL = "Jagged Fossil"
ABERRANT_FOSSIL = "Aberrant Fossil"
PRISTINE_FOSSIL = "Pristine Fossil"
DENSE_FOSSIL = "Dense Fossil"
CORRODED_FOSSIL = "Corroded Fossil"
PRISMATIC_FOSSIL = "Prismatic Fossil"
AETHERIC_FOSSIL = "Aetheric Fossil"
SERRATED_FOSSIL = "Serrated Fossil"
LUCENT_FOSSIL = "Lucent Fossil"
SHUDDERING_FOSSIL = "Shuddering Fossil"
BOUND_FOSSIL = "Bound Fossil"
# PERFECT_FOSSIL = "Perfect Fossil"
DEFT_FOSSIL = "Deft Fossil"
FUNDAMENTAL_FOSSIL = "Fundamental Fossil"
FACETED_FOSSIL = "Faceted Fossil"
BLOODSTAINED_FOSSIL = "Bloodstained Fossil"
HOLLOW_FOSSIL = "Hollow Fossil"
FRACTURED_FOSSIL = "Fractured Fossil"
GLYPHIC_FOSSIL = "Glyphic Fossil"
TANGLED_FOSSIL = "Tangled Fossil"
SANCTIFIED_FOSSIL = "Sanctified Fossil"
GILDED_FOSSIL = "Gilded Fossil"

DELVE_FOSSILS = [
    SCORCHED_FOSSIL,
    FRIGID_FOSSIL,
    METALLIC_FOSSIL,
    JAGGED_FOSSIL,
    ABERRANT_FOSSIL,
    PRISTINE_FOSSIL,
    DENSE_FOSSIL,
    CORRODED_FOSSIL,
    PRISMATIC_FOSSIL,
    AETHERIC_FOSSIL,
    SERRATED_FOSSIL,
    LUCENT_FOSSIL,
    SHUDDERING_FOSSIL,
    BOUND_FOSSIL,
    # PERFECT_FOSSIL,
    DEFT_FOSSIL,
    FUNDAMENTAL_FOSSIL,
    FACETED_FOSSIL,
    BLOODSTAINED_FOSSIL,
    HOLLOW_FOSSIL,
    FRACTURED_FOSSIL,
    GLYPHIC_FOSSIL,
    TANGLED_FOSSIL,
    SANCTIFIED_FOSSIL,
    GILDED_FOSSIL,
]

WHISPERING_ESSENCE_OF_HATRED = "Whispering Essence of Hatred"
MUTTERING_ESSENCE_OF_HATRED = "Muttering Essence of Hatred"
WEEPING_ESSENCE_OF_HATRED = "Weeping Essence of Hatred"
WAILING_ESSENCE_OF_HATRED = "Wailing Essence of Hatred"
SCREAMING_ESSENCE_OF_HATRED = "Screaming Essence of Hatred"
SHRIEKING_ESSENCE_OF_HATRED = "Shrieking Essence of Hatred"
DEAFENING_ESSENCE_OF_HATRED = "Deafening Essence of Hatred"
WHISPERING_ESSENCE_OF_WOE = "Whispering Essence of Woe"
MUTTERING_ESSENCE_OF_WOE = "Muttering Essence of Woe"
WEEPING_ESSENCE_OF_WOE = "Weeping Essence of Woe"
WAILING_ESSENCE_OF_WOE = "Wailing Essence of Woe"
SCREAMING_ESSENCE_OF_WOE = "Screaming Essence of Woe"
SHRIEKING_ESSENCE_OF_WOE = "Shrieking Essence of Woe"
DEAFENING_ESSENCE_OF_WOE = "Deafening Essence of Woe"
WHISPERING_ESSENCE_OF_GREED = "Whispering Essence of Greed"
MUTTERING_ESSENCE_OF_GREED = "Muttering Essence of Greed"
WEEPING_ESSENCE_OF_GREED = "Weeping Essence of Greed"
WAILING_ESSENCE_OF_GREED = "Wailing Essence of Greed"
SCREAMING_ESSENCE_OF_GREED = "Screaming Essence of Greed"
SHRIEKING_ESSENCE_OF_GREED = "Shrieking Essence of Greed"
DEAFENING_ESSENCE_OF_GREED = "Deafening Essence of Greed"
WHISPERING_ESSENCE_OF_CONTEMPT = "Whispering Essence of Contempt"
MUTTERING_ESSENCE_OF_CONTEMPT = "Muttering Essence of Contempt"
WEEPING_ESSENCE_OF_CONTEMPT = "Weeping Essence of Contempt"
WAILING_ESSENCE_OF_CONTEMPT = "Wailing Essence of Contempt"
SCREAMING_ESSENCE_OF_CONTEMPT = "Screaming Essence of Contempt"
SHRIEKING_ESSENCE_OF_CONTEMPT = "Shrieking Essence of Contempt"
DEAFENING_ESSENCE_OF_CONTEMPT = "Deafening Essence of Contempt"
MUTTERING_ESSENCE_OF_SORROW = "Muttering Essence of Sorrow"
WEEPING_ESSENCE_OF_SORROW = "Weeping Essence of Sorrow"
WAILING_ESSENCE_OF_SORROW = "Wailing Essence of Sorrow"
SCREAMING_ESSENCE_OF_SORROW = "Screaming Essence of Sorrow"
SHRIEKING_ESSENCE_OF_SORROW = "Shrieking Essence of Sorrow"
DEAFENING_ESSENCE_OF_SORROW = "Deafening Essence of Sorrow"
MUTTERING_ESSENCE_OF_ANGER = "Muttering Essence of Anger"
WEEPING_ESSENCE_OF_ANGER = "Weeping Essence of Anger"
WAILING_ESSENCE_OF_ANGER = "Wailing Essence of Anger"
SCREAMING_ESSENCE_OF_ANGER = "Screaming Essence of Anger"
SHRIEKING_ESSENCE_OF_ANGER = "Shrieking Essence of Anger"
DEAFENING_ESSENCE_OF_ANGER = "Deafening Essence of Anger"
MUTTERING_ESSENCE_OF_TORMENT = "Muttering Essence of Torment"
WEEPING_ESSENCE_OF_TORMENT = "Weeping Essence of Torment"
WAILING_ESSENCE_OF_TORMENT = "Wailing Essence of Torment"
SCREAMING_ESSENCE_OF_TORMENT = "Screaming Essence of Torment"
SHRIEKING_ESSENCE_OF_TORMENT = "Shrieking Essence of Torment"
DEAFENING_ESSENCE_OF_TORMENT = "Deafening Essence of Torment"
MUTTERING_ESSENCE_OF_FEAR = "Muttering Essence of Fear"
WEEPING_ESSENCE_OF_FEAR = "Weeping Essence of Fear"
WAILING_ESSENCE_OF_FEAR = "Wailing Essence of Fear"
SCREAMING_ESSENCE_OF_FEAR = "Screaming Essence of Fear"
SHRIEKING_ESSENCE_OF_FEAR = "Shrieking Essence of Fear"
DEAFENING_ESSENCE_OF_FEAR = "Deafening Essence of Fear"
WEEPING_ESSENCE_OF_SUFFERING = "Weeping Essence of Suffering"
WAILING_ESSENCE_OF_SUFFERING = "Wailing Essence of Suffering"
SCREAMING_ESSENCE_OF_SUFFERING = "Screaming Essence of Suffering"
SHRIEKING_ESSENCE_OF_SUFFERING = "Shrieking Essence of Suffering"
DEAFENING_ESSENCE_OF_SUFFERING = "Deafening Essence of Suffering"
WEEPING_ESSENCE_OF_RAGE = "Weeping Essence of Rage"
WAILING_ESSENCE_OF_RAGE = "Wailing Essence of Rage"
SCREAMING_ESSENCE_OF_RAGE = "Screaming Essence of Rage"
SHRIEKING_ESSENCE_OF_RAGE = "Shrieking Essence of Rage"
DEAFENING_ESSENCE_OF_RAGE = "Deafening Essence of Rage"
WEEPING_ESSENCE_OF_WRATH = "Weeping Essence of Wrath"
WAILING_ESSENCE_OF_WRATH = "Wailing Essence of Wrath"
SCREAMING_ESSENCE_OF_WRATH = "Screaming Essence of Wrath"
SHRIEKING_ESSENCE_OF_WRATH = "Shrieking Essence of Wrath"
DEAFENING_ESSENCE_OF_WRATH = "Deafening Essence of Wrath"
WEEPING_ESSENCE_OF_DOUBT = "Weeping Essence of Doubt"
WAILING_ESSENCE_OF_DOUBT = "Wailing Essence of Doubt"
SCREAMING_ESSENCE_OF_DOUBT = "Screaming Essence of Doubt"
SHRIEKING_ESSENCE_OF_DOUBT = "Shrieking Essence of Doubt"
DEAFENING_ESSENCE_OF_DOUBT = "Deafening Essence of Doubt"
WAILING_ESSENCE_OF_ANGUISH = "Wailing Essence of Anguish"
SCREAMING_ESSENCE_OF_ANGUISH = "Screaming Essence of Anguish"
SHRIEKING_ESSENCE_OF_ANGUISH = "Shrieking Essence of Anguish"
DEAFENING_ESSENCE_OF_ANGUISH = "Deafening Essence of Anguish"
WAILING_ESSENCE_OF_LOATHING = "Wailing Essence of Loathing"
SCREAMING_ESSENCE_OF_LOATHING = "Screaming Essence of Loathing"
SHRIEKING_ESSENCE_OF_LOATHING = "Shrieking Essence of Loathing"
DEAFENING_ESSENCE_OF_LOATHING = "Deafening Essence of Loathing"
WAILING_ESSENCE_OF_SPITE = "Wailing Essence of Spite"
SCREAMING_ESSENCE_OF_SPITE = "Screaming Essence of Spite"
SHRIEKING_ESSENCE_OF_SPITE = "Shrieking Essence of Spite"
DEAFENING_ESSENCE_OF_SPITE = "Deafening Essence of Spite"
WAILING_ESSENCE_OF_ZEAL = "Wailing Essence of Zeal"
SCREAMING_ESSENCE_OF_ZEAL = "Screaming Essence of Zeal"
SHRIEKING_ESSENCE_OF_ZEAL = "Shrieking Essence of Zeal"
DEAFENING_ESSENCE_OF_ZEAL = "Deafening Essence of Zeal"
SCREAMING_ESSENCE_OF_MISERY = "Screaming Essence of Misery"
SHRIEKING_ESSENCE_OF_MISERY = "Shrieking Essence of Misery"
DEAFENING_ESSENCE_OF_MISERY = "Deafening Essence of Misery"
SCREAMING_ESSENCE_OF_DREAD = "Screaming Essence of Dread"
SHRIEKING_ESSENCE_OF_DREAD = "Shrieking Essence of Dread"
DEAFENING_ESSENCE_OF_DREAD = "Deafening Essence of Dread"
SCREAMING_ESSENCE_OF_SCORN = "Screaming Essence of Scorn"
SHRIEKING_ESSENCE_OF_SCORN = "Shrieking Essence of Scorn"
DEAFENING_ESSENCE_OF_SCORN = "Deafening Essence of Scorn"
SCREAMING_ESSENCE_OF_ENVY = "Screaming Essence of Envy"
SHRIEKING_ESSENCE_OF_ENVY = "Shrieking Essence of Envy"
DEAFENING_ESSENCE_OF_ENVY = "Deafening Essence of Envy"
ESSENCE_OF_HYSTERIA = "Essence of Hysteria"
ESSENCE_OF_INSANITY = "Essence of Insanity"
ESSENCE_OF_HORROR = "Essence of Horror"
ESSENCE_OF_DELIRIUM = "Essence of Delirium"
REMNANT_OF_CORRUPTION = "Remnant of Corruption"

ESSENCES = [
    WHISPERING_ESSENCE_OF_HATRED,
    MUTTERING_ESSENCE_OF_HATRED,
    WEEPING_ESSENCE_OF_HATRED,
    WAILING_ESSENCE_OF_HATRED,
    SCREAMING_ESSENCE_OF_HATRED,
    SHRIEKING_ESSENCE_OF_HATRED,
    DEAFENING_ESSENCE_OF_HATRED,
    WHISPERING_ESSENCE_OF_WOE,
    MUTTERING_ESSENCE_OF_WOE,
    WEEPING_ESSENCE_OF_WOE,
    WAILING_ESSENCE_OF_WOE,
    SCREAMING_ESSENCE_OF_WOE,
    SHRIEKING_ESSENCE_OF_WOE,
    DEAFENING_ESSENCE_OF_WOE,
    WHISPERING_ESSENCE_OF_GREED,
    MUTTERING_ESSENCE_OF_GREED,
    WEEPING_ESSENCE_OF_GREED,
    WAILING_ESSENCE_OF_GREED,
    SCREAMING_ESSENCE_OF_GREED,
    SHRIEKING_ESSENCE_OF_GREED,
    DEAFENING_ESSENCE_OF_GREED,
    WHISPERING_ESSENCE_OF_CONTEMPT,
    MUTTERING_ESSENCE_OF_CONTEMPT,
    WEEPING_ESSENCE_OF_CONTEMPT,
    WAILING_ESSENCE_OF_CONTEMPT,
    SCREAMING_ESSENCE_OF_CONTEMPT,
    SHRIEKING_ESSENCE_OF_CONTEMPT,
    DEAFENING_ESSENCE_OF_CONTEMPT,
    MUTTERING_ESSENCE_OF_SORROW,
    WEEPING_ESSENCE_OF_SORROW,
    WAILING_ESSENCE_OF_SORROW,
    SCREAMING_ESSENCE_OF_SORROW,
    SHRIEKING_ESSENCE_OF_SORROW,
    DEAFENING_ESSENCE_OF_SORROW,
    MUTTERING_ESSENCE_OF_ANGER,
    WEEPING_ESSENCE_OF_ANGER,
    WAILING_ESSENCE_OF_ANGER,
    SCREAMING_ESSENCE_OF_ANGER,
    SHRIEKING_ESSENCE_OF_ANGER,
    DEAFENING_ESSENCE_OF_ANGER,
    MUTTERING_ESSENCE_OF_TORMENT,
    WEEPING_ESSENCE_OF_TORMENT,
    WAILING_ESSENCE_OF_TORMENT,
    SCREAMING_ESSENCE_OF_TORMENT,
    SHRIEKING_ESSENCE_OF_TORMENT,
    DEAFENING_ESSENCE_OF_TORMENT,
    MUTTERING_ESSENCE_OF_FEAR,
    WEEPING_ESSENCE_OF_FEAR,
    WAILING_ESSENCE_OF_FEAR,
    SCREAMING_ESSENCE_OF_FEAR,
    SHRIEKING_ESSENCE_OF_FEAR,
    DEAFENING_ESSENCE_OF_FEAR,
    WEEPING_ESSENCE_OF_SUFFERING,
    WAILING_ESSENCE_OF_SUFFERING,
    SCREAMING_ESSENCE_OF_SUFFERING,
    SHRIEKING_ESSENCE_OF_SUFFERING,
    DEAFENING_ESSENCE_OF_SUFFERING,
    WEEPING_ESSENCE_OF_RAGE,
    WAILING_ESSENCE_OF_RAGE,
    SCREAMING_ESSENCE_OF_RAGE,
    SHRIEKING_ESSENCE_OF_RAGE,
    DEAFENING_ESSENCE_OF_RAGE,
    WEEPING_ESSENCE_OF_WRATH,
    WAILING_ESSENCE_OF_WRATH,
    SCREAMING_ESSENCE_OF_WRATH,
    SHRIEKING_ESSENCE_OF_WRATH,
    DEAFENING_ESSENCE_OF_WRATH,
    WEEPING_ESSENCE_OF_DOUBT,
    WAILING_ESSENCE_OF_DOUBT,
    SCREAMING_ESSENCE_OF_DOUBT,
    SHRIEKING_ESSENCE_OF_DOUBT,
    DEAFENING_ESSENCE_OF_DOUBT,
    WAILING_ESSENCE_OF_ANGUISH,
    SCREAMING_ESSENCE_OF_ANGUISH,
    SHRIEKING_ESSENCE_OF_ANGUISH,
    DEAFENING_ESSENCE_OF_ANGUISH,
    WAILING_ESSENCE_OF_LOATHING,
    SCREAMING_ESSENCE_OF_LOATHING,
    SHRIEKING_ESSENCE_OF_LOATHING,
    DEAFENING_ESSENCE_OF_LOATHING,
    WAILING_ESSENCE_OF_SPITE,
    SCREAMING_ESSENCE_OF_SPITE,
    SHRIEKING_ESSENCE_OF_SPITE,
    DEAFENING_ESSENCE_OF_SPITE,
    WAILING_ESSENCE_OF_ZEAL,
    SCREAMING_ESSENCE_OF_ZEAL,
    SHRIEKING_ESSENCE_OF_ZEAL,
    DEAFENING_ESSENCE_OF_ZEAL,
    SCREAMING_ESSENCE_OF_MISERY,
    SHRIEKING_ESSENCE_OF_MISERY,
    DEAFENING_ESSENCE_OF_MISERY,
    SCREAMING_ESSENCE_OF_DREAD,
    SHRIEKING_ESSENCE_OF_DREAD,
    DEAFENING_ESSENCE_OF_DREAD,
    SCREAMING_ESSENCE_OF_SCORN,
    SHRIEKING_ESSENCE_OF_SCORN,
    DEAFENING_ESSENCE_OF_SCORN,
    SCREAMING_ESSENCE_OF_ENVY,
    SHRIEKING_ESSENCE_OF_ENVY,
    DEAFENING_ESSENCE_OF_ENVY,
    ESSENCE_OF_HYSTERIA,
    ESSENCE_OF_INSANITY,
    ESSENCE_OF_HORROR,
    ESSENCE_OF_DELIRIUM,
    REMNANT_OF_CORRUPTION,
]

STONE_OF_PASSAGE = "Stone of Passage"
CHRONICLE_OF_ATZOATL = "Chronicle of Atzoatl"


SYNTHESISING_FRAGMENT = "Synthesising Fragment"
DEVOURING_FRAGMENT = "Devouring Fragment"
BLAZING_FRAGMENT = "Blazing Fragment"
REALITY_FRAGMENT = "Reality Fragment"
COSMIC_FRAGMENT = "Cosmic Fragment"
AWAKENING_FRAGMENT = "Awakening Fragment"
DECAYING_FRAGMENT = "Decaying Fragment"

UBER_FRAGMENTS = [
    SYNTHESISING_FRAGMENT,
    DEVOURING_FRAGMENT,
    BLAZING_FRAGMENT,
    REALITY_FRAGMENT,
    COSMIC_FRAGMENT,
    AWAKENING_FRAGMENT,
    DECAYING_FRAGMENT,
]

RELIQUARY_SCARAB = "Reliquary Scarab"
RELIQUARY_SCARAB_OF_OVERLORDS = "Reliquary Scarab of Overlords"
RELIQUARY_SCARAB_OF_VISION = "Reliquary Scarab of Vision"
SULPHITE_SCARAB = "Sulphite Scarab"
SULPHITE_SCARAB_OF_GREED = "Sulphite Scarab of Greed"
SULPHITE_SCARAB_OF_FUMES = "Sulphite Scarab of Fumes"
DIVINATION_SCARAB = "Divination Scarab"
DIVINATION_SCARAB_OF_CURATION = "Divination Scarab of Curation"
DIVINATION_SCARAB_OF_PILFERING = "Divination Scarab of Pilfering"
TORMENT_SCARAB = "Torment Scarab"
TORMENT_SCARAB_OF_PECULIARITY = "Torment Scarab of Peculiarity"
TORMENT_SCARAB_OF_RELEASE = "Torment Scarab of Release"
TORMENT_SCARAB_OF_POSSESSION = "Torment Scarab of Possession"
ANARCHY_SCARAB = "Anarchy Scarab"
ANARCHY_SCARAB_OF_GIGANTIFICATION = "Anarchy Scarab of Gigantification"
ANARCHY_SCARAB_OF_PARTNERSHIP = "Anarchy Scarab of Partnership"
RITUAL_SCARAB_OF_SELECTIVENESS = "Ritual Scarab of Selectiveness"
RITUAL_SCARAB_OF_RECOGNITION = "Ritual Scarab of Recognition"
RITUAL_SCARAB_OF_ABUNDANCE = "Ritual Scarab of Abundance"
HARVEST_SCARAB = "Harvest Scarab"
HARVEST_SCARAB_OF_DOUBLING = "Harvest Scarab of Doubling"
HARVEST_SCARAB_OF_CORNUCOPIA = "Harvest Scarab of Cornucopia"
BESTIARY_SCARAB = "Bestiary Scarab"
BESTIARY_SCARAB_OF_THE_HERD = "Bestiary Scarab of the Herd"
BESTIARY_SCARAB_OF_DUPLICATING = "Bestiary Scarab of Duplicating"
BESTIARY_SCARAB_OF_THE_SHADOWED_CROW = "Bestiary Scarab of the Shadowed Crow"
INFLUENCING_SCARAB_OF_THE_SHAPER = "Influencing Scarab of the Shaper"
INFLUENCING_SCARAB_OF_THE_ELDER = "Influencing Scarab of the Elder"
INFLUENCING_SCARAB_OF_HORDES = "Influencing Scarab of Hordes"
INFLUENCING_SCARAB_OF_CONVERSION = "Influencing Scarab of Conversion"
HARBINGER_SCARAB = "Harbinger Scarab"
HARBINGER_SCARAB_OF_DISCERNMENT = "Harbinger Scarab of Discernment"
HARBINGER_SCARAB_OF_REGENCY = "Harbinger Scarab of Regency"
HARBINGER_SCARAB_OF_WARHOARDS = "Harbinger Scarab of Warhoards"
ABYSS_SCARAB = "Abyss Scarab"
ABYSS_SCARAB_OF_MULTITUDES = "Abyss Scarab of Multitudes"
ABYSS_SCARAB_OF_EMPTINESS = "Abyss Scarab of Emptiness"
ABYSS_SCARAB_OF_EDIFICE = "Abyss Scarab of Edifice"
ABYSS_SCARAB_OF_PROFOUND_DEPTH = "Abyss Scarab of Profound Depth"
ESSENCE_SCARAB = "Essence Scarab"
ESSENCE_SCARAB_OF_ASCENT = "Essence Scarab of Ascent"
ESSENCE_SCARAB_OF_STABILITY = "Essence Scarab of Stability"
ESSENCE_SCARAB_OF_CALCIFICATION = "Essence Scarab of Calcification"
ESSENCE_SCARAB_OF_ADAPTATION = "Essence Scarab of Adaptation"
DOMINATION_SCARAB = "Domination Scarab"
DOMINATION_SCARAB_OF_ABNORMALITY = "Domination Scarab of Abnormality"
DOMINATION_SCARAB_OF_APPARITIONS = "Domination Scarab of Apparitions"
DOMINATION_SCARAB_OF_TERRORS = "Domination Scarab of Terrors"
INCURSION_SCARAB = "Incursion Scarab"
INCURSION_SCARAB_OF_INVASION = "Incursion Scarab of Invasion"
INCURSION_SCARAB_OF_CHAMPIONS = "Incursion Scarab of Champions"
INCURSION_SCARAB_OF_TIMELINES = "Incursion Scarab of Timelines"
BETRAYAL_SCARAB = "Betrayal Scarab"
BETRAYAL_SCARAB_OF_INTELLIGENCE = "Betrayal Scarab of Intelligence"
BETRAYAL_SCARAB_OF_REINFORCEMENTS = "Betrayal Scarab of Reinforcements"
BETRAYAL_SCARAB_OF_PERPETUATION = "Betrayal Scarab of Perpetuation"
BLIGHT_SCARAB = "Blight Scarab"
BLIGHT_SCARAB_OF_BOUNTY = "Blight Scarab of Bounty"
BLIGHT_SCARAB_OF_OILS = "Blight Scarab of Oils"
BLIGHT_SCARAB_OF_BLOOMING = "Blight Scarab of Blooming"
BLIGHT_SCARAB_OF_INVIGORATION = "Blight Scarab of Invigoration"
BREACH_SCARAB = "Breach Scarab"
BREACH_SCARAB_OF_THE_DREAMER = "Breach Scarab of the Dreamer"
BREACH_SCARAB_OF_LORDSHIP = "Breach Scarab of Lordship"
BREACH_SCARAB_OF_SPLINTERING = "Breach Scarab of Splintering"
BREACH_SCARAB_OF_SNARES = "Breach Scarab of Snares"
BREACH_SCARAB_OF_RESONANT_CASCADE = "Breach Scarab of Resonant Cascade"
LEGION_SCARAB = "Legion Scarab"
LEGION_SCARAB_OF_OFFICERS = "Legion Scarab of Officers"
LEGION_SCARAB_OF_COMMAND = "Legion Scarab of Command"
LEGION_SCARAB_OF_THE_SEKHEMA = "Legion Scarab of The Sekhema"
LEGION_SCARAB_OF_ETERNAL_CONFLICT = "Legion Scarab of Eternal Conflict"
CARTOGRAPHY_SCARAB = "Cartography Scarab"
CARTOGRAPHY_SCARAB_OF_ESCALATION = "Cartography Scarab of Escalation"
CARTOGRAPHY_SCARAB_OF_THE_MULTITUDE = "Cartography Scarab of the Multitude"
CARTOGRAPHY_SCARAB_OF_CORRUPTION = "Cartography Scarab of Corruption"
BEYOND_SCARAB = "Beyond Scarab"
BEYOND_SCARAB_OF_HAEMOPHILIA = "Beyond Scarab of Haemophilia"
BEYOND_SCARAB_OF_CORRUPTION = "Beyond Scarab of Corruption"
BEYOND_SCARAB_OF_RESURGENCE = "Beyond Scarab of Resurgence"
BEYOND_SCARAB_OF_THE_INVASION = "Beyond Scarab of the Invasion"
AMBUSH_SCARAB = "Ambush Scarab"
AMBUSH_SCARAB_OF_HIDDEN_COMPARTMENTS = "Ambush Scarab of Hidden Compartments"
AMBUSH_SCARAB_OF_POTENCY = "Ambush Scarab of Potency"
AMBUSH_SCARAB_OF_CONTAINMENT = "Ambush Scarab of Containment"
AMBUSH_SCARAB_OF_DISCERNMENT = "Ambush Scarab of Discernment"
ULTIMATUM_SCARAB = "Ultimatum Scarab"
ULTIMATUM_SCARAB_OF_BRIBING = "Ultimatum Scarab of Bribing"
ULTIMATUM_SCARAB_OF_DUELING = "Ultimatum Scarab of Dueling"
ULTIMATUM_SCARAB_OF_CATALYSING = "Ultimatum Scarab of Catalysing"
ULTIMATUM_SCARAB_OF_INSCRIPTION = "Ultimatum Scarab of Inscription"
EXPEDITION_SCARAB = "Expedition Scarab"
EXPEDITION_SCARAB_OF_RUNEFINDING = "Expedition Scarab of Runefinding"
EXPEDITION_SCARAB_OF_VERISIUM_POWDER = "Expedition Scarab of Verisium Powder"
EXPEDITION_SCARAB_OF_THE_SKALD = "Expedition Scarab of the Skald"
EXPEDITION_SCARAB_OF_ARCHAEOLOGY = "Expedition Scarab of Archaeology"
DELIRIUM_SCARAB = "Delirium Scarab"
DELIRIUM_SCARAB_OF_MANIA = "Delirium Scarab of Mania"
DELIRIUM_SCARAB_OF_PARANOIA = "Delirium Scarab of Paranoia"
DELIRIUM_SCARAB_OF_NEUROSES = "Delirium Scarab of Neuroses"
DELIRIUM_SCARAB_OF_DELUSIONS = "Delirium Scarab of Delusions"
KALGUURAN_SCARAB = "Kalguuran Scarab"
KALGUURAN_SCARAB_OF_GUARDED_RICHES = "Kalguuran Scarab of Guarded Riches"
KALGUURAN_SCARAB_OF_REFINEMENT = "Kalguuran Scarab of Refinement"
SCARAB_OF_MONSTROUS_LINEAGE = "Scarab of Monstrous Lineage"
SCARAB_OF_ADVERSARIES = "Scarab of Adversaries"
MYSTERIOUS_SCARAB = "Mysterious Scarab"
SCARAB_OF_HUNTED_TRAITORS = "Scarab of Hunted Traitors"
SCARAB_OF_STABILITY = "Scarab of Stability"
SCARAB_OF_WISPS = "Scarab of Wisps"
SCARAB_OF_RADIANT_STORMS = "Scarab of Radiant Storms"
HORNED_SCARAB_OF_BLOODLINES = "Horned Scarab of Bloodlines"
HORNED_SCARAB_OF_NEMESES = "Horned Scarab of Nemeses"
HORNED_SCARAB_OF_PRESERVATION = "Horned Scarab of Preservation"
HORNED_SCARAB_OF_AWAKENING = "Horned Scarab of Awakening"
HORNED_SCARAB_OF_TRADITION = "Horned Scarab of Tradition"
HORNED_SCARAB_OF_GLITTERING = "Horned Scarab of Glittering"
HORNED_SCARAB_OF_PANDEMONIUM = "Horned Scarab of Pandemonium"
