GEMS = "Gems"
MAPS = "Maps"
QUEST = "Quest Items"
GEAR = [
    "One Hand Axes",
    "Claws",
    "Thrusting One Hand Swords",
    "Staves",
    "One Hand Swords",
    "Sceptres",
    "One Hand Maces",
    "Daggers",
    "Abyss Jewels",
    "Rune Daggers",
    "Shields",
    "Warstaves",
    "Wands",
    "Two Hand Axes",
    "Two Hand Maces",
    "Two Hand Swords",
    "Hybrid Flasks",
    "Life Flasks",
    "Mana Flasks",
    "Boots",
    "Body Armours",
    "Gloves",
    "Helmets",
    "Amulets",
    "Rings",
    "Belts",
    "Bows",
    "Quivers",
    "Jewels",
    "Utility Flasks",
]
