cards = [
    "A Chilling Wind",
    "A Dab of Ink",
    "A Dusty Memory",
    "A Familiar Call",
    "A Fate Worse Than Death",
    "A Modest Request",
    "A Mother's Parting Gift",
    "A Note in the Wind",
    "A Sea of Blue",
    "A Stone Perfected",
    "Abandoned Wealth",
    "Acclimatisation",
    "Akil's Prophecy",
    "Alivia's Grace",
    "Alluring Bounty",
    "Alone in the Darkness",
    "Altered Perception",
    "Ambitious Obsession",
    "Anarchy's Price",
    "Arrogance of the Vaal",
    "Assassin's Favour",
    "Assassin's Gift",
    "Astral Protection",
    "Atziri's Arsenal",
    "Audacity",
    "Auspicious Ambitions",
    "Azure Rage",
    "Azyran's Reward",
    "Baited Expectations",
    "Beauty Through Death",
    "Bijoux",
    "Blind Venture",
    "Boon of Justice",
    "Boon of the First Ones",
    "Boundless Realms",
    "Bowyer's Dream",
    "Broken Promises",
    "Broken Truce",
    "Brother's Gift",
    "Brother's Stash",
    "Brotherhood in Exile",
    "Brush, Paint and Palette",
    "Buried Treasure",
    "Burning Blood",
    "Call to the First Ones",
    "Cameria's Cut",
    "Cartographer's Delight",
    "Chaotic Disposition",
    "Chasing Risk",
    "Checkmate",
    "Choking Guilt",
    "Costly Curio",
    "Council of Cats",
    "Coveted Possession",
    "Cursed Words",
    "Dark Dreams",
    "Dark Temptation",
    "Darker Half",
    "Deadly Joy",
    "Death",
    "Deathly Designs",
    "Dementophobia",
    "Demigod's Wager",
    "Desecrated Virtue",
    "Desperate Crusade",
    "Destined to Crumble",
    "Dialla's Subjugation",
    "Disdain",
    "Divine Beauty",
    "Doedre's Madness",
    "Draped in Dreams",
    "Duality",
    "Dying Light",
    "Earth Drinker",
    "Echoes of Love",
    "Eldritch Perfection",
    "Emperor of Purity",
    "Emperor's Luck",
    "Endless Night",
    "Etched in Blood",
    "Eternal Bonds",
    "Ever-Changing",
    "Fateful Meeting",
    "Fire Of Unknown Origin",
    "Forbidden Power",
    "From Bone to Ashes",
    "Further Invention",
    "Gemcutter's Mercy",
    "Gemcutter's Promise",
    "Gift of Asenath",
    "Gift of the Gemling Queen",
    "Glimmer of Hope",
    "Grave Knowledge",
    "Guardian's Challenge",
    "Harmony of Souls",
    "Haunting Shadows",
    "Her Mask",
    "Heterochromia",
    "Home",
    "Hope",
    "House of Mirrors",
    "Hubris",
    "Humility",
    "Hunter's Resolve",
    "Hunter's Reward",
    "I See Brothers",
    "Immortal Resolve",
    "Imperfect Memories",
    "Imperial Legacy",
    "Jack in the Box",
    "Judging Voices",
    "Justified Ambition",
    "Keeper's Corruption",
    "Lachrymal Necrosis",
    "Lantador's Lost Love",
    "Last Hope",
    "Left to Fate",
    "Lethean Temptation",
    "Light and Truth",
    "Lingering Remnants",
    "Lost Worlds",
    "Love Through Ice",
    "Loyalty",
    "Lucky Connections",
    "Lucky Deck",
    "Luminous Trove",
    "Lysah's Respite",
    "Magnum Opus",
    "Man With Bear",
    "Matryoshka",
    "Mawr Blaidd",
    "Merciless Armament",
    "Might is Right",
    "Misery in Darkness",
    "Mitts",
    "Monochrome",
    "More is Never Enough",
    "No Traces",
    "Nook's Crown",
    "Parasitic Passengers",
    "Peaceful Moments",
    "Perfection",
    "Poisoned Faith",
    "Prejudice",
    "Pride Before the Fall",
    "Pride of the First Ones",
    "Prometheus' Armoury",
    "Prosperity",
    "Rain of Chaos",
    "Rain Tempter",
    "Rats",
    "Rebirth",
    "Rebirth and Renewal",
    "Reckless Ambition",
    "Remembrance",
    "Sambodhi's Vow",
    "Sambodhi's Wisdom",
    "Scholar of the Seas",
    "Seven Years Bad Luck",
    "Shard of Fate",
    "Silence and Frost",
    "Society's Remorse",
    "Something Dark",
    "Soul Quenched",
    "Struck by Lightning",
    "Succor of the Sinless",
    "The Academic",
    "The Admirer",
    "The Adventuring Spirit",
    "The Aesthete",
    "The Apothecary",
    "The Archmage's Right Hand",
    "The Arena Champion",
    "The Army of Blood",
    "The Artist",
    "The Aspirant",
    "The Astromancer",
    "The Avenger",
    "The Awakened",
    "The Battle Born",
    "The Bear Woman",
    "The Beast",
    "The Betrayal",
    "The Bitter Blossom",
    "The Blazing Fire",
    "The Body",
    "The Bones",
    "The Brawny Battle Mage",
    "The Breach",
    "The Brittle Emperor",
    "The Cache",
    "The Cacophony",
    "The Calling",
    "The Card Sharp",
    "The Carrion Crow",
    "The Cartographer",
    "The Cataclysm",
    "The Catalyst",
    "The Catch",
    "The Celestial Justicar",
    "The Celestial Stone",
    "The Chains that Bind",
    "The Cheater",
    "The Chosen",
    "The Coming Storm",
    "The Conduit",
    "The Craving",
    "The Cursed King",
    "The Damned",
    "The Dapper Prodigy",
    "The Dark Mage",
    "The Darkest Dream",
    "The Deal",
    "The Deceiver",
    "The Deep Ones",
    "The Demon",
    "The Demoness",
    "The Destination",
    "The Doctor",
    "The Doppelganger",
    "The Dragon",
    "The Dragon's Heart",
    "The Dreamer",
    "The Dreamland",
    "The Drunken Aristocrat",
    "The Dungeon Master",
    "The Easy Stroll",
    "The Eldritch Decay",
    "The Emptiness",
    "The Encroaching Darkness",
    "The Endless Darkness",
    "The Endurance",
    "The Enforcer",
    "The Enlightened",
    "The Enthusiasts",
    "The Escape",
    "The Eternal War",
    "The Ethereal",
    "The Explorer",
    "The Eye of Terror",
    "The Eye of the Dragon",
    "The Fathomless Depths",
    "The Feast",
    "The Fiend",
    "The Finishing Touch",
    "The Fishmonger",
    "The Fletcher",
    "The Flora's Gift",
    "The Fool",
    "The Forgotten Treasure",
    "The Formless Sea",
    "The Forsaken",
    "The Fortunate",
    "The Forward Gaze",
    "The Fox",
    "The Fox in the Brambles",
    "The Gambler",
    "The Garish Power",
    "The Gemcutter",
    "The Gentleman",
    "The Gladiator",
    "The Golden Era",
    "The Greatest Intentions",
    "The Gulf",
    "The Hale Heart",
    "The Harvester",
    "The Hermit",
    "The Heroic Shot",
    "The Hive of Knowledge",
    "The Hoarder",
    "The Hunger",
    "The Immortal",
    "The Incantation",
    "The Innocent",
    "The Inoculated",
    "The Insane Cat",
    "The Insatiable",
    "The Inventor",
    "The Jester",
    "The Jeweller's Boon",
    "The Journalist",
    "The Journey",
    "The King's Blade",
    "The King's Heart",
    "The Landing",
    "The Last One Standing",
    "The Last Supper",
    "The Leviathan",
    "The Lich",
    "The Life Thief",
    "The Lion",
    "The Long Con",
    "The Lord in Black",
    "The Lord of Celebration",
    "The Lover",
    "The Lunaris Priestess",
    "The Mad King",
    "The Magma Crab",
    "The Master",
    "The Master Artisan",
    "The Mercenary",
    "The Messenger",
    "The Metalsmith's Gift",
    "The Mind's Eyes",
    "The Mountain",
    "The Nurse",
    "The Oath",
    "The Obscured",
    "The Offering",
    "The Offspring",
    "The Old Man",
    "The One That Got Away",
    "The One With All",
    "The Opulent",
    "The Pack Leader",
    "The Pact",
    "The Patient",
    "The Penitent",
    "The Poet",
    "The Polymath",
    "The Porcupine",
    "The Price of Devotion",
    "The Price of Loyalty",
    "The Price of Prescience",
    "The Price of Protection",
    "The Primordial",
    "The Prince of Darkness",
    "The Professor",
    "The Progeny of Lunaris",
    "The Puzzle",
    "The Queen",
    "The Rabbit's Foot",
    "The Rabid Rhoa",
    "The Realm",
    "The Return of the Rat",
    "The Risk",
    "The Rite of Elements",
    "The Road to Power",
    "The Rusted Bard",
    "The Ruthless Ceinture",
    "The Sacrifice",
    "The Saint's Treasure",
    "The Samurai's Eye",
    "The Scarred Meadow",
    "The Scavenger",
    "The Scholar",
    "The Scout",
    "The Seeker",
    "The Sephirot",
    "The Shepherd's Sandals",
    "The Shieldbearer",
    "The Shortcut",
    "The Side Quest",
    "The Sigil",
    "The Siren",
    "The Skeleton",
    "The Soul",
    "The Spark and the Flame",
    "The Spoiled Prince",
    "The Standoff",
    "The Stormcaller",
    "The Strategist",
    "The Summoner",
    "The Sun",
    "The Surgeon",
    "The Surveyor",
    "The Survivalist",
    "The Sword King's Salute",
    "The Thaumaturgist",
    "The Throne",
    "The Tinkerer's Table",
    "The Tireless Extractor",
    "The Tower",
    "The Traitor",
    "The Transformation",
    "The Trial",
    "The Tumbleweed",
    "The Twilight Moon",
    "The Twins",
    "The Tyrant",
    "The Undaunted",
    "The Undisputed",
    "The Unexpected Prize",
    "The Union",
    "The Valkyrie",
    "The Vast",
    "The Visionary",
    "The Void",
    "The Warden",
    "The Warlord",
    "The Watcher",
    "The Web",
    "The Wedding Gift",
    "The White Knight",
    "The Whiteout",
    "The Wilted Rose",
    "The Wind",
    "The Witch",
    "The Wolf",
    "The Wolf's Legacy",
    "The Wolf's Shadow",
    "The Wolven King's Bite",
    "The Wolverine",
    "The World Eater",
    "The Wrath",
    "The Wretched",
    "Thirst for Knowledge",
    "Three Faces in the Dark",
    "Three Voices",
    "Thunderous Skies",
    "Time-Lost Relic",
    "Tranquillity",
    "Treasure Hunter",
    "Triskaidekaphobia",
    "Turn the Other Cheek",
    "Unchained",
    "Underground Forest",
    "Unrequited Love",
    "Vanity",
    "Vile Power",
    "Vinia's Token",
    "Void of the Elements",
    "Volatile Power",
    "Wealth and Power",
    "Who Asked",
    "Winter's Embrace",
]
