from app.blocks import *
from app.actions import *
from app.categories import *
from app.conditions import *
from app.rule_map import *

rule_map = {
    # Currency
    "Orb of Transmutation": RULE.HIDE,
    "Orb of Augmentation": RULE.HIDE,
    "Orb of Alchemy": RULE.HIDE,
    "Orb of Chance": RULE.HIDE,
    "Orb of Binding": RULE.HIDE,
    "Armourer's Scrap": RULE.HIDE,
    "Blacksmith's Whetstone": RULE.RARE,  # Only shown for spectral throw leveling
    "Chromatic Orb": RULE.EPIC,
    "Jeweller's Orb": RULE.HIDE,
    "Orb of Fusing": RULE.HIDE,
    "Instilling Orb": RULE.HIDE,
    "Enkindling Orb": RULE.HIDE,
    "Gemcutter's Prism": RULE.HIDE,
    "Orb of Alteration": RULE.EPIC,
    "Chaos Orb": RULE.EPIC,
    "Exalted Orb": RULE.EPIC,
    "Orb of Unmaking": RULE.HIDE,
    "Orb of Scouring": RULE.HIDE,
    "Blessed Orb": RULE.HIDE,
    "Orb of Regret": RULE.HIDE,
    "Regal Orb": RULE.HIDE,
    "Divine Orb": RULE.LEGENDARY,
    "Vaal Orb": RULE.EPIC,
    "Ancient Orb": RULE.EPIC,
    "Orb of Annulment": RULE.LEGENDARY,
    "Fracturing Orb": RULE.LEGENDARY,
    "Glassblower's Bauble": RULE.EPIC,
    "Mirror of Kalandra": RULE.LEGENDARY,
    "Tempering Orb": RULE.LEGENDARY,
    "Tailoring Orb": RULE.LEGENDARY,
    "Maven's Chisel of Procurement": RULE.EPIC,
    "Maven's Chisel of Proliferation": RULE.EPIC,
    "Maven's Chisel of Scarabs": RULE.EPIC,
    "Maven's Chisel of Avarice": RULE.EPIC,
    "Maven's Chisel of Divination": RULE.EPIC,
    "Volatile Vaal Orb": RULE.EPIC,
    "Veiled Exalted Orb": RULE.LEGENDARY,
    "Veiled Chaos Orb": RULE.LEGENDARY,
    "Sacred Orb": RULE.LEGENDARY,
    "Refracting Fog": RULE.LEGENDARY,
    "Scrying Orb": RULE.LEGENDARY,
    # Exotic currency
    "Orb of Intention": RULE.LEGENDARY,
    "Orb of Unravelling": RULE.LEGENDARY,
    "Orb of Remembrance": RULE.LEGENDARY,
    "Shaper's Exalted Orb": RULE.LEGENDARY,
    "Elder's Exalted Orb": RULE.LEGENDARY,
    "Crusader's Exalted Orb": RULE.LEGENDARY,
    "Redeemer's Exalted Orb": RULE.LEGENDARY,
    "Hunter's Exalted Orb": RULE.LEGENDARY,
    "Warlord's Exalted Orb": RULE.LEGENDARY,
    "Awakener's Orb": RULE.LEGENDARY,
    "Orb of Dominance": RULE.LEGENDARY,
    "Eldritch Chaos Orb": RULE.LEGENDARY,
    "Eldritch Exalted Orb": RULE.LEGENDARY,
    "Eldritch Orb of Annulment": RULE.LEGENDARY,
    "Lesser Eldritch Ember": RULE.RARE,
    "Greater Eldritch Ember": RULE.RARE,
    "Grand Eldritch Ember": RULE.LEGENDARY,
    "Exceptional Eldritch Ember": RULE.LEGENDARY,
    "Lesser Eldritch Ichor": RULE.RARE,
    "Greater Eldritch Ichor": RULE.RARE,
    "Grand Eldritch Ichor": RULE.LEGENDARY,
    "Exceptional Eldritch Ichor": RULE.LEGENDARY,
    "Orb of Conflict": RULE.LEGENDARY,
    "Tainted Chromatic Orb": RULE.EPIC,
    "Tainted Orb of Fusing": RULE.LEGENDARY,
    "Tainted Jeweller's Orb": RULE.EPIC,
    "Tainted Chaos Orb": RULE.LEGENDARY,
    "Tainted Exalted Orb": RULE.LEGENDARY,
    "Tainted Mythic Orb": RULE.LEGENDARY,
    "Tainted Armourer's Scrap": RULE.EPIC,
    "Tainted Blacksmith's Whetstone": RULE.EPIC,
    "Tainted Divine Teardrop": RULE.LEGENDARY,
    "Wild Crystallised Lifeforce": RULE.EPIC,
    "Vivid Crystallised Lifeforce": RULE.EPIC,
    "Primal Crystallised Lifeforce": RULE.EPIC,
    "Sacred Crystallised Lifeforce": RULE.EPIC,
    "Crystallised Rancour": RULE.EPIC,
    "Hinekora's Lock": RULE.LEGENDARY,
    # Shards & Splinters
    "Alteration Shard": RULE.EPIC,
    "Alchemy Shard": RULE.RARE,
    "Engineer's Shard": RULE.LEGENDARY,
    "Annulment Shard": RULE.LEGENDARY,
    "Fracturing Shard": RULE.LEGENDARY,
    "Mirror Shard": RULE.LEGENDARY,
    # Legion
    "Timeless Eternal Empire Splinter": RULE.EPIC,
    "Timeless Karui Splinter": RULE.EPIC,
    "Timeless Vaal Splinter": RULE.EPIC,
    "Timeless Templar Splinter": RULE.EPIC,
    "Timeless Maraketh Splinter": RULE.EPIC,
    "Simulacrum Splinter": RULE.EPIC,
    "Crescent Splinter": RULE.EPIC,
    # Fragments
    "Sacrifice at Dusk": RULE.RARE,
    "Sacrifice at Midnight": RULE.RARE,
    "Sacrifice at Dawn": RULE.RARE,
    "Sacrifice at Noon": RULE.RARE,
    "Mortal Grief": RULE.RARE,
    "Mortal Rage": RULE.RARE,
    "Mortal Hope": RULE.RARE,
    "Mortal Ignorance": RULE.RARE,
    "Fragment of the Hydra": RULE.LEGENDARY,
    "Fragment of the Phoenix": RULE.LEGENDARY,
    "Fragment of the Minotaur": RULE.LEGENDARY,
    "Fragment of the Chimera": RULE.LEGENDARY,
    "Fragment of Enslavement": RULE.LEGENDARY,
    "Fragment of Eradication": RULE.LEGENDARY,
    "Fragment of Constriction": RULE.LEGENDARY,
    "Fragment of Purification": RULE.LEGENDARY,
    "Fragment of Terror": RULE.LEGENDARY,
    "Fragment of Emptiness": RULE.LEGENDARY,
    "Fragment of Shape": RULE.LEGENDARY,
    "Fragment of Knowledge": RULE.LEGENDARY,
    "Al-Hezmin's Crest": RULE.LEGENDARY,
    "Baran's Crest": RULE.LEGENDARY,
    "Drox's Crest": RULE.LEGENDARY,
    "Veritania's Crest": RULE.LEGENDARY,
    "Simulacrum": RULE.LEGENDARY,
    "Sacred Blossom": RULE.LEGENDARY,
    "Syndicate Medallion": RULE.LEGENDARY,
    "Ritual Vessel": RULE.EPIC,
    "Blood-filled Vessel": RULE.EPIC,
    "The Maven's Writ": RULE.LEGENDARY,
    "Writhing Invitation": RULE.LEGENDARY,
    "Screaming Invitation": RULE.LEGENDARY,
    "Polaric Invitation": RULE.LEGENDARY,
    "Incandescent Invitation": RULE.LEGENDARY,
    "Ancient Reliquary Key": RULE.LEGENDARY,
    "Timeworn Reliquary Key": RULE.LEGENDARY,
    "Vaal Reliquary Key": RULE.LEGENDARY,
    "Forgotten Reliquary Key": RULE.LEGENDARY,
    "Visceral Reliquary Key": RULE.LEGENDARY,
    "Shiny Reliquary Key": RULE.LEGENDARY,
    "Archive Reliquary Key": RULE.LEGENDARY,
    "Oubliette Reliquary Key": RULE.LEGENDARY,
    "Cosmic Reliquary Key": RULE.LEGENDARY,
    "Decaying Reliquary Key": RULE.LEGENDARY,
    "Voidborn Reliquary Key": RULE.LEGENDARY,
    "Valdo's Puzzle Box": RULE.LEGENDARY,
    "Divine Vessel": RULE.HIDE,
    "Offering to the Goddess": RULE.HIDE,
    "Gift to the Goddess": RULE.EPIC,
    "Tribute to the Goddess": RULE.EPIC,
    # Sanctum
    "Forbidden Tome": RULE.HIDE,
    # Expedition
    "Astragali": RULE.EPIC,
    "Exotic Coinage": RULE.EPIC,
    "Scrap Metal": RULE.EPIC,
    "Burial Medallion": RULE.EPIC,
    "Expedition Logbook": RULE.LEGENDARY,
    # Labyrinth
    "Golden Key": RULE.EPIC,
    "Treasure Key": RULE.EPIC,
    "Silver Key": RULE.RARE,
    # Incursion
    "Stone of Passage": RULE.LEGENDARY,
    "Chronicle of Atzoatl": RULE.LEGENDARY,
    # Uber fragments
    "Synthesising Fragment": RULE.LEGENDARY,
    "Devouring Fragment": RULE.LEGENDARY,
    "Blazing Fragment": RULE.LEGENDARY,
    "Reality Fragment": RULE.LEGENDARY,
    "Cosmic Fragment": RULE.LEGENDARY,
    "Awakening Fragment": RULE.LEGENDARY,
    "Decaying Fragment": RULE.LEGENDARY,
    "Traumatic Fragment": RULE.LEGENDARY,
    "Lonely Fragment": RULE.LEGENDARY,
    "Reverent Fragment": RULE.LEGENDARY,
    # Venarius Echos
    "Echo of Trauma": RULE.LEGENDARY,
    "Echo of Reverence": RULE.LEGENDARY,
    "Echo of Loneliness": RULE.LEGENDARY,
    "Memory of Trauma": RULE.LEGENDARY,
    "Memory of Reverence": RULE.LEGENDARY,
    "Memory of Loneliness": RULE.LEGENDARY,
    # Breach
    "Flesh of Xesht": RULE.LEGENDARY,
    "Hivebrain Gland": RULE.LEGENDARY,
    # Curse of the Allflame
    "Dead Man's Sulphur": RULE.EPIC,
    "Message in a Bottle": RULE.EPIC,
}

rules = [
    *map_to_rules(rule_map),
    Show(
        [
            BaseType("Oil", OPERATOR.CONTAINS),
            Class("Stackable Currency"),
            TierStyle(TIER.EPIC),
        ]
    ),
    Show([BaseType("Allflame", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Show([BaseType("Tattoo", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Show([BaseType("Catalyst", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Show([BaseType("Wombgift", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Show([BaseType("Runegraft", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Show([BaseType("Astrolabe", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Show([BaseType("Enshrouding Crystal", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Show([BaseType("Chart", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Show([BaseType("Ducat", OPERATOR.CONTAINS), TierStyle(TIER.EPIC)]),
    Hide([BaseType("Gold")]),
]
